<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 4               */
/* CACHE FILE: Generated: Wed, 18 May 2016 17:28:36 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_reviews_view_4 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['view_the_review'] = array('showParentName','hasProductImage','showDetailedRatings','isMember');


}

/* -- add_rating_page --*/
function add_rating_page($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['links']}
<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=do_rate&amp;id={$data['id']}&amp;rating={$data['rating']}'>
<h3 class='maintitle'>{$this->lang->words['add_review_rating']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container ipsPad'>
<fieldset>
<ul class='ipsForm ipsForm_horizontal'>
<li class='ipsField'>
<label class='ipsField_title'>{$this->lang->words['add_rating_header']}</label>
<div class='ipsField_content'>{$data['title']}<span class='desc'></span>
</div>
</li>
<li class='ipsField ipsField_select'>
<label class='ipsField_title'>{$this->lang->words['add_rating_header_2']}</label>
<div class='ipsField_content'>{$data['rating_image']}<span class='desc'></span>
</div>
</li>
</ul>
</fieldset>
</div>
</div>
<fieldset class='submit'>
{$this->lang->words['add_msg_rating']}<br /><br />
<input type=\"submit\" value=\"{$this->lang->words['submit']}\" tabindex=\"0\" class=\"input_submit\" />
</fieldset>
</form>
<br />";
return $IPBHTML;
}

/* -- options_box_normal --*/
function options_box_normal($id="",$approve="",$mid="",$tracky="",$sendy="",$admin=0) {
$IPBHTML = "";
$IPBHTML .= "" . (($admin == '1') ? ("" . (( $approve != '0') ? ("" . (( $approve == '1') ? ("
<input type='button' id='revopts' value='{$this->lang->words['mod_options1']}' class='input_submit alt ipbmenu' />
<ul class='ipbmenu_content' id='revopts_menucontent'>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=edit&amp;do=edit&amp;id={$id}'>{$this->lang->words['edit']}</a></li>
<li>{$tracky}</li>
{$sendy}
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=controls&amp;do=ban&amp;id={$mid}'>{$this->lang->words['ban_member']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=approve&amp;do=approve&amp;id={$id}'>{$this->lang->words['approve']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=approve&amp;do=decline&amp;id={$id}'>{$this->lang->words['decline']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=approve&amp;do=redirect&amp;id={$id}&amp;redirect=1'>{$this->lang->words['option_redirect']}</a></li>
</ul>
") : ("
<input type='button' id='revopts' value='{$this->lang->words['mod_options1']}' class='input_submit alt ipbmenu' />
<ul class='ipbmenu_content' id='revopts_menucontent'>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=edit&amp;do=edit&amp;id={$id}'>{$this->lang->words['edit']}</a></li>
<li>{$tracky}</li>
{$sendy}
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=takeaction&amp;do=takeaction&amp;id={$id}'>{$this->lang->words['take_action']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=approve&amp;do=redirect&amp;id={$id}&amp;redirect=2'>{$this->lang->words['option_redirect']}</a></li>
</ul>
")) . "") : ("
<input type='button' id='revopts' value='{$this->lang->words['mod_options1']}' class='input_submit alt ipbmenu' />
<ul class='ipbmenu_content' id='revopts_menucontent'>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=edit&amp;do=edit&amp;id={$id}'>{$this->lang->words['edit']}</a></li>
<li>{$tracky}</li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=move&amp;id={$id}'>{$this->lang->words['move']}</a></li>
{$sendy}
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=report&amp;do=reportpage&amp;id={$id}'>{$this->lang->words['report_as_wrong']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=approve&amp;do=redirect&amp;id={$id}&amp;redirect=2'>{$this->lang->words['option_redirect']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=controls&amp;do=ban&amp;id={$mid}'>{$this->lang->words['ban_member']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=deletepage&amp;id={$id}'>{$this->lang->words['delete_color']}</a></li>
</ul>
")) . "") : ("
<input type='button' id='revopts' value='{$this->lang->words['mod_options1']}' class='input_submit alt ipbmenu' />
<ul class='ipbmenu_content' id='revopts_menucontent'>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=edit&amp;do=edit&amp;id={$id}'>{$this->lang->words['edit']}</a></li>
<li>{$tracky}</li>
<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=reports&amp;rcom=review&amp;id={$id}", "public",'' ), "", "" ) . "'>{$this->lang->words['report_as_wrong']}</a></li>
</ul>
")) . "";
return $IPBHTML;
}

/* -- options_box_rate --*/
function options_box_rate($id="",$sendy="",$tracky="") {
$IPBHTML = "";
$IPBHTML .= "<input type='button' id='revopts' value='{$this->lang->words['mod_options1']}' class='input_submit alt ipbmenu' />
<ul class='ipbmenu_content' id='revopts_menucontent'>
<li>{$tracky}</li>
{$sendy}
<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=reports&amp;rcom=review&amp;id={$id}", "public",'' ), "", "" ) . "'>{$this->lang->words['report_as_wrong']}</a></li>
{$this->lang->words['rate_review']}
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=1'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_1.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=2'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_2.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=3'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_3.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=4'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_4.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=5'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_5.png' alt='{$this->lang->words['img_rating']}' /></a></li>
</ul>";
return $IPBHTML;
}

/* -- options_box_report --*/
function options_box_report($id="",$sendy="",$tracky="") {
$IPBHTML = "";
$IPBHTML .= "<input type='button' id='revopts' value='{$this->lang->words['mod_options1']}' class='input_submit alt ipbmenu' />
<ul class='ipbmenu_content' id='revopts_menucontent'>
<li>{$tracky}</li>
{$sendy}
<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=reports&amp;rcom=review&amp;id={$id}", "public",'' ), "", "" ) . "'>{$this->lang->words['report_as_wrong']}</a></li>
</ul>";
return $IPBHTML;
}

/* -- options_box_special --*/
function options_box_special($id="",$approve="",$mid="",$tracky="",$sendy="") {
$IPBHTML = "";
$IPBHTML .= "" . (( $approve != '0') ? ("" . (( $approve == '1') ? ("
<input type='button' id='revopts' value='{$this->lang->words['mod_options1']}' class='input_submit alt ipbmenu' />
<ul class='ipbmenu_content' id='revopts_menucontent'>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=edit&amp;do=edit&amp;id={$id}'>{$this->lang->words['edit']}</a></li>
<li>{$tracky}</li>
{$sendy}
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=controls&amp;do=ban&amp;id={$mid}'>{$this->lang->words['ban_member']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=approve&amp;do=approve&amp;id={$id}'>{$this->lang->words['approve']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=approve&amp;do=decline&amp;id={$id}'>{$this->lang->words['decline']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=approve&amp;do=redirect&amp;id={$id}&amp;redirect=1'>{$this->lang->words['option_redirect']}</a></li>
{$this->lang->words['rate_review']}
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=1'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_1.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=2'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_2.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=3'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_3.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=4'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_4.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=5'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_5.png' alt='{$this->lang->words['img_rating']}' /></a></li>
</ul>
") : ("
<input type='button' id='revopts' value='{$this->lang->words['mod_options1']}' class='input_submit alt ipbmenu' />
<ul class='ipbmenu_content' id='revopts_menucontent'>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=edit&amp;do=edit&amp;id={$id}'>{$this->lang->words['edit']}</a></li>
<li>{$tracky}</li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=move&amp;id={$id}'>{$this->lang->words['move']}</a></li>
{$sendy}
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=takeaction&amp;do=takeaction&amp;id={$id}'>{$this->lang->words['take_action']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=approve&amp;do=redirect&amp;id={$id}&amp;redirect=2'>{$this->lang->words['option_redirect']}</a></li>
{$this->lang->words['rate_review']}
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=1'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_1.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=2'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_2.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=3'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_3.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=4'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_4.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=5'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_5.png' alt='{$this->lang->words['img_rating']}' /></a></li>
</ul>
")) . "") : ("
<input type='button' id='revopts' value='{$this->lang->words['mod_options1']}' class='input_submit alt ipbmenu' />
<ul class='ipbmenu_content' id='revopts_menucontent'>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=edit&amp;do=edit&amp;id={$id}'>{$this->lang->words['edit']}</a></li>
<li>{$tracky}</li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=move&amp;id={$id}'>{$this->lang->words['move']}</a></li>
{$sendy}
<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=reports&amp;rcom=review&amp;id={$id}", "public",'' ), "", "" ) . "'>{$this->lang->words['report_as_wrong']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=approve&amp;do=redirect&amp;id={$id}&amp;redirect=2'>{$this->lang->words['option_redirect']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=controls&amp;do=ban&amp;id={$mid}'>{$this->lang->words['ban_member']}</a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=deletepage&amp;id={$id}'>{$this->lang->words['delete_color']}</a></li>
{$this->lang->words['rate_review']}
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=1'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_1.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=2'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_2.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=3'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_3.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=4'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_4.png' alt='{$this->lang->words['img_rating']}' /></a></li>
<li><a href='{$this->settings['base_url']}app=reviews&amp;module=reviews&amp;section=rate&amp;do=rate&amp;id={$id}&amp;rating=5'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_rating_5.png' alt='{$this->lang->words['img_rating']}' /></a></li>
</ul>
")) . "";
return $IPBHTML;
}

/* -- review_comments_row --*/
function review_comments_row($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<tr class='{$data['rowclass']}' id='comment{$data['id']}'>
<td align='center' valign='top'>
{$data['photo']}
</td>
<td class='altrow' valign='top'>
<div style=\"float: left;\">
<p class='desc'>
{$this->lang->words['posted_on']}{$data['date']}{$this->lang->words['posted_by']}<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=authors&amp;section=profile&amp;do=profile&amp;id={$data['mid']}", "public",'' ), "{$data['members_seo_name']}", "showrevuser" ) . "'>{$data['author']}</a></strong>
" . (( $data['members_display_name'] == "") ? ("
{$data['mem_name']}
") : ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'user_popup' ) ? $this->registry->getClass('output')->getTemplate('global')->user_popup($data['mid'], $data['members_display_name']) : '' ) . "
")) . "</p></div><div style=\"float: right;\">
" . (( $data['extra'] == '1') ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=reports&amp;rcom=review&amp;id={$data['rid']}&amp;comment_id={$data['id']}", "public",'' ), "", "" ) . "'>
<img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/report.png' alt='{$this->lang->words['report_comment']}' title='{$this->lang->words['report_comment']}' /></a>
" . (( $data['extra2'] == '1') ? ("
<a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=delete_comment&amp;id={$data['id']}'><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/comment_delete.png' alt='{$this->lang->words['comment_delete']}' title='{$this->lang->words['comment_delete']}' /></a>
") : ("")) . "") : ("")) . "
</div><br /><br />
{$data['comment']}
</td>
</tr>";
return $IPBHTML;
}

/* -- view_all_by_member --*/
function view_all_by_member($data=array(),$selected=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['linkbar']}
" . (( $data['rows'] != "") ? ("<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=authors&amp;section=content&amp;do=viewallbymember&amp;id={$data['id']}", "public",'' ), "{$data['memebrs_seo_name']}", "showrevmember" ) . "' method='post'>
<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr class='header'><th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['verdict']}</th><th scope='col' style=\"width:53%\">{$this->lang->words['review_title']}</th><th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['reader_rating']}</th><th scope='col' style=\"width:7%;text-align:center\">{$this->lang->words['views']}</th><th scope='col' style=\"width:20%;text-align:center\" colspan=\"2\">{$this->lang->words['overall_rating']}</th></tr>
{$data['rows']}
<tr class='unread'><td class='altrow' colspan='6' align='right'>
<select name='key' class='codebuttons'>
<option value='awards'{$selected['awards']}>{$this->lang->words['awards']}</option>
<option value='date'{$selected['date']}>{$this->lang->words['date']}</option>
<option value='updated'{$selected['updated']}>{$this->lang->words['updated']}</option>
<option value='since_last_visit'{$selected['since_last_visit']}>{$this->lang->words['since_last_visit']}</option>
<option value='overall'{$selected['overall']}>{$this->lang->words['overall_rating']}</option>
<option value='rrating'{$selected['rrating']}>{$this->lang->words['reader_rating']}</option>
<option value='name'{$selected['name']}>{$this->lang->words['review_title']}</option>
<option value='status'{$selected['status']}>{$this->lang->words['status']}</option>
<option value='verdict'{$selected['verdict']}>{$this->lang->words['verdict']}</option>
<option value='views'{$selected['views']}>{$this->lang->words['views']}</option>
</select>&nbsp;
<select name='order' class='codebuttons'>
<option value='ASC'{$selected['ASC']}>{$this->lang->words['asc']}</option>
<option value='DESC'{$selected['DESC']}>{$this->lang->words['desc']}</option>
</select>&nbsp;
" . (($data['is_mr_mod'] == 1) ? ("
<input type='submit' value='{$this->lang->words['sortdelete']}' class='input_submit' />
") : ("
<input type='submit' value='{$this->lang->words['sort']}' class='input_submit' />
")) . "
</td></tr>
</table>
</div>
</div>
</form>
<br />
" . (($data['links'] != "") ? ("
<div class='topic_controls'>
{$data['links']}
</div>
") : ("")) . "") : ("<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=authors&amp;section=content&amp;do=viewallbymember&amp;id={$data['id']}", "public",'' ), "{$data['memebrs_seo_name']}", "showrevmember" ) . "' method='post'>
<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row1' align='center'>{$this->lang->words['no_reviews_sort']}</td></tr>
" . (($data['show_sort'] == '1') ? ("<tr class='row2'><td class='altrow' align='right'>
<select name='key' class='codebuttons'>
<option value='awards'{$selected['awards']}>{$this->lang->words['awards']}</option>
<option value='date'{$selected['date']}>{$this->lang->words['date']}</option>
<option value='updated'{$selected['updated']}>{$this->lang->words['updated']}</option>
<option value='since_last_visit'{$selected['since_last_visit']}>{$this->lang->words['since_last_visit']}</option>
<option value='overall'{$selected['overall']}>{$this->lang->words['overall_rating']}</option>
<option value='rrating'{$selected['rrating']}>{$this->lang->words['reader_rating']}</option>
<option value='name'{$selected['name']}>{$this->lang->words['review_title']}</option>
<option value='status'{$selected['status']}>{$this->lang->words['status']}</option>
<option value='verdict'{$selected['verdict']}>{$this->lang->words['verdict']}</option>
<option value='views'{$selected['views']}>{$this->lang->words['views']}</option>
</select>&nbsp;
<select name='order' class='codebuttons'>
<option value='ASC'{$selected['ASC']}>{$this->lang->words['asc']}</option>
<option value='DESC'{$selected['DESC']}>{$this->lang->words['desc']}</option>
</select>&nbsp;
" . (($data['is_mr_mod'] == 1) ? ("
<input type='submit' value='{$this->lang->words['sortdelete']}' class='input_submit' />
") : ("
<input type='submit' value='{$this->lang->words['sort']}' class='input_submit' />
")) . "
</td></tr>") : ("")) . "
</table>
</div>
</div>
</form>
<br />")) . "";
return $IPBHTML;
}

/* -- view_all_by_member_row --*/
function view_all_by_member_row($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<tr class='{$data['rowclass']}'>
<td class='altrow' style=\"width:10%\"><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_buy_{$data['buy']}.png' alt='{$this->lang->words['img_buy']}' /></td>
" . (($data['checkbox'] != '') ? ("
<td style=\"width:53%\">
") : ("
<td style=\"width:63%\">
")) . "
" . (( $data['image'] != "") ? ("
{$data['image']}
") : ("")) . "
<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=reviews&amp;section=reviews&amp;do=view&amp;id={$data['id']}&amp;#review", "public",'' ), "{$data['frname']}", "showrevreview" ) . "'>{$data['title']}</a></strong><br />{$this->lang->words['date_added']}: {$data['date']}
" . (( $data['updated'] != "") ? ("
<br />{$this->lang->words['review_edited_new']}: {$data['updated']}") : ("")) . "
<br />{$this->lang->words['new_cat']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=products&amp;do=products&amp;id={$data['cid']}", "public",'' ), "{$data['fname']}", "showrevproduct" ) . "'>{$data['cname']}</a></td>
<td class='altrow' style=\"width:10%\" align='center'>{$data['favimg']}</td>
<td  style=\"width:7%\" align='center'><strong>{$data['views']}</strong></td>
<td class='altrow' style=\"width:10%\" align='center'><strong>{$data['rating']}</strong></td>
" . (($data['checkbox'] != '') ? ("
<td style=\"width:10%\" align='center'>{$data['checkbox']}</td>
") : ("")) . "
</tr>";
return $IPBHTML;
}

/* -- view_all_reviews --*/
function view_all_reviews($data=array(),$selected=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['linkbar']}
" . (( $data['rows'] != "") ? ("<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=reviews&amp;section=all&amp;do=viewall", "public",'' ), "all", "showrevall" ) . "' method='post'>
<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr class='header'><th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['verdict']}</th><th scope='col' style=\"width:53%\">{$this->lang->words['review_title']}</th><th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['author']}</th><th scope='col' style=\"width:7%;text-align:center\">{$this->lang->words['views']}</th><th scope='col' style=\"width:20%;text-align:center\" colspan=\"2\">{$this->lang->words['overall_rating']}</th></tr>
{$data['rows']}
<tr class='unread'><td class='altrow' colspan='6' align='right'>
<select name='key' class='codebuttons'>
<option value='author'{$selected['author']}>{$this->lang->words['author']}</option>
<option value='awards'{$selected['awards']}>{$this->lang->words['awards']}</option>
<option value='date'{$selected['date']}>{$this->lang->words['date']}</option>
<option value='updated'{$selected['updated']}>{$this->lang->words['updated']}</option>
<option value='since_last_visit'{$selected['since_last_visit']}>{$this->lang->words['since_last_visit']}</option>
<option value='overall'{$selected['overall']}>{$this->lang->words['overall_rating']}</option>
<option value='rrating'{$selected['rrating']}>{$this->lang->words['reader_rating']}</option>
<option value='name'{$selected['name']}>{$this->lang->words['review_title']}</option>
<option value='status'{$selected['status']}>{$this->lang->words['status']}</option>
<option value='verdict'{$selected['verdict']}>{$this->lang->words['verdict']}</option>
<option value='views'{$selected['views']}>{$this->lang->words['views']}</option>
</select>&nbsp;
<select name='order' class='codebuttons'>
<option value='ASC'{$selected['ASC']}>{$this->lang->words['asc']}</option>
<option value='DESC'{$selected['DESC']}>{$this->lang->words['desc']}</option>
</select>&nbsp;
" . (($data['is_mr_mod'] == 1) ? ("
<input type='submit' value='{$this->lang->words['sortdelete']}' class='input_submit' />
") : ("
<input type='submit' value='{$this->lang->words['sort']}' class='input_submit' />
")) . "
</td></tr>
</table>
</div>
</div>
</form>
<br />
" . (($data['links'] != "") ? ("
<div class='topic_controls'>
{$data['links']}
</div>
") : ("")) . "") : ("<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=reviews&amp;section=all&amp;do=viewall", "public",'' ), "all", "showrevall" ) . "' method='post'>
<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row1' align='center'>{$this->lang->words['no_reviews_sort']}</td></tr>
" . (($data['show_sort'] == '1') ? ("<tr class=\"unread\"><td class='altrow' align='right'>
<select name='key' class='codebuttons'>
<option value='author'{$selected['author']}>{$this->lang->words['author']}</option>
<option value='awards'{$selected['awards']}>{$this->lang->words['awards']}</option>
<option value='date'{$selected['date']}>{$this->lang->words['date']}</option>
<option value='updated'{$selected['updated']}>{$this->lang->words['updated']}</option>
<option value='since_last_visit'{$selected['since_last_visit']}>{$this->lang->words['since_last_visit']}</option>
<option value='overall'{$selected['overall']}>{$this->lang->words['overall_rating']}</option>
<option value='rrating'{$selected['rrating']}>{$this->lang->words['reader_rating']}</option>
<option value='name'{$selected['name']}>{$this->lang->words['review_title']}</option>
<option value='status'{$selected['status']}>{$this->lang->words['status']}</option>
<option value='verdict'{$selected['verdict']}>{$this->lang->words['verdict']}</option>
<option value='views'{$selected['views']}>{$this->lang->words['views']}</option>
</select>&nbsp;
<select name='order' class='codebuttons'>
<option value='ASC'{$selected['ASC']}>{$this->lang->words['asc']}</option>
<option value='DESC'{$selected['DESC']}>{$this->lang->words['desc']}</option>
</select>&nbsp;
" . (($data['is_mr_mod'] == 1) ? ("
<input type='submit' value='{$this->lang->words['sortdelete']}' class='input_submit' />
") : ("
<input type='submit' value='{$this->lang->words['sort']}' class='input_submit' />
")) . "
</td></tr>") : ("")) . "
</table>
</div>
</div>
</form>
<br />")) . "";
return $IPBHTML;
}

/* -- view_all_reviews_row --*/
function view_all_reviews_row($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<tr class='{$data['rowclass']}'>
<td class='altrow' style=\"width:10%\"><img src='{$this->settings['board_url']}/public/style_images/<#IMG_DIR#>/reviews/rev_buy_{$data['buy']}.png' alt='{$this->lang->words['img_buy']}' /></td>
" . (($data['checkbox'] != '') ? ("
<td style=\"width:53%\">
") : ("
<td style=\"width:63%\">
")) . "
" . (( $data['image'] != "") ? ("
{$data['image']}
") : ("")) . "
<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=reviews&amp;section=reviews&amp;do=view&amp;id={$data['id']}&amp;#review", "public",'' ), "{$data['frname']}", "showrevreview" ) . "'>{$data['title']}</a></strong><br />{$this->lang->words['date_added']}: {$data['date']}
" . (( $data['updated'] != "") ? ("
<br />{$this->lang->words['review_edited_new']}: {$data['updated']}") : ("")) . "
<br />{$this->lang->words['new_cat']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=products&amp;do=products&amp;id={$data['cid']}", "public",'' ), "" . IPSText::makeSeoTitle($data['cname']) . "", "showrevproduct" ) . "'>{$data['cname']}</a></td>
<td class='altrow' style=\"width:10%\" align='center'>
" . (( $data['members_display_name'] == "") ? ("
{$data['mem_name']}
") : ("
<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=authors&amp;section=profile&amp;do=profile&amp;id={$data['mid']}", "public",'' ), "{$data['members_seo_name']}", "showrevuser" ) . "'>{$data['author']}</a>
")) . "
</td>
<td style=\"width:7%\" align='center'><strong>{$data['views']}</strong></td>
<td class='altrow' style=\"width:10%\" align='center'><strong>{$data['rating']}</strong></td>
" . (($data['checkbox'] != '') ? ("
<td style=\"width:10%\" align='center'>{$data['checkbox']}</td>
") : ("")) . "
</tr>";
return $IPBHTML;
}

/* -- view_the_review --*/
function view_the_review($data=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_reviews_view', $this->_funcHooks['view_the_review'] ) )
{
$count_76b8e39f1dfa6371605bec9a6e42fff5 = is_array($this->functionData['view_the_review']) ? count($this->functionData['view_the_review']) : 0;
$this->functionData['view_the_review'][$count_76b8e39f1dfa6371605bec9a6e42fff5]['data'] = $data;
}

$pluginEditorHook = IPSLib::loadLibrary( IPS_ROOT_PATH . 'sources/classes/editor/composite.php', 'classes_editor_composite' );
	$editor = new $pluginEditorHook();
$IPBHTML .= "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'include_lightbox' ) ? $this->registry->getClass('output')->getTemplate('global')->include_lightbox() : '' ) . "
<div class='ipsLayout_content clearfix' itemscope itemtype=\"http://data-vocabulary.org/Review\">
  <div class='clearfix'>
    " . ((is_array($data['parent']) && count($data['parent']) && $data['parent']['cname']) ? ("<h1 class='pcat'>
        " . (($data['root']=='1') ? ("
          {$data['parent']['cname']} Destination Wedding Resort Reviews
        ") : ("
          Destination Wedding {$data['parent']['cname']}
        ")) . "
      </h1>") : ("")) . "
    <h2 class=\"ipsType_pagetitle left\" itemprop=\"itemreviewed\">{$data['title']}</h2>
    " . ((in_array( $this->memberData['member_group_id'], array( 4, 6 ) )) ? ("
      <!-- moderation button -->
      <div id=\"mod-options\" class='right'>{$data['extra']}</div>
    ") : ("")) . "
  </div>
  <br class='clear' />
  <div class='review_summary ipsPad_half left'>
    <p>This is a review of:</p>
    <h2><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=products&amp;do=products&amp;id={$data['cid']}", "public",'' ), "" . IPSText::makeSeoTitle($data['cname']) . "", "showrevproduct" ) . "'><span itemprop=\"itemreviewed\">{$data['cname']}</span></a></h2>
    " . (($data['cimg']) ? ("
      <br />
      <a class=\"product-image\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=products&amp;do=products&amp;id={$data['cid']}", "public",'' ), "" . IPSText::makeSeoTitle($data['cname']) . "", "showrevproduct" ) . "\">
        <img src=\"{$data['cimg']}\" width=\"160\" alt=\"{$data['cname']}\" class='ipsPad_double'/>
      </a>
    ") : ("")) . "
    <!-- detailed ratings -->
    " . (($this->settings['mr_enable_detailed'] && $data['regularrows']) ? ("
      <div id=\"revavgrating\">
        <h3>{$this->lang->words['average_ratings']}:</h3>
        <ul>
          {$data['regularrows']}
        </ul>
      </div>
    ") : ("")) . "
  </div>
  <div class='ipsPad_half left review_content' style='width: 70%;'>
    " . (($data['mid'] && $data['pp_main_photo']) ? ("
      <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$data['mid']}", "public",'' ), "{$data['members_seo_name']}", "showuser" ) . "' class='ipsUserPhotoLink'>
        <img src='{$data['pp_main_photo']}' class='ipsUserPhoto ipsUserPhoto_medium left' />
      </a>
    ") : ("")) . "
    <div class='ipsBox_withphoto'>
      <img src='{$this->settings['img_url']}/reviews/rev_rating_" . str_replace('.', '_', str_replace('.0', '', $data['overall'])) . ".png' alt='{$data['overall']}'/><span itemprop=\"rating\" style='display:none;'>{$data['overall']}</span>
      <p>
        {$this->lang->words['by']} <span itemprop=\"reviewer\">" . IPSMember::makeProfileLink($data['author'], $data['mid'], $data['members_seo_name']) . "</span>
      </p>
      <p>
        {$this->lang->words['date_added']} <span itemprop=\"dtreviewed\" datetime=\"{$data['date']}\">{$data['date']}</span> &sdot; {$data['views']} {$this->lang->words['totalviews']} &sdot; {$data['rcomments']} Comments
      </p>
    </div>
    <br />
    <div id=\"rev-procon\">
      <p><span class=\"rev-pro\">{$this->lang->words['pros']}:</span> {$data['pros']}</p>
      <p><span class=\"rev-con\">{$this->lang->words['cons']}:</span> {$data['cons']}</p>
    </div>
    <div itemprop=\"summary\">
      {$data['content']}
    </div>
    " . (($this->memberData['g_is_supmod'] || $data['can_report']) ? ("
      <br />
      <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=reports&amp;rcom=review&amp;id={$data['id']}", "public",'' ), "", "" ) . "' class='right'>Report</a>
    ") : ("")) . "
    <br class='clear' />
    " . (($this->settings['mr_enable_history']) ? ("
      <a name=\"logs\"></a>
      <h3 class='maintitle clear'>{$this->lang->words['edit_log_table']}</h3>
      <div class='ipsBox'>
        <div class='ipsBox_container'>
          <table class='ipb_table'>
            <tr class='header'>
              <th scope='col' style=\"width:25%;text-align:center\"><strong>{$this->lang->words['edit_reason_date']}</strong></th>
              <th scope='col' style=\"width:15%;text-align:center\"><strong>{$this->lang->words['edit_reason_member']}</strong></th>
              <th scope='col' style=\"width:60%\"><strong>{$this->lang->words['edit_reason']}</strong></th>
            </tr>
            {$data['edit_rows']}
          </table>
        </div>
      </div>
      <br/>
    ") : ("")) . "
  </div>
  <br class='clear' />
  " . (($data['comment_on']) ? ("<a name=\"comments\"></a>
    <h3 class='maintitle'>{$this->lang->words['review_comments']}</h3>
    <div class='ipsBox'>
      <div class='ipsBox_container'>
        <table class='ipb_table'>
          " . (($data['rows']) ? ("
            <tr class='header'>
              <th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['comments_name']}</th>
              <th scope='col' style=\"width:90%\">{$this->lang->words['comments_comment']}</th>
            </tr>
            {$data['rows']}
          ") : ("")) . "
        </table>
      </div>
    </div>
    <br />
    " . (($data['links']) ? ("
      <div class='topic_controls'>{$data['links']}</div>
    ") : ("")) . "" . (($data['comment_yes']) ? ("<br />
      <div class='ipsBox' id='fast_reply_wrapper'>
        <div class='ipsBox_container ipsPad'>
          <h1 class='ipsType_subtitle'>{$this->lang->words['editor_title']}</h1>
          <br/>
          " . (($this->memberData['member_group_id'] != '2') ? ("		
            <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$this->memberData['member_id']}", "public",'' ), "{$this->memberData['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['your_profile']}' class='ipsUserPhotoLink left'><img src='{$this->memberData['pp_small_photo']}' alt=\"" . sprintf($this->lang->words['users_photo'],$this->memberData['members_display_name']) . "\" class='ipsUserPhoto ipsUserPhoto_medium' /></a>
          ") : ("		
            <div class='left'>" . IPSMember::buildNoPhoto(0, 'small' ) . "</div>		  
          ")) . "
          <div class='ipsBox_withphoto clearfix'>
            <form id='postingform' onsubmit='return ValidateForm()' action=\"{$this->settings['base_url']}app=reviews&amp;module=extra&amp;section=comment&amp;do=do_add_comment\" method=\"post\">
              <input type=\"hidden\" name=\"id\" value=\"{$data['id']}\"/>
              <input type=\"hidden\" name=\"fast_reply_used\" value=\"1\"/>
              " . $editor->show('Post', array('type' => 'mini', 'minimize' => TRUE ), "")  . "
              <br/>
              <fieldset class='right' id='fast_reply_controls'>
                <input type='submit' name=\"submit\" class='input_submit' value='{$this->lang->words['add_comment']}' tabindex='1' accesskey='s' id='submit_post' />
              </fieldset>
            </form>
          </div>
          <div id='ips_HasReplies'></div>
        </div>
      </div>") : ("")) . "") : ("")) . "
</div>
<script>
// nav_menu_5 = 1
// nav_menu_6 = 69
if ({$data['rootid']}=='1'){var d = document.getElementById(\"nav_menu_5\");} 
else if ({$data['rootid']}=='69'){var d = document.getElementById(\"nav_menu_6\");} 
else {//do nothing
}
d.className = d.className + \" active\";
</script>";
return $IPBHTML;
}

/* -- view_the_review_edit_row --*/
function view_the_review_edit_row($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<tr class='{$data['rowclass']}'>
<td align='center'>{$data['date']}</td>
<td class='altrow' align='center'>
" . (( $data['members_display_name'] == "") ? ("
{$data['mem_name']}
") : ("
{$data['author']}
")) . "
</td>
<td>{$data['reason']}</td>
</tr>";
return $IPBHTML;
}

/* -- view_the_review_extra_ratings_row --*/
function view_the_review_extra_ratings_row($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<li><label>{$data['name']}.....</label>{$data['average']}</li>";
return $IPBHTML;
}

/* -- view_the_review_ratings --*/
function view_the_review_ratings($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<!-- add super category test here -->
" . (($this->settings['mr_enable_breakdown'] == "1" && $data['specialrows'] != "") ? ("
  <div id=\"revgenrerating\">
  <h3>{$this->lang->words['genre_ratings']}</h3>
  <ul>
    {$data['specialrows']}
  </ul>
  </div>
") : ("")) . "" . (( $data['extra_rows'] != "") ? ("
  <div id=\"revextrarating\">
  <h3>{$data['extra_rate']}</h3> 
  <ul>{$data['extra_rows']}</ul>
  </div>
") : ("")) . "";
return $IPBHTML;
}

/* -- view_the_review_ratings_row --*/
function view_the_review_ratings_row($name="",$value="") {
$IPBHTML = "";
$IPBHTML .= "<li class=\"revdetrate\">{$name}: {$value}</li>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>