<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 5               */
/* CACHE FILE: Generated: Tue, 10 May 2016 16:28:52 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_reviews_hooks_5 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();


}

/* -- reviewsInCard --*/
function reviewsInCard($reviews) {
$IPBHTML = "";
$IPBHTML .= "<dt>{$this->lang->words['reviews_name_4']}</dt>
			<dd>" . $this->registry->getClass('class_localization')->formatNumber( $reviews ) . "</dd>";
return $IPBHTML;
}

/* -- reviewsInPane --*/
function reviewsInPane($reviews) {
$IPBHTML = "";
$IPBHTML .= "<li class='post_count desc lighter'>" . $this->registry->getClass('class_localization')->formatNumber( intval( $reviews ) ) . " {$this->lang->words['reviews_name_2']}
</li>";
return $IPBHTML;
}

/* -- reviewsInProfile --*/
function reviewsInProfile($reviews) {
$IPBHTML = "";
$IPBHTML .= "<li><span class='row_title'>{$this->lang->words['reviews_name_3']}</span>
<span class='row_data'>" . $this->registry->getClass('class_localization')->formatNumber( $reviews ) . "</span></li>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>