<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 5               */
/* CACHE FILE: Generated: Tue, 10 May 2016 16:28:51 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_global_5 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['hookRecentGalleryImages'] = array('gallery_images_hook');
$this->_funcHooks['likeSummaryContents'] = array('likeOnlyMembers');
$this->_funcHooks['listingLightbox'] = array('doAdvanced','doAdvancedToo','loadedYet','notYetLoaded','loadNormal');
$this->_funcHooks['shareLinks'] = array('hasOverrideApp','hasCustom','isEnabled','cacheLoop','gotLinks');
$this->_funcHooks['tagCloud'] = array('eachTag','hasTags');


}

/* -- bbCodeAlbum --*/
function bbCodeAlbum($album) {
$IPBHTML = "";
$IPBHTML .= "<div class='_sharedMediaBbcode'>
	<div class='bbcode_mediaWrap clearfix'>
		<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$album['album_id']}", "public",'' ), "{$album['album_name_seo']}", "viewalbum" ) . "\">{$album['thumb']}</a>
		<div class='details'>
			<h5><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$album['album_id']}", "public",'' ), "{$album['album_name_seo']}", "viewalbum" ) . "\">{$this->lang->words['album_ucfirst']}: {$album['album_name']}</a></h5>
			<div>{$album['album_count_imgs']} {$this->lang->words['images_lower']}</div>
			<div>{$album['album_count_comments']} {$this->lang->words['comments_lower']}</div>
		</div>
	</div>
</div>
<br />";
return $IPBHTML;
}

/* -- bbCodeImage --*/
function bbCodeImage($image) {
$IPBHTML = "";
$IPBHTML .= "<!-- bbcodeImage-js (do not remove or edit this tag) -->
<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;image={$image['image_id']}", "public",'' ), "{$image['image_caption_seo']}", "viewimage" ) . "\" title=\"{$image['image_caption']}\">{$image['thumb']}</a>
<br />";
return $IPBHTML;
}

/* -- bbCodeImageNoPermission --*/
function bbCodeImageNoPermission() {
$IPBHTML = "";
$IPBHTML .= "<div id='lightbox_wrap'>
	<a href='#' id='close_lightbox'>&times;</a>
	<div id='imageErrorWrap'>
		<h2 class='ipsType_pagetitle'>{$this->lang->words['no_permission_bbcodeajaximage']}</h2>
	</div>
</div>";
return $IPBHTML;
}

/* -- galleryCss --*/
function galleryCss() {
$IPBHTML = "";
$IPBHTML .= "<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipgallery.css\" />";
return $IPBHTML;
}

/* -- general_warning --*/
function general_warning($data='') {
$IPBHTML = "";
$IPBHTML .= "<!-- Show inline warning -->
<div class='message unspecific'>
	<strong>{$data['title']}</strong><br />
	{$data['body']}
</div>";
return $IPBHTML;
}

/* -- globals --*/
function globals($data='') {
$IPBHTML = "";

if ( ! isset( $this->registry->templateStriping['imagelisting'] ) ) {
$this->registry->templateStriping['imagelisting'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("gallery", "0" ) . "
" . $this->registry->getClass('output')->addJSModule("rating", "0" ) . "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'include_lightbox' ) ? $this->registry->getClass('output')->getTemplate('global')->include_lightbox() : '' ) . "
" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'include_highlighter' ) ? $this->registry->getClass('output')->getTemplate('global')->include_highlighter(1) : '' ) . "
<script type='text/javascript'>
ipb.vars['members_gallery']	= '{$this->settings['gallery_members_album']}';
ipb.lang['hidden']				= \"{$this->lang->words['image_hidden']}\";
</script>
<!--[if lte IE 8]>
	<style type='text/css'>
		.gallery_category > div {
			padding: 0px;
			border: 1px solid #000;
		}
		.gallery_category h2 {
			background: #000;
			top: 0px;
			right: 0px;
			left: 0px;
		}

		.gallery_category .gallery_item_info {
			margin-left: 5px;
			margin-right: 5px;
			margin-bottom: 5px;
		}
	</style>
<![endif]-->";
return $IPBHTML;
}

/* -- hookRecentGalleryImages --*/
function hookRecentGalleryImages($rows) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_global', $this->_funcHooks['hookRecentGalleryImages'] ) )
{
$count_506be28f0b5a51925cc0573b6bb28eda = is_array($this->functionData['hookRecentGalleryImages']) ? count($this->functionData['hookRecentGalleryImages']) : 0;
$this->functionData['hookRecentGalleryImages'][$count_506be28f0b5a51925cc0573b6bb28eda]['rows'] = $rows;
}
$IPBHTML .= "<style type=\"text/css\">
#appGallLatestHook
{
	overflow:auto;
	overflow-y: hidden;
	height: 117px;
}
	#appGallLatestHook a {
		display: block;
	}
	
	#appGallLatestHook ul li img
	{
		max-width: 100px;
		max-height: 100px;
	}
		
		#appGallLatestHook ul li:last-child { margin-right: 10px; }
</style>
<div id='category_gallrecent' class='category_block block_wrap'>
	<h3 class='maintitle'>
		<a class='toggle right' href='#' title=\"{$this->lang->words['toggle_ucfirst']}\">{$this->lang->words['toggle_ucfirst']}</a> <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery", "public",'' ), "false", "app=gallery" ) . "\">{$this->lang->words['recent_gallery_images']}</a>
	</h3>
	<div id='appGallLatestHook' class='ipsBox table_wrap'>
		<ul class='ipsList_inline ipsList_nowrap'>
			".$this->__f__bd2ea2183543c4ef83eaae7a7b24f77c($rows)."		</ul>
	</div>
</div>
<br />";
return $IPBHTML;
}


function __f__bd2ea2183543c4ef83eaae7a7b24f77c($rows)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $rows as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<li>{$r['thumb']}</li>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- likeSummary --*/
function likeSummary($data, $relId, $opts) {
$IPBHTML = "";
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("like", "0" ) . "
<div class='__like right' data-app=\"{$data['app']}\" data-area=\"{$data['area']}\" data-relid=\"{$relId}\" data-isfave=\"{$data['iLike']}\">
	" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_global'), 'likeSummaryContents' ) ? $this->registry->getClass('output')->getTemplate('gallery_global')->likeSummaryContents($data, $relId, $opts) : '' ) . "
</div>
<script type=\"text/javascript\">
	var FAVE_TEMPLATE = new Template( \"<h3>" . sprintf( $this->lang->words['unset_fave_title'], $this->lang->words['like_ucfirst_un' . $data['vernacular'] ]) . "</h3><div class='ipsPad'><span class='desc'>" . sprintf( $this->lang->words['unset_fave_words'], $this->lang->words['like_un' . $data['vernacular'] ]) . "</span><br /><p class='ipsForm_center'><input type='button' value='" . sprintf( $this->lang->words['unset_button'], $this->lang->words['like_ucfirst_un' . $data['vernacular'] ]) . "' class='input_submit _funset' /></p></div>\");
</script>";
return $IPBHTML;
}

/* -- likeSummaryContents --*/
function likeSummaryContents($data, $relId, $opts=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_global', $this->_funcHooks['likeSummaryContents'] ) )
{
$count_aa9a6d1fe154774f5eb6603f493ef82d = is_array($this->functionData['likeSummaryContents']) ? count($this->functionData['likeSummaryContents']) : 0;
$this->functionData['likeSummaryContents'][$count_aa9a6d1fe154774f5eb6603f493ef82d]['data'] = $data;
$this->functionData['likeSummaryContents'][$count_aa9a6d1fe154774f5eb6603f493ef82d]['relId'] = $relId;
$this->functionData['likeSummaryContents'][$count_aa9a6d1fe154774f5eb6603f493ef82d]['opts'] = $opts;
}
$IPBHTML .= "<span class='ipsButton_extra right " . (($data['totalCount']) ? ("_fmore clickable") : ("")) . "' title='" . sprintf( $this->lang->words['like_totalcount_' . $data['vernacular'] ], $data['totalCount'] ) . "' data-tooltip=\"" . sprintf( $this->lang->words['like_totalcount_' . $data['vernacular'] ], $data['totalCount'] ) . "\"><img src='{$this->settings['img_url']}/icon_users.png' /> <strong>{$data['totalCount']}</strong></span>
" . (($this->memberData['member_id']) ? ("<a href='#' title=\"" . (($data['iLike']) ? ("" . sprintf( $this->lang->words['fave_tt_on'], $this->lang->words['like_ucfirst_un' . $data['vernacular'] ]) . "") : ("" . sprintf( $this->lang->words['fave_tt_off'], $this->lang->words['like_ucfirst_' . $data['vernacular'] ]) . "")) . "\" class='ftoggle ipsButton_secondary'>" . (($data['iLike']) ? ("" . sprintf( $this->lang->words['unset_fave_button'], $this->lang->words['like_ucfirst_un' . $data['vernacular'] ]) . "") : ("" . sprintf( $this->lang->words['set_fave_button'], $this->lang->words['like_ucfirst_' . $data['vernacular'] ]) . "")) . "</a>") : ("")) . "";
return $IPBHTML;
}

/* -- listingLightbox --*/
function listingLightbox($loadInline=false, $doAdvanced=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_global', $this->_funcHooks['listingLightbox'] ) )
{
$count_abe6824d5683f3751c53249dd36f7140 = is_array($this->functionData['listingLightbox']) ? count($this->functionData['listingLightbox']) : 0;
$this->functionData['listingLightbox'][$count_abe6824d5683f3751c53249dd36f7140]['loadInline'] = $loadInline;
$this->functionData['listingLightbox'][$count_abe6824d5683f3751c53249dd36f7140]['doAdvanced'] = $doAdvanced;
}
$IPBHTML .= "" . ((!$loadInline) ? ("" . $this->registry->getClass('output')->addJSModule("gallery_lightbox", "0" ) . "" . $this->registry->getClass('output')->addJSModule("sharelinks", "0" ) . "" . $this->registry->getClass('output')->addToDocumentHead( 'importcss', "{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipgallery_lightbox.css" ) . "
	<script type='text/javascript'>
		ipb.gallery_lightbox.doAutoAdvanced	= " . (($doAdvanced) ? ("true") : ("false")) . ";
	</script>
	<div id=\"ips_lightbox\" style='display:none' setup=\"false\" available=\"true\">
		<div id='ips_lightbox_content' style='display:none;'></div>
		<div id='ips_lightbox_loading'>
			<img src='{$this->settings['img_url']}/wait.gif' alt='' />
		</div>
	</div>") : ("" . ((!$this->_loadedLightbox) ? ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_global'), 'galleryCss' ) ? $this->registry->getClass('output')->getTemplate('gallery_global')->galleryCss() : '' ) . "
		<script type='text/javascript' src=\"{$this->settings['public_dir']}js/ips.gallery.js\"></script>
		<script type='text/javascript' src=\"{$this->settings['public_dir']}js/ips.gallery_lightbox.js\"></script>
		<script type='text/javascript' src=\"{$this->settings['public_dir']}js/ips.sharelinks.js\"></script>
		<link rel=\"stylesheet\" type='text/css' href='{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipgallery_lightbox.css' />
		<script type='text/javascript'>
			ipb.gallery_lightbox.doAutoAdvanced	= " . (($doAdvanced) ? ("true") : ("false")) . ";
		</script>
		<div id=\"ips_lightbox\" style='display:none' setup=\"false\" available=\"true\">
			<div id='ips_lightbox_content' style='display:none;'></div>
			<div id='ips_lightbox_loading'>
				<img src='{$this->settings['img_url']}/wait.gif' alt='' />
			</div>
		</div>
		" . (($this->_loadedLightbox=1) ? ("") : ("")) . "") : ("")) . "")) . "";
return $IPBHTML;
}

/* -- pinterestButton --*/
function pinterestButton($url, $title) {
$IPBHTML = "";
$IPBHTML .= "" . $this->registry->getClass('output')->addToDocumentHead( 'javascript', "//assets.pinterest.com/js/pinit.js" ) . "
<li class='pinterestShareLink'><a href=\"http://pinterest.com/pin/create/button/?url=" . urlencode(IPSText::base64_decode_urlSafe($url)) . "&amp;media=" . urlencode($this->settings['gallery_image_url']) . "\" class=\"pin-it-button\" count-layout=\"horizontal\"><img src=\"//assets.pinterest.com/images/PinExt.png\" title=\"Pin It\" /></a></li>";
return $IPBHTML;
}

/* -- shareLinks --*/
function shareLinks($links, $title='', $url='', $cssClass='topic_share left') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_global', $this->_funcHooks['shareLinks'] ) )
{
$count_d5dc4f57f0d47cf711d95c3d52b2f1e2 = is_array($this->functionData['shareLinks']) ? count($this->functionData['shareLinks']) : 0;
$this->functionData['shareLinks'][$count_d5dc4f57f0d47cf711d95c3d52b2f1e2]['links'] = $links;
$this->functionData['shareLinks'][$count_d5dc4f57f0d47cf711d95c3d52b2f1e2]['title'] = $title;
$this->functionData['shareLinks'][$count_d5dc4f57f0d47cf711d95c3d52b2f1e2]['url'] = $url;
$this->functionData['shareLinks'][$count_d5dc4f57f0d47cf711d95c3d52b2f1e2]['cssClass'] = $cssClass;
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("sharelinks", "0" ) . "
" . ((is_array( $links )) ? ("
	<ul class='{$cssClass} shareButtons ipsList_inline'>
	".$this->__f__9c2c5700342b9e1c6ee5fe4ee4a05928($links,$title,$url,$cssClass)."		" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_global'), 'pinterestButton' ) ? $this->registry->getClass('output')->getTemplate('gallery_global')->pinterestButton($url, $title) : '' ) . "
	</ul>
	<script type=\"text/javascript\">
		ipb.sharelinks.url   = \"" . IPSText::base64_decode_urlSafe($url) . "\";
		ipb.sharelinks.title = \"" . IPSText::base64_decode_urlSafe( IPSText::htmlspecialchars( $title ) ) . "\";
		ipb.sharelinks.bname = \"" . trim(addslashes($this->settings['board_name'])) . "\";
	</script>
") : ("")) . "";
return $IPBHTML;
}


function __f__9c2c5700342b9e1c6ee5fe4ee4a05928($links, $title='', $url='', $cssClass='topic_share left')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $links as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		" . (($data['share_enabled']) ? ("" . (($data['customOutput'] and is_array( $data['customOutput'] )) ? ("
				" . $this->registry->output->getTemplate($data['customOutput'][0])->$data['customOutput'][1]( $data['_rawUrl'], $title, $data['customOutput'][2] ) . "
			") : ("<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "sharelink={$data['share_key']};{$data['_url']};{$title}", "public",'' ), "", "" ) . "" . (($data['overrideApp']) ? ("&amp;overrideApp={$data['overrideApp']}") : ("")) . "\" rel=\"nofollow\" target=\"_blank\" title=\"" . ((isset( $this->lang->words['gbl_sharelink_with_' . $data['share_key'] ] )) ? ("{$this->lang->words['gbl_sharelink_with_' . $data['share_key'] ]}") : ("{$this->lang->words['gbl_sharelink_with']} {$data['share_title']}")) . "\" class='_slink' id='slink_{$data['share_key']}'><img src=\"{$this->settings['public_cdn_url']}style_extra/sharelinks/{$data['share_key']}.png\" /></a></li>")) . "") : ("")) . "
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- tagCloud --*/
function tagCloud($tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_global', $this->_funcHooks['tagCloud'] ) )
{
$count_fda6be6bc293f621034ed1fe2882edb3 = is_array($this->functionData['tagCloud']) ? count($this->functionData['tagCloud']) : 0;
$this->functionData['tagCloud'][$count_fda6be6bc293f621034ed1fe2882edb3]['tags'] = $tags;
}
$IPBHTML .= "" . ((count($tags['tags'])) ? ("
	<div class='ipsSideBlock clearfix'>
		<h3>{$this->lang->words['popular_tags']}</h3>
		<div class='_sbcollapsable'>
			<ul class='ipsList_inline'>
				".$this->__f__09074aa29c3316b7f6e8adc8520859a1($tags)."			</ul>
		</div>
	</div>
") : ("")) . "";
return $IPBHTML;
}


function __f__09074aa29c3316b7f6e8adc8520859a1($tags)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $tags['tags'] as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					<li><span class=\"{$data['className']}\">{$data['tagWithUrl']}</span></li>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>