<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 7               */
/* CACHE FILE: Generated: Fri, 23 Sep 2016 17:24:01 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_reviews_global_7 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['searchResultsWrapper'] = array('results');


}

/* -- searchResultComment --*/
function searchResultComment($comment) {
$IPBHTML = "";
$IPBHTML .= "<tr>
  <td>    
    <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=reviews&amp;section=reviews&amp;do=view&amp;id={$comment['id']}", "public",'' ), "" . IPSText::makeSeoTitle($comment['cname']) . "", "showrevreview" ) . "#comments'>{$comment['title']}</a>
    <div class='desc lighter'>{$comment['content']}</div>
  </td>
  <td style='width: 20%;' class='desc'>
    " . IPSMember::makeProfileLink($comment['members_display_name'], $comment['mid'], $comment['members_seo_name']) . "
    <br />
    " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($comment['time'],"LONG", 0)) . "
  </td>
</tr>";
return $IPBHTML;
}

/* -- searchResultProduct --*/
function searchResultProduct($product) {
$IPBHTML = "";
$IPBHTML .= "<tr>
  <td>
    <img src='{$product['cimg']}' class='ipsUserPhoto ipsUserPhoto_medium left' />
  </td>
  <td>
    <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=products&amp;do=products&amp;id={$product['cid']}", "public",'' ), "" . IPSText::makeSeoTitle($product['cname']) . "", "showrevproduct" ) . "'><strong>{$product['content_title']}</strong></a>
    <br />
    " . (($product['root'] == 1) ? ("
      <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=categories&amp;do=viewcat&amp;cid={$product['cparent']}", "public",'' ), "" . IPSText::makeSeoTitle($product['parent_name']) . "", "showrevcategorytwo" ) . "'>{$product['parent_name']} Destination Wedding Resort Reviews</a>
    ") : ("
      <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=categories&amp;do=viewcat&amp;cid={$product['cparent']}", "public",'' ), "" . IPSText::makeSeoTitle($product['parent_name']) . "", "showrevcategorytwo" ) . "'>Destination Wedding {$product['parent_name']} Reviews</a>
    ")) . "
    <div class='desc'>{$product['content']}</div>
  </td>
  <td style='width: 10%; text-align: right;'>
    <img src='{$this->settings['img_url']}/reviews/rev_rating_{$product['rating']}.png' title='{$product['rating']}'/>
    <br />
    <span class='desc lighter'>{$product['rcomments']} reviews</span>
  </td>
</tr>";
return $IPBHTML;
}

/* -- searchResultReview --*/
function searchResultReview($review) {
$IPBHTML = "";
$IPBHTML .= "<tr>
  <td>    
    <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=reviews&amp;section=reviews&amp;do=view&amp;id={$review['id']}", "public",'' ), "" . IPSText::makeSeoTitle($review['cname']) . "", "showrevreview" ) . "'>{$review['content_title']}</a>
    <br />
    <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=products&amp;do=products&amp;id={$review['cid']}", "public",'' ), "" . IPSText::makeSeoTitle($review['cname']) . "", "showrevproduct" ) . "'>{$review['cname']}</a>
    <div class='desc lighter'>{$review['content']}</div>
  </td>
  <td style='width: 20%;' class='desc'>
    " . IPSMember::makeProfileLink($review['members_display_name'], $review['mid'], $review['members_seo_name']) . "
    <br />
    " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($review['time'],"LONG", 0)) . "
  </td>
  <td style='width: 10%; text-align: right;'>
    <div>
      " . (($review['overall'] > 0) ? ("" . $this->registry->getClass('output')->getReplacement("mini_rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("mini_rate_off") . "")) . "" . (($review['overall'] > 1) ? ("" . $this->registry->getClass('output')->getReplacement("mini_rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("mini_rate_off") . "")) . "" . (($review['overall'] > 2) ? ("" . $this->registry->getClass('output')->getReplacement("mini_rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("mini_rate_off") . "")) . "" . (($review['overall'] > 3) ? ("" . $this->registry->getClass('output')->getReplacement("mini_rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("mini_rate_off") . "")) . "" . (($review['overall'] > 4) ? ("" . $this->registry->getClass('output')->getReplacement("mini_rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("mini_rate_off") . "")) . "
    </div>
    <div class='desc lighter'>{$review['rcomments']} comments</div>
  </td>
</tr>";
return $IPBHTML;
}

/* -- searchResultsWrapper --*/
function searchResultsWrapper($results=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_reviews_global', $this->_funcHooks['searchResultsWrapper'] ) )
{
$count_d2e14c1163f40e5c36e317afb4eee94f = is_array($this->functionData['searchResultsWrapper']) ? count($this->functionData['searchResultsWrapper']) : 0;
$this->functionData['searchResultsWrapper'][$count_d2e14c1163f40e5c36e317afb4eee94f]['results'] = $results;
}
$IPBHTML .= "<table class='ipb_table'>
  " . ((is_array($results) && count($results)) ? ("".$this->__f__f17433d2706c82308e33801621f6b9f9($results)."  ") : ("")) . "
</table>";
return $IPBHTML;
}


function __f__f17433d2706c82308e33801621f6b9f9($results=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $results as $result )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
      {$result['html']}
    
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>