<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 7               */
/* CACHE FILE: Generated: Fri, 23 Sep 2016 17:24:00 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_blog_global_7 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['blog_header'] = array('showDisabledBox','includeCustomThemes');
$this->_funcHooks['catsAsList'] = array('isLastCategory','categoriesLoop','hasCategories');
$this->_funcHooks['contextSearch'] = array('inBlog','inBlogEntry');
$this->_funcHooks['hookTagCloud'] = array('eachTag');
$this->_funcHooks['overwriteHeader'] = array('bloghasdesc','bloghasurl');
$this->_funcHooks['short_img_tag'] = array('isAnEmoticon');
$this->_funcHooks['short_media_tag'] = array('isyoutube');
$this->_funcHooks['theme_menu'] = array('gotThemes');


}

/* -- blog_header --*/
function blog_header($blog="", $cblock_control="", $theme_js='', $header_js='', $title='', $headerButtons=TRUE) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_global', $this->_funcHooks['blog_header'] ) )
{
$count_c575d0ffd1e1035f5837596992667608 = is_array($this->functionData['blog_header']) ? count($this->functionData['blog_header']) : 0;
$this->functionData['blog_header'][$count_c575d0ffd1e1035f5837596992667608]['blog'] = $blog;
$this->functionData['blog_header'][$count_c575d0ffd1e1035f5837596992667608]['cblock_control'] = $cblock_control;
$this->functionData['blog_header'][$count_c575d0ffd1e1035f5837596992667608]['theme_js'] = $theme_js;
$this->functionData['blog_header'][$count_c575d0ffd1e1035f5837596992667608]['header_js'] = $header_js;
$this->functionData['blog_header'][$count_c575d0ffd1e1035f5837596992667608]['title'] = $title;
$this->functionData['blog_header'][$count_c575d0ffd1e1035f5837596992667608]['headerButtons'] = $headerButtons;
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("blog", "0" ) . "
<script type='text/javascript'>
	ipb.vars['blog_id'] = parseInt( {$blog['blog_id']} );
	ipb.vars['blog_url'] = \"{$blog['blog_url']}\";
	ipb.lang['confirm_delete'] = \"{$this->lang->words['blog_sure_delcblock']}\";
	ipb.lang['confirm_reset'] = \"{$this->lang->words['blog_theme_reset']}\";
	ipb.lang['blog_sure_delcblock']	= \"{$this->lang->words['blog_sure_delcblock']}\";
	ipb.lang['copy_entry_link'] = \"{$this->lang->words['permalink_prompt']}\";
</script>
" . (($blog['blog_disabled'] AND $this->memberData['g_is_supmod']) ? ("
	<div class='message error'>
		<h4>{$this->lang->words['blog_global_disabled_title']}</h4>
		" . sprintf( $this->lang->words['blog_global_disabled_desc'], $this->settings['base_url'] . 'app=blog&amp;module=post&amp;section=mod&amp;do=toggledisable&amp;disable=0&amp;blog_id=' . $blog['blog_id'] . '&amp;auth_key='.$this->member->form_hash ) . "
	</div>
	<br />
") : ("")) . "
" . (($this->settings['blog_themes_custom']) ? ("
	<script type='text/javascript'>
		var clientImagePath = \"{$this->settings['_original_base_url']}/blog/colorpicker/images/\";
	</script>
	<script type=\"text/javascript\" src=\"{$this->settings['_original_base_url']}/blog/colorpicker/colormethods.js\" ></script>
	<script type=\"text/javascript\" src=\"{$this->settings['_original_base_url']}/blog/colorpicker/colorvaluepicker.js\" ></script>
	<script type=\"text/javascript\" src=\"{$this->settings['_original_base_url']}/blog/colorpicker/slider.js\" ></script>
	<script type=\"text/javascript\" src=\"{$this->settings['_original_base_url']}/blog/colorpicker/colorpicker.js\" ></script>
	
	<style type='text/css'>
		.colorpicker {
		display: block;
		}
		.margin{
		margin-top: 1px;
		margin-left: 3px;
		}
	</style>
") : ("")) . "
{$cblock_control}
{$header_js}
{$theme_js}";
return $IPBHTML;
}

/* -- catsAsList --*/
function catsAsList($blogId, $categories) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_global', $this->_funcHooks['catsAsList'] ) )
{
$count_db4851676d216b8eb321e66bb08e0e40 = is_array($this->functionData['catsAsList']) ? count($this->functionData['catsAsList']) : 0;
$this->functionData['catsAsList'][$count_db4851676d216b8eb321e66bb08e0e40]['blogId'] = $blogId;
$this->functionData['catsAsList'][$count_db4851676d216b8eb321e66bb08e0e40]['categories'] = $categories;
}

$categories = $this->registry->blogFunctions->formatCategoriesUrl( $blogId, $categories );
$IPBHTML .= "" . ((is_array( $categories ) && count( $categories ) && !(count($categories) == 1 && array_key_exists(0, $categories))) ? ("
	{$this->lang->words['blog_in']}
	".$this->__f__83d2ac96a2d5306eb4c7fdb1862e4457($blogId,$categories)."") : ("")) . "";
return $IPBHTML;
}


function __f__83d2ac96a2d5306eb4c7fdb1862e4457($blogId, $categories)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $categories as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<a href='{$data['_url']}' title=\"" . sprintf( $this->lang->words['view_all_entry_in_cat'], $data['category_title'] ) . "\" data-tooltip=\"" . sprintf( $this->lang->words['view_all_entry_in_cat'], $data['category_title'] ) . "\">{$data['category_title']}</a>" . ((!$data['_last']) ? (", ") : ("")) . "
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- cblock_menu --*/
function cblock_menu($cblocks) {
$IPBHTML = "";
$IPBHTML .= "<ul class=\"ipbmenu_content\" id='content_blocks_menucontent' style='display: none'>
	" . (($this->settings['blog_allow_cblocks']) ? ("
		<li id='new_cblock'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=post&amp;section=post&amp;do=addcblock&amp;blogid={$this->registry->blogFunctions->blog['blog_id']}&amp;inline=1", "public",'' ), "", "" ) . "' title=\"{$this->lang->words['add_a_cblock']}\"><strong><img src='{$this->settings['img_url']}/add.png' alt='' /> {$this->lang->words['blog_cblock']}</strong></a></li>
	") : ("")) . "" . ((is_array( $cblocks ) && count( $cblocks )) ? ("".$this->__f__931781901113d9c0d95553c48391b863($cblocks)."	") : ("")) . "
</ul>
<script type='text/javascript'>
	ipb.templates['cblock_item'] = new Template(\"<li id='enable_cblock_#{id}' class='customBlockOption enable'><a href='#'>#{name}</a></li>\");
</script>";
return $IPBHTML;
}


function __f__931781901113d9c0d95553c48391b863($cblocks)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $cblocks as $cid => $block )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<li id='enable_cblock_{$block[0]}' class='customBlockOption " . (($block[3]) ? ("add") : ("enable")) . "'><a href='#'>{$block[1]}</a></li>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- contextSearch --*/
function contextSearch() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_global', $this->_funcHooks['contextSearch'] ) )
{
$count_ea8f7121db180a2dc4b8a882929436b8 = is_array($this->functionData['contextSearch']) ? count($this->functionData['contextSearch']) : 0;
}
$IPBHTML .= "" . ((ipsRegistry::$appSearch = TRUE) ? ("") : ("")) . "
" . (($this->request['app'] == 'blog' AND $this->request['module'] == 'display' AND ($this->request['section'] == 'blog' OR $this->request['section'] == 'entry') AND $this->request['blogid']) ? ("" . ((ipsRegistry::$appSearch = FALSE) ? ("") : ("")) . "
	<li class='special'><label for='s_blog' title='{$this->lang->words['context_search_blog']}'><input type='radio' name='search_app' value=\"blog:blog:{$this->request['blogid']}\" class='input_radio' id='s_blog' checked=\"checked\" /> <strong>{$this->lang->words['context_search_blog']}</strong></label></li>") : ("")) . "
" . (($this->request['app'] == 'blog' AND $this->request['module'] == 'display' AND $this->request['section'] == 'entry' AND $this->request['blogid']) ? ("" . ((ipsRegistry::$appSearch = FALSE) ? ("") : ("")) . "
	<li class='special'><label for='s_blog_comments' title='{$this->lang->words['context_search_blog_comments']}'><input type='radio' name='search_app' value=\"blog:entry:{$this->request['eid']}\" class='input_radio' id='s_blog_comments' checked=\"checked\" /> <strong>{$this->lang->words['context_search_blog_comments']}</strong></label></li>") : ("")) . "";
return $IPBHTML;
}

/* -- hookTagCloud --*/
function hookTagCloud($tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_global', $this->_funcHooks['hookTagCloud'] ) )
{
$count_39629c8d2b893e1d78cac3a998853ac9 = is_array($this->functionData['hookTagCloud']) ? count($this->functionData['hookTagCloud']) : 0;
$this->functionData['hookTagCloud'][$count_39629c8d2b893e1d78cac3a998853ac9]['tags'] = $tags;
}
$IPBHTML .= "<ul class='ipsList_inline'>".$this->__f__d3e156397882f2f860ff1e08b4544f18($tags)."</ul>";
return $IPBHTML;
}


function __f__d3e156397882f2f860ff1e08b4544f18($tags)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $tags['tags'] as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<li><span class=\"{$data['className']}\">{$data['tagWithUrl']}</span></li>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- overwriteHeader --*/
function overwriteHeader() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_global', $this->_funcHooks['overwriteHeader'] ) )
{
$count_aacb79044cd1fdf251935e52226e2b90 = is_array($this->functionData['overwriteHeader']) ? count($this->functionData['overwriteHeader']) : 0;
}
$IPBHTML .= "<style type='text/css'>
/* This has to go here as the css won't be loaded on std error page and header rules are thus ignored */
#blog_title {
	display: block;
	width: 63%;
	background: url({style_image_url}/blog/blank_logo.png) no-repeat;
	position: relative;
}
	#blog_title img {
		position: absolute;
		top: 10px;
		left: 0px;
	}
	
	#blog_title span {
		font-family: Georgia;
		font-style: italic;
		text-transform: capitalize;
		position: absolute;
		top: 10px;
		left: 60px;
		font-size: 1.8em;
		color: #fff;
		text-shadow: #192b40 0px 2px 7px;
		width: 100%;
	}
	
		#blog_title span div {
			position: relative;
			font-size: 0.6em !important;
			top: 2px;
		}
</style>
" . (($this->settings['blog_url']) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$this->registry->blogFunctions->blog['blog_id']}", "public",'' ), "{$this->registry->blogFunctions->blog['blog_seo_name']}", "showblog" ) . "' title='{$this->lang->words['blog_homepage']}' id='blog_title'>
		<img src='{$this->settings['img_url']}/blog/logo_blog.png' alt='{$this->registry->blogFunctions->blog['blog_name']}' />
		<span>
			{$this->registry->blogFunctions->blog['blog_name']}
			" . (($this->registry->blogFunctions->blog['blog_desc']) ? ("
				<div>{$this->registry->blogFunctions->blog['blog_desc']}</div>
			") : ("")) . "
		</span>
	</a>") : ("
	" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'defaultHeader' ) ? $this->registry->getClass('output')->getTemplate('global')->defaultHeader() : '' ) . "
")) . "";
return $IPBHTML;
}

/* -- short_attach_tag --*/
function short_attach_tag($matches) {
$IPBHTML = "";
$IPBHTML .= "<div><a href='{$this->settings['base_url']}app=core&amp;module=attach&amp;section=attach&amp;attach_rel_module=post&amp;attach_id={$matches[1]}' target='_blank'><img src=\"{$this->settings['img_url']}/blog/image.png\" alt=\"\" /></a><br />" . $this->registry->getClass('output')->getReplacement("post_attach_link") . " <a href='{$this->settings['base_url']}app=core&amp;module=attach&amp;section=attach&amp;attach_rel_module=post&amp;attach_id={$matches[1]}' target='_blank'>{$matches[2]}</a></div>";
return $IPBHTML;
}

/* -- short_img_tag --*/
function short_img_tag($matches) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_global', $this->_funcHooks['short_img_tag'] ) )
{
$count_b663cf1a09e05ce4ce15eaf8c920d43f = is_array($this->functionData['short_img_tag']) ? count($this->functionData['short_img_tag']) : 0;
$this->functionData['short_img_tag'][$count_b663cf1a09e05ce4ce15eaf8c920d43f]['matches'] = $matches;
}
$IPBHTML .= "" . ((strpos( $matches[1], $this->settings['emoticons_url'] ) === false) ? ("<img src='{$matches[1]}' style='max-width:300px;height:auto' alt='{$this->lang->words['blog_short_image']}' title='{$this->lang->words['blog_short_image']}' />") : ("{$matches[0]}")) . "";
return $IPBHTML;
}

/* -- short_media_tag --*/
function short_media_tag($url, $type) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_global', $this->_funcHooks['short_media_tag'] ) )
{
$count_237414567263c442ce151583bb7f4797 = is_array($this->functionData['short_media_tag']) ? count($this->functionData['short_media_tag']) : 0;
$this->functionData['short_media_tag'][$count_237414567263c442ce151583bb7f4797]['url'] = $url;
$this->functionData['short_media_tag'][$count_237414567263c442ce151583bb7f4797]['type'] = $type;
}
$IPBHTML .= "<img src='{$this->settings['img_url']}/blog/" . ((strstr( $url, 'youtube.' )) ? ("youtube.png") : ("media.png")) . "'> <a href='$url'>{$type}</a>";
return $IPBHTML;
}

/* -- theme_menu --*/
function theme_menu($themes, $blog, $_customTheme='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_global', $this->_funcHooks['theme_menu'] ) )
{
$count_6562bb4bb2575cf242925e0ac09d0d5e = is_array($this->functionData['theme_menu']) ? count($this->functionData['theme_menu']) : 0;
$this->functionData['theme_menu'][$count_6562bb4bb2575cf242925e0ac09d0d5e]['themes'] = $themes;
$this->functionData['theme_menu'][$count_6562bb4bb2575cf242925e0ac09d0d5e]['blog'] = $blog;
$this->functionData['theme_menu'][$count_6562bb4bb2575cf242925e0ac09d0d5e]['_customTheme'] = $_customTheme;
}
$IPBHTML .= "<ul class='ipbmenu_content' id='themes_menu_menucontent' style='display: none'>
	" . (($this->settings['blog_themes_custom'] OR (is_array($themes) AND count($themes))) ? ("" . (($this->settings['blog_themes_custom']) ? ("
			<li>
				<a href='#' id='add_theme'><img src='{$this->settings['img_url']}/add.png' alt='' /> <strong>{$this->lang->words['custom_theme_create']}</strong></a>
			</li>
		") : ("")) . "" . ((is_array( $themes ) && count( $themes )) ? ("".$this->__f__6579e489cf1e8ef2fc1fdbcb861781eb($themes,$blog,$_customTheme)."		") : ("")) . "
		<li class='submit' style='text-align: center'>
			<form action='{$this->settings['blog_url']}&amp;changeTheme=0' method='post'>
				<input type='submit' class='input_submit' value='{$this->lang->words['reset_theme']}' />
			</form>
		</li>") : ("
		<li class='ipsPad_half'>{$this->lang->words['no_themes']}</li>
	")) . "
</ul>
<script type='text/javascript'>
	ipb.templates['add_theme'] = \"<h3>{$this->lang->words['create_custom_theme']}</h3><div><div id='theme_editor'><img src='{$this->settings['img_url']}/blog/color_wheel.png' alt='' class='input_submit alt' title='{$this->lang->words['launch_color_picker']}' id='theme_color_picker' /><strong>{$this->lang->words['custom_css']}</strong><br /><textarea name='themeContent' id='themeContent' rows='10' cols='29' class='input_text'>{$_customTheme}</textarea></div></div><fieldset class='submit'><input type='submit' value='{$this->lang->words['save_css']}' class='input_submit' id='theme_save' /> <input type='submit' class='input_submit alt' id='theme_preview' value='{$this->lang->words['preview_css']}' /></fieldset>\";
	
	ipb.templates['theme_saved'] = \"<h3>{$this->lang->words['create_custom_theme']}</h3><p class='message'>{$this->lang->words['theme_saved_msg']}</p>\";
</script>";
return $IPBHTML;
}


function __f__6579e489cf1e8ef2fc1fdbcb861781eb($themes, $blog, $_customTheme='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $themes as $theme )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<li>
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$this->request['blogid']}&amp;changeTheme={$theme['id']}", "public",'' ), "", "" ) . "'>{$theme['name']}</a>
				</li>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>