<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 7               */
/* CACHE FILE: Generated: Fri, 23 Sep 2016 17:24:01 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_nexus_emails_7 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['genericInvoiceTable'] = array('cfields','isRenewal','hasLink','cfields','multiplePrices','items','discount','tax','discountOrTax');
$this->_funcHooks['genericPurchasesTable'] = array('purchases');
$this->_funcHooks['giftVoucher'] = array('message');
$this->_funcHooks['shipping_canceled'] = array('cfields','cfields','items','addressLine2','addressState');
$this->_funcHooks['shipping_notification'] = array('cfields','cfields','items','addressLine2','addressState');


}

/* -- autopay --*/
function autopay() {
$IPBHTML = "";
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_new_invoice']} <#AUTOPAY_REASON#><br />
<br />
<br />
<#INVOICE_TABLE#>
<br />
{$this->lang->words['ne_info_only']} <#SHIP#>
<br />
<a href='<#SUPPORT_LINK#>'>{$this->lang->words['ne_contact']}.</a><br />
<br />";
return $IPBHTML;
}

/* -- autopay_fail --*/
function autopay_fail() {
$IPBHTML = "";
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_new_invoice']}. {$this->lang->words['ne_autopay_fail']}<br />
<br />
<br />
<#INVOICE_TABLE#>
<br />
<a href='<#LINK#>'>{$this->lang->words['ne_login_for_payment_urgent']}</a>. {$this->lang->words['ne_autopay_provider']} <a href='<#DETAILS_LINK#>'>{$this->lang->words['ne_autopay_details']}</a>.
<br />
<a href='<#SUPPORT_LINK#>'>{$this->lang->words['ne_contact']}.</a><br />
<br />";
return $IPBHTML;
}

/* -- autoresolve --*/
function autoresolve() {
$IPBHTML = "";
$IPBHTML .= "" . nl2br($this->lang->words['autoresolve_warning']) . "<br />";
return $IPBHTML;
}

/* -- genericInvoiceTable --*/
function genericInvoiceTable($invoice, $cfields, $subtotal, $tax) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_nexus_emails', $this->_funcHooks['genericInvoiceTable'] ) )
{
$count_27c83041e83b797a574cf721de9a645a = is_array($this->functionData['genericInvoiceTable']) ? count($this->functionData['genericInvoiceTable']) : 0;
$this->functionData['genericInvoiceTable'][$count_27c83041e83b797a574cf721de9a645a]['invoice'] = $invoice;
$this->functionData['genericInvoiceTable'][$count_27c83041e83b797a574cf721de9a645a]['cfields'] = $cfields;
$this->functionData['genericInvoiceTable'][$count_27c83041e83b797a574cf721de9a645a]['subtotal'] = $subtotal;
$this->functionData['genericInvoiceTable'][$count_27c83041e83b797a574cf721de9a645a]['tax'] = $tax;
}
$IPBHTML .= "<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=nexus&amp;module=clients&amp;section=invoices&amp;do=view&amp;id={$invoice->id}", "public",'' ), "", "" ) . "'>" . sprintf( $this->lang->words['invoice_number'], $invoice->id ) . " - {$invoice->title}</a></strong><br />
<br />
<table class='ipb_table' style=\"border-bottom: 1px solid #f3f3f3;\">
	<tr style=\"border-bottom: 1px solid #f3f3f3;\">
		<td style='font-weight:bold'>{$this->lang->words['cart_desc']}</td>
		<td style='font-weight:bold'>&nbsp;</tdh>
		<td style='font-weight:bold'>{$this->lang->words['cart_unit']}</td>
		<td style='font-weight:bold'>{$this->lang->words['cart_qty']}</td>
		<td style='font-weight:bold'>{$this->lang->words['cart_line']}</td>
	</tr>
	".$this->__f__cb34b0086b3985d6b19143f354f36b26($invoice,$cfields,$subtotal,$tax)."	" . (($invoice->discount or $tax) ? ("<tr style='font-weight: bold'>
			<td style='text-align: right' colspan='4'>{$this->lang->words['store_subtotal']}</td>
			<td>{$this->lang->formatMoney( $subtotal )}</td>
		</tr>
		" . (($invoice->discount) ? ("
			<tr style='font-weight: bold'>
				<td style='text-align: right' colspan='4'>{$invoice->discount}% {$this->lang->words['store_bundle_discount']}</td>
				<td>{$this->lang->formatMoney( - ( $subtotal - $invoice->total - $tax ) )}</td>
			</tr>
		") : ("")) . "
		" . (($tax) ? ("
			<tr style='font-weight: bold'>
				<td style='text-align: right' colspan='4'>{$this->lang->words['store_tax']}</td>
				<td>{$this->lang->formatMoney( $tax )}</td>
			</tr>
		") : ("")) . "") : ("")) . "
	<tr style='font-weight: bold'>
		<td style='text-align: right' colspan='4'>{$this->lang->words['store_total']}</td>
		<td><strong>{$this->lang->formatMoney( $invoice->total )}</strong></td>
	</tr>
</table>
<br />";
return $IPBHTML;
}


function __f__b804f4ed3cf8b90a5df7fec6caf9ad0d($invoice, $cfields, $subtotal, $tax,$k='',$item='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $item['cfields'] as $id => $value )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						{$cfields[ $id ]['cf_name']}: {$invoice->getCustomFieldValue( $cfields[ $id ], $value )}<br />
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__cb34b0086b3985d6b19143f354f36b26($invoice, $cfields, $subtotal, $tax)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $invoice->items as $k => $item )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<tr style=\"border-bottom: 1px solid #f3f3f3;\">
			<td>
				" . (($item['itemURI']) ? ("
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$item['itemURI']}", "public",'' ), "", "" ) . "'>{$item['itemName']}</a>
				") : ("" . (($item['act'] == 'renewal') ? ("
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=nexus&module=clients&section=purchases&do=view&id={$item['itemID']}", "public",'' ), "", "" ) . "'>{$item['itemName']}</a>
					") : ("
						{$item['itemName']}
					")) . "")) . "
			</td>
			<td>
				" . ((is_array( $item['cfields'] )) ? ("
					".$this->__f__b804f4ed3cf8b90a5df7fec6caf9ad0d($invoice,$cfields,$subtotal,$tax,$k,$item)."				") : ("")) . "
			</td>
			<td class='short'>
				" . ((is_array( $item['prices'] )) ? ("
					" . invoice::formatPrices( $item['prices'] ) . "
				") : ("
					{$this->lang->formatMoney( $item['cost'] )}
				")) . "
			</td>
			<td class='short'>
				{$item['quantity']}
			</td>
			<td>
				{$this->lang->formatMoney( $invoice->getLinePrice( $k ) )}
			</td>
		</tr>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- genericPurchasesTable --*/
function genericPurchasesTable($purchases) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_nexus_emails', $this->_funcHooks['genericPurchasesTable'] ) )
{
$count_755516924f5efc1d345f766e24f3ac28 = is_array($this->functionData['genericPurchasesTable']) ? count($this->functionData['genericPurchasesTable']) : 0;
$this->functionData['genericPurchasesTable'][$count_755516924f5efc1d345f766e24f3ac28]['purchases'] = $purchases;
}
$IPBHTML .= "<br />
<table class='ipb_table' style=\"border-bottom: 1px solid #f3f3f3;\">
	<tr style=\"border-bottom: 1px solid #f3f3f3;\">
		<td style='font-weight:bold'>{$this->lang->words['purchase_id']}</td>
		<td style='font-weight:bold'>{$this->lang->words['purchase_name']}</td>
		<td style='font-weight:bold'>{$this->lang->words['purchase_expire']}</td>
		<td style='font-weight:bold'>{$this->lang->words['purchase_renewals']}</td>
	</tr>
	".$this->__f__93671a81c819caecd4769fd7d3e3169b($purchases)."</table>
<br />";
return $IPBHTML;
}


function __f__93671a81c819caecd4769fd7d3e3169b($purchases)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $purchases as $purchase )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<tr style=\"border-bottom: 1px solid #f3f3f3;\">
			<td>{$purchase['ps_id']}</td>
			<td>{$purchase['ps_name']}</td>
			<td>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($purchase['ps_expire'],"JOINED", 0)) . "</td>
			<td>{$purchase['renewal']}</td>
		</tr>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- giftVoucher --*/
function giftVoucher($purchase, $data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_nexus_emails', $this->_funcHooks['giftVoucher'] ) )
{
$count_71fa3242f1d2e09f6be5e63ca4005eb4 = is_array($this->functionData['giftVoucher']) ? count($this->functionData['giftVoucher']) : 0;
$this->functionData['giftVoucher'][$count_71fa3242f1d2e09f6be5e63ca4005eb4]['purchase'] = $purchase;
$this->functionData['giftVoucher'][$count_71fa3242f1d2e09f6be5e63ca4005eb4]['data'] = $data;
}
$IPBHTML .= "<div style='margin-top: 10px; font-size: 2em'>
	<#AMOUNT#> {$this->lang->words['gift_voucher']}
</div>
<br />
<br />
" . (($data['message']) ? ("
	<div style=\"background: #ebf0f3; padding: 10px;\">
		<#RECIPIENT#>
		<#MESSAGE#>
		<#SENDER#>
	</div>
	<br /><br />
") : ("")) . "
<strong>
	{$this->lang->words['gv_redeem_code']}:<br />
	<#CODE#><br />
	<br />
	<a href='<#LINK#>'>{$this->lang->words['gv_redeem_now']}</a>
</strong>";
return $IPBHTML;
}

/* -- invoice_warn --*/
function invoice_warn() {
$IPBHTML = "";
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_invoice_warn']}.<br />
<br />
<br />
<#PURCHASES_TABLE#>
<br />
{$this->lang->words['ne_invoice_warn_explain']}<br />
<#INVOICE_DATE#><br />
<br />
{$this->lang->words['ne_invoice_warn_check']}<br />
<br />
<a href='<#SUPPORT_LINK#>'>{$this->lang->words['ne_contact']}.</a><br />
<br />";
return $IPBHTML;
}

/* -- new_invoice --*/
function new_invoice() {
$IPBHTML = "";
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_new_invoice']}.<br />
<br />
<br />
<#INVOICE_TABLE#>
<br />
<a href='<#LINK#>'>{$this->lang->words['ne_login_for_payment']}</a>
<br />
{$this->lang->words['ne_note_expiry_dates']}<br />
<br />";
return $IPBHTML;
}

/* -- payment_failed --*/
function payment_failed() {
$IPBHTML = "";
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_payment_failed']}<br />
<br />
<br />
<#INVOICE_TABLE#>
<br />
<#TRANSACTION#><br />
<br />
<a href='<#SUPPORT_LINK#>'>{$this->lang->words['ne_contact']}</a> {$this->lang->words['or']} <a href='<#LINK#>'>{$this->lang->words['ne_login_for_other_payment']}</a>.<br />
<br />";
return $IPBHTML;
}

/* -- payment_held --*/
function payment_held() {
$IPBHTML = "";
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_payment_held']}<br />
<br />
<br />
<#INVOICE_TABLE#>
<br />
<#TRANSACTION#><br />
<br />
{$this->lang->words['ne_additional_approved']}<br />
<br />
<a href='<#SUPPORT_LINK#>'>{$this->lang->words['ne_contact']}.</a><br />
<br />";
return $IPBHTML;
}

/* -- payment_received --*/
function payment_received() {
$IPBHTML = "";
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_payment_received']}<br />
<br />
<br />
<#INVOICE_TABLE#>
<br />
<#TRANSACTION#><br />
<br />
<#SHIP#><br />
<br />";
return $IPBHTML;
}

/* -- payment_refunded --*/
function payment_refunded() {
$IPBHTML = "";
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_payment_refunded']}<br />
<br />
<br />
<#INVOICE_TABLE#>
<br />
<#TRANSACTION#><br />
<br />
{$this->lang->words['ne_refund_explain']}<br />
<a href='<#SUPPORT_LINK#>'>{$this->lang->words['ne_contact']}</a> {$this->lang->words['or']} <a href='<#LINK#>'>{$this->lang->words['ne_login_for_other_payment']}</a>.<br />
<br />";
return $IPBHTML;
}

/* -- payment_waiting --*/
function payment_waiting() {
$IPBHTML = "";
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_order_thanks']}<br />
<br />
<#INSTRUCTIONS_HTML#>
<br />
<br />
<#INVOICE_TABLE#>
<br />
<a href='<#LINK#>'>{$this->lang->words['ne_login_for_payment']}</a>
<br />
{$this->lang->words['ne_additional_confirm']}<br />
<br />
<a href='<#SUPPORT_LINK#>'>{$this->lang->words['ne_contact']}.</a><br />
<br />";
return $IPBHTML;
}

/* -- reply --*/
function reply() {
$IPBHTML = "";
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_support_reply']}<br />
<br />
<div style=\"background: #ebf0f3; padding: 10px;\">
	<#MESSAGE#>
</div>
<br />
<br />
<#REPLY_NOTIFY#>";
return $IPBHTML;
}

/* -- shipping_canceled --*/
function shipping_canceled($items, $cfields, $address) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_nexus_emails', $this->_funcHooks['shipping_canceled'] ) )
{
$count_ffaa85cd88ea867869a53e1e5af5a0e8 = is_array($this->functionData['shipping_canceled']) ? count($this->functionData['shipping_canceled']) : 0;
$this->functionData['shipping_canceled'][$count_ffaa85cd88ea867869a53e1e5af5a0e8]['items'] = $items;
$this->functionData['shipping_canceled'][$count_ffaa85cd88ea867869a53e1e5af5a0e8]['cfields'] = $cfields;
$this->functionData['shipping_canceled'][$count_ffaa85cd88ea867869a53e1e5af5a0e8]['address'] = $address;
}
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_ship_canc_notification']}<br />
<br />
<table class='ipb_table' style=\"border-bottom: 1px solid #f3f3f3;\">
	<tr style=\"border-bottom: 1px solid #f3f3f3;\">
		<td style='font-weight:bold'>{$this->lang->words['item']}</td>
		<td style='font-weight:bold'>&nbsp;</td>
		<td style='font-weight:bold'>{$this->lang->words['cart_qty']}</td>
	</tr>
	".$this->__f__6ccedbe3f0ea96090aaf917c9ea0b004($items,$cfields,$address)."</table>
<br />
<br />
<#SHIP_METHOD#><br />
{$address['first_name']} {$address['last_name']}<br />
{$address['address_1']}<br />
" . (($address['address_2']) ? ("
	{$address['address_2']}<br />
") : ("")) . "
{$address['city']}<br />
" . (($address['state']) ? ("
	{$address['state']}<br />
") : ("")) . "
{$address['zip']}<br />
<br />
<br />
<#TRACKING#><br />
<br />
<a href='<#SUPPORT_LINK#>'>{$this->lang->words['ne_contact']}.</a><br />
<br />";
return $IPBHTML;
}


function __f__0fef6171a281843b4606305c1625d397($items, $cfields, $address,$item='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $item['cfields'] as $id => $value )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						{$cfields[ $id ]['cf_name']}: {$value}<br />
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__6ccedbe3f0ea96090aaf917c9ea0b004($items, $cfields, $address)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $items as $item )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<tr style=\"border-bottom: 1px solid #f3f3f3;\">
			<td>{$item['itemName']}</td>
			<td>
				" . ((is_array( $item['cfields'] )) ? ("
					".$this->__f__0fef6171a281843b4606305c1625d397($items,$cfields,$address,$item)."				") : ("")) . "
			</td>
			<td>{$item['quantity']}</td>
		</tr>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- shipping_notification --*/
function shipping_notification($items, $cfields, $address) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_nexus_emails', $this->_funcHooks['shipping_notification'] ) )
{
$count_f0cb6de385d7914c04da034572716ce9 = is_array($this->functionData['shipping_notification']) ? count($this->functionData['shipping_notification']) : 0;
$this->functionData['shipping_notification'][$count_f0cb6de385d7914c04da034572716ce9]['items'] = $items;
$this->functionData['shipping_notification'][$count_f0cb6de385d7914c04da034572716ce9]['cfields'] = $cfields;
$this->functionData['shipping_notification'][$count_f0cb6de385d7914c04da034572716ce9]['address'] = $address;
}
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_ship_notification']}<br />
<br />
<table class='ipb_table' style=\"border-bottom: 1px solid #f3f3f3;\">
	<tr style=\"border-bottom: 1px solid #f3f3f3;\">
		<td style='font-weight:bold'>{$this->lang->words['item']}</td>
		<td style='font-weight:bold'>&nbsp;</td>
		<td style='font-weight:bold'>{$this->lang->words['cart_qty']}</td>
	</tr>
	".$this->__f__0c4986e35c25e9fd1fd1e49691478415($items,$cfields,$address)."</table>
<br />
<br />
<#SHIP_METHOD#><br />
{$address['first_name']} {$address['last_name']}<br />
{$address['address_1']}<br />
" . (($address['address_2']) ? ("
	{$address['address_2']}<br />
") : ("")) . "
{$address['city']}<br />
" . (($address['state']) ? ("
	{$address['state']}<br />
") : ("")) . "
{$address['zip']}<br />
<br />
<br />
<#TRACKING#><br />
<br />
<a href='<#SUPPORT_LINK#>'>{$this->lang->words['ne_contact']}.</a><br />
<br />";
return $IPBHTML;
}


function __f__254a0256c56749014eac63e8090387cf($items, $cfields, $address,$item='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $item['cfields'] as $id => $value )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						{$cfields[ $id ]['cf_name']}: {$value}<br />
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__0c4986e35c25e9fd1fd1e49691478415($items, $cfields, $address)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $items as $item )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<tr style=\"border-bottom: 1px solid #f3f3f3;\">
			<td>{$item['itemName']}</td>
			<td>
				" . ((is_array( $item['cfields'] )) ? ("
					".$this->__f__254a0256c56749014eac63e8090387cf($items,$cfields,$address,$item)."				") : ("")) . "
			</td>
			<td>{$item['quantity']}</td>
		</tr>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- staff_notify --*/
function staff_notify() {
$IPBHTML = "";
$IPBHTML .= "<#STAFF_NAME#>,<br />
<br />
{$this->lang->words['ne_support_staff']}<br />
<br />
<strong><#TITLE#></strong><br />
<br />
<#POSTER#>:<br />
<div style=\"background: #ebf0f3; padding: 10px;\">
	<#MESSAGE#>
</div>
<br />
<br />
<#REPLY_NOTIFY#>";
return $IPBHTML;
}

/* -- support --*/
function support() {
$IPBHTML = "";
$IPBHTML .= "<#CUSTOMER_NAME#>,<br />
<br />
{$this->lang->words['ne_support_new']}<br />
<br />
<strong><a href='<#LINK#>'><#TITLE#></a></strong><br />
<br />
<div style=\"background: #ebf0f3; padding: 10px;\">
	<#MESSAGE#>
</div>
<br />
<br />
<#REPLY_NOTIFY#>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>