<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 7               */
/* CACHE FILE: Generated: Fri, 23 Sep 2016 17:24:00 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_home_7 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['album_listing'] = array('inlineNotApproved','filerate1','filerate2','filerate3','ralerate4','filerate5','albumIsFriendOnly','albumIsPrivate','canUploadToAlbum','canEditAlbum','canDeleteAlbum','showAlbumOptions','coverNotApprved','hasLatest','albumsLoop','albumSetName','albumNameSOA','albumNameSOD','albumSetDate','albumDateSOA','albumDateSOD','albumSetRate','albumRateSOA','albumRateSOD','albumSetImages','albumImagesSOA','albumImagesSOD','albumSetComments','albumCommentsSOA','albumCommentsSOD','albumCategoryComments','albumSetAsc','albumSortAsc','albumSetDesc','albumSortDesc','catnorows');
$this->_funcHooks['category'] = array('hasRulesTitle','hasRules','hasFollow','hasDescription','topTopPages','canIUpload','isMembersGallery','hasImages','hasSubCategories','hasPagesTop','showMembers','showImages','showAlbums','hasPagesBottom','memAlbumAlbums','memAlbumAlbums','memAlbumAlbums','isMembersGalleryMenu');
$this->_funcHooks['category_listing'] = array('hasImage','categoryAllowsAlbums','categoryComments','categoryLoop');
$this->_funcHooks['homeBottom'] = array('hasAlbums','hasImages');
$this->_funcHooks['homeSocial'] = array('hasMedPatch','hasMedPatchH','featuredImages','featuredImageAlbum','featuredImages','imagesLoop','recentNotApproved','notRead','notApproved','imagePinned','views','comments','imagesLoop','canView','categoriesLoop','hasChildren','canView','categoriesLoop','canIUpload','needSidebar','patchwork','weHaveFeatured','weHaveAlbums','weHaveRecent','weHaveComments','weHaveTags','showSidebar');
$this->_funcHooks['homeTraditional'] = array('hasMedPatch','hasMedPatchH','featuredImages','featuredImageAlbum','featuredImages','recentNotApproved','notRead','notApproved','imagePinned','views','comments','imagesLoop','canIUpload','needSidebar','weHaveComments','weHaveTags','showSidebar','patchwork','weHaveFeatured','weHaveRecent');
$this->_funcHooks['image_listing'] = array('lwrapperunapproved','lmoderate','largeNotRead','largeUnapproved','limagePinned','lviews','lcomments','imagesLoop','notApprovedWrapper','notRead','notApproved','imagePinned','views','comments','imagesLoop','thumbActive','largeActive','canChangeViewStyle','imageSetCDate','imageDateCSOA','imageDateCSOD','imageSetCDate','imageViewsCSOA','imageViewsCSOD','imageSetCDate','imageRateCSOA','imageRateCSOD','imageSetCDate','imageCommentsCSOA','imageCommentsCSOD','imageSetCDate','imageCommentsSCSOA','imageCommentsSCSOD','isCategoryComments','isAlbumComments','imageSetCCaption','imageCaptionCSOA','imageCaptionCSOD','ImageSetAsc','imageSortAsc','ImageSetDesc','imageSortDesc','largeViewStyleCheck','hasImages','showModOption');
$this->_funcHooks['member_listing'] = array('memberImages','hasImages','albumhasLatestImage','albumsLoop','catnorows');


}

/* -- album_listing --*/
function album_listing($albums, $category, $sortData=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_home', $this->_funcHooks['album_listing'] ) )
{
$count_bf033cfe3fb7e40367bdaac99c66bda4 = is_array($this->functionData['album_listing']) ? count($this->functionData['album_listing']) : 0;
$this->functionData['album_listing'][$count_bf033cfe3fb7e40367bdaac99c66bda4]['albums'] = $albums;
$this->functionData['album_listing'][$count_bf033cfe3fb7e40367bdaac99c66bda4]['category'] = $category;
$this->functionData['album_listing'][$count_bf033cfe3fb7e40367bdaac99c66bda4]['sortData'] = $sortData;
}

// This is a bit of a messy way of doing it, but we have to calculate these
	// here because they depend on system settings.
	//---------------------------------------------------------------------------
	// 8: padding on each thumb
	// 11: margin between top and bottom rows
	// 5: A bit of breathing space for the shadow
	$previewHeight = ( 8 * 2 ) + ( ( ( $this->settings['gallery_use_square_thumbnails'] ) ? $this->settings['gallery_size_thumb_width'] : $this->settings['gallery_size_thumb_height'] ) * 2 ) + 11;
	$largePreviewSize = $previewHeight - 8;
	$previewLeft = $largePreviewSize + 20;
	$previewHeight += 5;
$IPBHTML .= "<style type='text/css'>
	.gallery_preview_strip { height: {$previewHeight}px; left: {$previewLeft}px; }
	.gallery_album { min-height: {$previewHeight}px; }
	.gallery_album_image { width: {$largePreviewSize}px; height: {$largePreviewSize}px;	}
</style>

<div class='maintitle ipsFilterbar'>
	<div class='filterBarPrefix'>{$this->lang->words['sortby_prefix']}</div>
	<ul class='ipsList_inline left'>
		<li " . (($this->request['asort_key'] == 'name' || $this->request['asort_key'] == 'album_name' || (!$this->request['asort_key'] AND $sortData['sort_key'] == 'album_name')) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;asort_key=name&amp;asort_order=" . (($this->request['asort_order']) ? ("{$this->request['asort_order']}") : ("" . (($sortData['sort_dir']) ? ("{$sortData['sort_dir']}") : ("asc")) . "")) . "", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['filter_by_name']}</a>
		</li>
		<li " . (($this->request['asort_key'] == 'date' || $this->request['asort_key'] == 'album_last_img_date' || (!$this->request['asort_key'] AND $sortData['sort_key'] == 'album_last_img_date')) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;asort_key=date&amp;asort_order=" . (($this->request['asort_order']) ? ("{$this->request['asort_order']}") : ("" . (($sortData['sort_dir']) ? ("{$sortData['sort_dir']}") : ("asc")) . "")) . "", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['filter_most_recent']}</a>
		</li>
		<li " . (($this->request['asort_key'] == 'rated' || $this->request['asort_key'] == 'album_rating_aggregate' || (!$this->request['asort_key'] AND $sortData['sort_key'] == 'album_rating_aggregate')) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;asort_key=rated&amp;asort_order=" . (($this->request['asort_order']) ? ("{$this->request['asort_order']}") : ("" . (($sortData['sort_dir']) ? ("{$sortData['sort_dir']}") : ("asc")) . "")) . "", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['filter_highest_rated']}</a>
		</li>
		<li " . (($this->request['asort_key'] == 'images' || $this->request['asort_key'] == 'album_count_imgs' || (!$this->request['asort_key'] AND $sortData['sort_key'] == 'album_count_imgs')) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;asort_key=images&amp;asort_order=" . (($this->request['asort_order']) ? ("{$this->request['asort_order']}") : ("" . (($sortData['sort_dir']) ? ("{$sortData['sort_dir']}") : ("asc")) . "")) . "", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['filter_most_images']}</a>
		</li>
		" . (($category['category_allow_comments']) ? ("<li " . (($this->request['asort_key'] == 'comments' || $this->request['asort_key'] == 'album_count_comments' || (!$this->request['asort_key'] AND $sortData['sort_key'] == 'album_count_comments')) ? ("class='active'") : ("")) . ">
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;asort_key=comments&amp;asort_order=" . (($this->request['asort_order']) ? ("{$this->request['asort_order']}") : ("" . (($sortData['sort_dir']) ? ("{$sortData['sort_dir']}") : ("asc")) . "")) . "", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['filter_most_comments']}</a>
			</li>") : ("")) . "
	</ul>
	<div class='filterBarPrefix second'>{$this->lang->words['sortorder_prefix']}</div>
	<ul class='ipsList_inline'>
		<li " . (($this->request['asort_order'] == 'asc' || (!$this->request['asort_order'] AND ( strtolower($sortData['sort_dir']) == 'asc' OR !$sortData['sort_dir'] ) )) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;asort_key=" . (($this->request['asort_key']) ? ("{$this->request['asort_key']}") : ("{$sortData['sort_key']}")) . "&amp;asort_order=asc", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['dir_sort_az']}</a>
		</li>
		<li " . (($this->request['asort_order'] == 'desc' || (!$this->request['asort_order'] AND strtolower($sortData['sort_dir']) == 'desc')) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;asort_key=" . (($this->request['asort_key']) ? ("{$this->request['asort_key']}") : ("{$sortData['sort_key']}")) . "&amp;asort_order=desc", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['dir_sort_za']}</a>
		</li>
	</ul>
</div>
<div class='ipsBox gallery_box'>
	" . ((!count($albums)) ? ("
		<div class='no_messages'>
			{$this->lang->words['albums_none_to_see']}
		</div>
	") : ("
		".$this->__f__1617e94bb7cde426f2162fd3297f96b8($albums,$category,$sortData)."	")) . "
</div>
<br />";
return $IPBHTML;
}


function __f__e513bf3a0bef45106ea26cab9c9d4b3c($albums, $category, $sortData=array(),$data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $data['_latest'] as $idx => $img )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
									<li class='gallery_image" . (($img['image_approved'] != 1) ? (" moderated") : ("")) . "' data-tooltip=\"" . IPSText::truncate( $img['image_caption'], 40 ) . "\">
										{$img['thumb']}
									</li>
								
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__1617e94bb7cde426f2162fd3297f96b8($albums, $category, $sortData=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $albums as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<div class='gallery_album'>
				<div class='gallery_album_info'>
					" . (($data['album_allow_rating']) ? ("<p class='right'>
							" . (($data['album_rating_aggregate'] >= 1) ? ("<img src=\"{$this->settings['img_url']}/star.png\" alt='*' class='rate_img' />") : ("<img src=\"{$this->settings['img_url']}/star_off.png\" alt='*' class='rate_img' />")) . "
							" . (($data['album_rating_aggregate'] >= 2) ? ("<img src=\"{$this->settings['img_url']}/star.png\" alt='*' class='rate_img' />") : ("<img src=\"{$this->settings['img_url']}/star_off.png\" alt='*' class='rate_img' />")) . "
							" . (($data['album_rating_aggregate'] >= 3) ? ("<img src=\"{$this->settings['img_url']}/star.png\" alt='*' class='rate_img' />") : ("<img src=\"{$this->settings['img_url']}/star_off.png\" alt='*' class='rate_img' />")) . "
							" . (($data['album_rating_aggregate'] >= 4) ? ("<img src=\"{$this->settings['img_url']}/star.png\" alt='*' class='rate_img' />") : ("<img src=\"{$this->settings['img_url']}/star_off.png\" alt='*' class='rate_img' />")) . "
							" . (($data['album_rating_aggregate'] >= 5) ? ("<img src=\"{$this->settings['img_url']}/star.png\" alt='*' class='rate_img' />") : ("<img src=\"{$this->settings['img_url']}/star_off.png\" alt='*' class='rate_img' />")) . "
						</p>") : ("")) . "
					<h2 class='ipsType_subtitle'>
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$data['album_id']}", "public",'' ), "{$data['album_name_seo']}", "viewalbum" ) . "'>" . IPSText::truncate( $data['album_name'], 40 ) . "</a>
					</h2>
					<div class='desc'>
						" . (($this->registry->gallery->helper('albums')->isFriends($data)) ? ("
							<span class='ipsBadge ipsBadge_green reset_cursor' data-tooltip='{$this->lang->words['friend_only_prefix_desc']}' title='{$this->lang->words['friend_only_prefix_desc']}'>{$this->lang->words['friend_only_prefix']}</span>&nbsp;
						") : ("")) . "
						" . (($this->registry->gallery->helper('albums')->isPrivate($data)) ? ("
							<span class='ipsBadge ipsBadge_red reset_cursor'>{$this->lang->words['private_ucfirst']}</span>&nbsp;
						") : ("")) . " 
						" . IPSText::truncate( strip_tags( $data['album_description'] ), 300 ) . "
					</div>
					<br />
					" . (($this->registry->gallery->helper('albums')->isUploadable($data) || $this->registry->gallery->helper('albums')->isOwner($data) || $this->registry->gallery->helper('albums')->canModerate($data)) ? ("<ul class='ipsList_inline right ipsType_smaller'>
							" . (($this->registry->gallery->helper('albums')->isUploadable($data)) ? ("
								<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=post&amp;section=image&amp;album_id={$data['album_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['upload']}'>{$this->lang->words['upload']}</a></li>
							") : ("")) . "
							" . (($this->registry->gallery->helper('albums')->canEdit($data)) ? ("
								<li>&nbsp;&nbsp;<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;albumedit={$data['album_id']}", "public",'' ), "{$data['album_name_seo']}", "editalbum" ) . "' title='{$this->lang->words['edit']}'>{$this->lang->words['edit']}</a></li>
							") : ("")) . "
							" . (($this->registry->gallery->helper('albums')->canDelete($data)) ? ("
								<li>&nbsp;&nbsp;<a href=\"javascript:void(0);\" album-id=\"{$data['album_id']}\" class=\"_albumDelete\" title='{$this->lang->words['delete_link']}'>{$this->lang->words['delete_link']}</a></li>
							") : ("")) . "
						</ul>
						<br />") : ("")) . "
					<div class='clear ipsPad_top'>
						<ul class='ipsList_inline gallery_item_info right'>
							<li><img src='{$this->settings['img_url']}/gallery/icon_image.png' alt='' /> {$data['album_count_imgs']}</li>
							" . (($data['album_allow_comments']) ? ("
								<li><img src='{$this->settings['img_url']}/gallery/icon_comments.png' alt='' /> {$data['album_count_comments']}</li>
							") : ("")) . "
						</ul>
						<strong>{$this->lang->words['by']}</strong> <img src='{$data['pp_thumb_photo']}' class='ipsUserPhoto ipsUserPhoto_tiny' /> " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($data) : '' ) . "
					</div> 
				</div>
				<div class='gallery_album_previews'>
					<div class='gallery_image" . ((isset($data['_coverImage']['image_id']) AND $data['_coverImage']['image_id'] AND $data['_coverImage']['image_approved'] != 1) ? (" moderated") : ("")) . "'>
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$data['album_id']}", "public",'' ), "{$data['album_name_seo']}", "viewalbum" ) . "'><div class='gallery_album_image' style='background-size: cover; background-position: center center; background-repeat: no-repeat; background-image: url( {$data['coverUrl']} )'></div></a>
					</div>
					" . ((count( $data['_latest'] )) ? ("
						<div class='gallery_preview_strip'>
							<ul class='ipsList_inline ipsList_reset'>
								".$this->__f__e513bf3a0bef45106ea26cab9c9d4b3c($albums,$category,$sortData,$data)."							</ul>
						</div>
					") : ("")) . "
				</div>
			</div>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- category --*/
function category($category, $categories, $albums, $images, $pages, $follow='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_home', $this->_funcHooks['category'] ) )
{
$count_b94b7ae1d271625b246d3baf00f6dd86 = is_array($this->functionData['category']) ? count($this->functionData['category']) : 0;
$this->functionData['category'][$count_b94b7ae1d271625b246d3baf00f6dd86]['category'] = $category;
$this->functionData['category'][$count_b94b7ae1d271625b246d3baf00f6dd86]['categories'] = $categories;
$this->functionData['category'][$count_b94b7ae1d271625b246d3baf00f6dd86]['albums'] = $albums;
$this->functionData['category'][$count_b94b7ae1d271625b246d3baf00f6dd86]['images'] = $images;
$this->functionData['category'][$count_b94b7ae1d271625b246d3baf00f6dd86]['pages'] = $pages;
$this->functionData['category'][$count_b94b7ae1d271625b246d3baf00f6dd86]['follow'] = $follow;
}
$IPBHTML .= "" . (($category['category_rules__text']) ? ("<div class='message unspecific'>
		" . (($category['category_rules__title']) ? ("<h3>{$category['category_rules__title']}</h3>") : ("")) . "
		{$category['category_rules__text']}
	</div>
	<br />") : ("")) . "
<script type=\"text/javascript\">
 ipb.gallery.categoryId	= parseInt({$category['category_id']});
</script>
" . (($follow) ? ("
	{$follow}
") : ("")) . "
<div class='right' style='margin: 3px 10px;'>
	<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=albums&amp;section=rss&amp;type=category&amp;typeid={$category['category_id']}", "public",'' ), "{$category['category_name_seo']}", "galleryrss" ) . "\"><img src=\"{$this->settings['img_url']}/rss-mini.png\" alt=\"{$this->lang->words['rss_feed']}\" /></a>
</div>
{$category['cover']['tag']}
<div class='ipsBox_withphoto ipsGallery_h1image'>
	<h1 class='ipsType_pagetitle'>{$category['category_name']}</h1>
	" . (($category['category_description']) ? ("
		<div class='ipsType_pagedesc forum_rules'>
			{$category['category_description']}
		</div>
	") : ("")) . "
</div>
<div class='topic_controls clear clearfix'>
	" . ((!count($categories) AND $pages) ? ("
		{$pages}
	") : ("")) . "
	<ul class='topic_buttons'>
		" . (($this->registry->gallery->getCanUpload()) ? ("
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=post&amp;section=image&amp;category_id={$category['category_id']}", "public",'' ), "", "" ) . "'>{$this->lang->words['upload']}</a></li>
		") : ("")) . "
		" . (($category['category_id'] == $this->settings['gallery_members_album']) ? ("
			<li><a id='viewOptions' class='ipbmenu' href='#viewOptions'>{$this->lang->words['memgallery_showme']} &nbsp;<img src='{$this->settings['img_url']}/opts_arrow.png' alt='&gt;' /></a></li>
		") : ("")) . "
		" . ((count($images)) ? ("
			<li class='non_button'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=images&amp;section=slideshow&amp;type=category&amp;typeid={$category['category_id']}", "public",'' ), "false", "slideshow" ) . "\">{$this->lang->words['ss_title']}</a></li>
		") : ("")) . "
	</ul>
</div>
<div class='ipsLayout'>
	<div class='ipsLayout_content'>
		" . ((count($categories)) ? ("
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_home'), 'category_listing' ) ? $this->registry->getClass('output')->getTemplate('gallery_home')->category_listing($categories, true) : '' ) . "
		") : ("")) . "
		" . ((count($categories) AND $pages) ? ("
			{$pages}<br class='clear' />
		") : ("")) . "
		
		" . (($category['category_type'] == 1) ? ("
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_home'), 'album_listing' ) ? $this->registry->getClass('output')->getTemplate('gallery_home')->album_listing($albums, $category, array( 'url' => 'app=gallery&amp;category=' . $category['category_id'], 'title' => $category['category_name_seo'], 'template' => 'viewcategory', 'sort_key' => $category['category_sort_options__key'], 'sort_dir' => $category['category_sort_options__dir'] )) : '' ) . "
		") : ("" . (($category['category_type'] == 2) ? ("
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_home'), 'image_listing' ) ? $this->registry->getClass('output')->getTemplate('gallery_home')->image_listing($images, array(), $category, array( 'url' => 'app=gallery&amp;category=' . $category['category_id'], 'title' => $category['category_name_seo'], 'template' => 'viewcategory', 'sort_key' => $category['category_sort_options__key'], 'sort_dir' => $category['category_sort_options__dir'] ), true, IPSCookie::get('gallery_view_size')) : '' ) . "
			") : ("" . (($category['category_type'] == 4) ? ("
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_home'), 'member_listing' ) ? $this->registry->getClass('output')->getTemplate('gallery_home')->member_listing($albums, $category, array( 'url' => 'app=gallery&amp;category=' . $category['category_id'], 'title' => $category['category_name_seo'], 'template' => 'viewcategory' )) : '' ) . "
				") : ("")) . "")) . "")) . "
	</div>
</div>
" . (($pages) ? ("
	<div class='clear'>{$pages}</div>
	<br />
") : ("")) . "
<br class='clear' />
" . (($category['category_id'] == $this->settings['gallery_members_album']) ? ("<ul class=\"ipbmenu_content memAlbumOptions\" id='viewOptions_menucontent' style='display:none' >
	<li" . (($category['category_type'] == 1) ? (" class='active'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;category={$category['category_id']}&amp;showme=albums", "public",'' ), "{$category['category_name_seo']}", "viewcategory" ) . "'>{$this->lang->words['gallery_albums_heading']}</a></li>
	<li" . (($category['category_type'] == 2) ? (" class='active'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;category={$category['category_id']}&amp;showme=images", "public",'' ), "{$category['category_name_seo']}", "viewcategory" ) . "'>{$this->lang->words['gallery_images_heading']}</a></li>
	<li" . (($category['category_type'] == 4) ? (" class='active'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;category={$category['category_id']}&amp;showme=members", "public",'' ), "{$category['category_name_seo']}", "viewcategory" ) . "'>{$this->lang->words['gallery_members_heading']}</a></li>
</ul>") : ("")) . "";
return $IPBHTML;
}

/* -- category_listing --*/
function category_listing($categories, $asSubcats=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_home', $this->_funcHooks['category_listing'] ) )
{
$count_4e6595334dc74734a00181e433d57f58 = is_array($this->functionData['category_listing']) ? count($this->functionData['category_listing']) : 0;
$this->functionData['category_listing'][$count_4e6595334dc74734a00181e433d57f58]['categories'] = $categories;
$this->functionData['category_listing'][$count_4e6595334dc74734a00181e433d57f58]['asSubcats'] = $asSubcats;
}
$IPBHTML .= "<div class='gallery_box'>
	".$this->__f__772461acc9d77742c23b8ab6f1bfb9c0($categories,$asSubcats)."</div>
<br /><br />";
return $IPBHTML;
}


function __f__772461acc9d77742c23b8ab6f1bfb9c0($categories, $asSubcats=false)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $categories as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<div class='gallery_category'>
		 	<div>
		 		<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;category={$data['category_id']}", "public",'' ), "{$data['category_name_seo']}", "viewcategory" ) . "' title='{$data['category_name']}'>
					<h2>{$data['category_name']}</h2>
					<div class='gallery_category_image'" . (($data['coverUrl']) ? (" style='background-image: url({$data['coverUrl']});'") : ("")) . "></div>
				</a>
				<ul class='gallery_item_info ipsList_inline'>
					<li class='left' title='{$this->lang->words['updated_ucfirst']}'>
						<img src='{$this->settings['img_url']}/gallery/icon_clock.png' alt='' /> " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($data['category_last_img_date'],"DATE", 0)) . "
					</li>
					
					<li title='{$this->lang->words['col__gallery_categories_category_count_imgs']}'><img src='{$this->settings['img_url']}/gallery/icon_image.png' alt='' /> {$data['category_count_imgs']}</li>
					" . (($data['category_type'] == 1) ? ("
						<li title='{$this->lang->words['col__gallery_categories_category_public_albums']}'><img src='{$this->settings['img_url']}/gallery/icon_albums.png' /> {$data['category_public_albums']}</li>
					") : ("")) . "
					<li " . ((!$data['category_count_comments']) ? ("class='faded'") : ("")) . " title='{$this->lang->words['col__gallery_categories_category_count_comments']}'><img src='{$this->settings['img_url']}/gallery/icon_comments.png' alt='' /> {$data['category_count_comments']}</li>
				</ul>	
			</div>			
		</div>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- homeBottom --*/
function homeBottom($stats) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_home', $this->_funcHooks['homeBottom'] ) )
{
$count_08e9ffef2b7be6200ad3876081ead561 = is_array($this->functionData['homeBottom']) ? count($this->functionData['homeBottom']) : 0;
$this->functionData['homeBottom'][$count_08e9ffef2b7be6200ad3876081ead561]['stats'] = $stats;
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("gallery_slider", "0" ) . "
<br class='clear' />
<br />
<script type=\"text/javascript\">
	document.observe(\"dom:loaded\", function(){
		if( $('featuredImages') )
		{
			new ipb_gallery.carousel( $('featuredImages') );
		}
	} );
</script>
<div id='board_stats'>
	<ul class='ipsType_small ipsList_inline'>
		" . (($stats['albums']) ? ("
			<li class='clear'>
				<span class='value'>" . $this->registry->getClass('class_localization')->formatNumber( $stats['albums'] ) . "</span>
				{$this->lang->words['stats_total_albums']}
			</li>
		") : ("")) . "
		<li class='clear'>
			<span class='value'>" . $this->registry->getClass('class_localization')->formatNumber( $stats['images'] ) . "</span>
			{$this->lang->words['stats_total_images']}
		</li>
		<li class='clear'>
			<span class='value'>" . $this->registry->getClass('class_localization')->formatNumber( $stats['comments'] ) . "</span>
			{$this->lang->words['stats_total_comments']}
		</li>
		" . (($stats['images']) ? ("
		<li class='clear'>
			<span class='value'>{$stats['diskspace']}</span>
			{$this->lang->words['stats_total_size']}
		</li>
		") : ("")) . "
	</ul>
</div>
<br />";
return $IPBHTML;
}

/* -- homeSocial --*/
function homeSocial($categories, $featuredImages, $recentImages, $recentAlbums, $recentComments, $tagCloud, $stats) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_home', $this->_funcHooks['homeSocial'] ) )
{
$count_df12c553107abd83305a3ed3d66ba196 = is_array($this->functionData['homeSocial']) ? count($this->functionData['homeSocial']) : 0;
$this->functionData['homeSocial'][$count_df12c553107abd83305a3ed3d66ba196]['categories'] = $categories;
$this->functionData['homeSocial'][$count_df12c553107abd83305a3ed3d66ba196]['featuredImages'] = $featuredImages;
$this->functionData['homeSocial'][$count_df12c553107abd83305a3ed3d66ba196]['recentImages'] = $recentImages;
$this->functionData['homeSocial'][$count_df12c553107abd83305a3ed3d66ba196]['recentAlbums'] = $recentAlbums;
$this->functionData['homeSocial'][$count_df12c553107abd83305a3ed3d66ba196]['recentComments'] = $recentComments;
$this->functionData['homeSocial'][$count_df12c553107abd83305a3ed3d66ba196]['tagCloud'] = $tagCloud;
$this->functionData['homeSocial'][$count_df12c553107abd83305a3ed3d66ba196]['stats'] = $stats;
}
$IPBHTML .= "" . (($this->registry->gallery->getCanUpload()) ? ("
	<ul class='topic_buttons'>
		<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=post&amp;section=image", "public",'' ), "", "" ) . "'>{$this->lang->words['upload']}</a></li>
	</ul>
") : ("")) . "
<h1 class='ipsType_pagetitle'>" . IPSLib::getAppTitle('gallery') . "</h1>
<br />
<div class='ipsLayout" . ((count($recentComments) OR $tagCloud or count($categories)) ? (" ipsLayout_withright ipsLayout_bigright") : ("")) . "'>
	<div class='ipsLayout_content'>
		" . ((count($featuredImages)) ? ("" . (($this->settings['gallery_featuredimage'] == 'patchwork') ? ("
				" . $this->registry->getClass('output')->addJSModule("gallery_patchwork", "0" ) . "
				<script type='text/javascript'>
					ipb.galleryPatchwork = [
						".$this->__f__54a06143108c96fa5668837f33ed22f1($categories,$featuredImages,$recentImages,$recentAlbums,$recentComments,$tagCloud,$stats)."					];
				</script>
				<h2 class='maintitle'>{$this->lang->words['featured_images_heading']}</h2>
				<div class='ipsBox gallery_box'>
					<div id='featured_images'></div>
				</div>
				<br />
				<script type='text/javascript'>
					$('featured_images').patchwork({ imageData: ipb.galleryPatchwork });
				</script>
			") : ("
				<h2 class='maintitle'>{$this->lang->words['featured_images_heading']}</h2>
				<div class='ipsBox'>
					<div class='ipsBox_container ipsPad'>
						<div class='galleryCarousel' id='featuredImages'>
							<a href='#' id='feature_left' class='carousel_nav carousel_left' style='display: none'>&lsaquo;</a>
							<a href='#' id='feature_right' class='carousel_nav carousel_right' style='display: none'>&rsaquo;</a>
							".$this->__f__f6ba71980803dda237fb2313430d4814($categories,$featuredImages,$recentImages,$recentAlbums,$recentComments,$tagCloud,$stats)."						</div>
					</div>
				</div>
				<br />
			")) . "") : ("")) . "
		" . ((count($recentAlbums)) ? ("
			<h2 class='maintitle'>{$this->lang->words['recent_albums_heading']}</h2>
			<div class='ipsBox gallery_box'>
				<div class='ipsBox_container ipsPad'>
					<ul class='ipsList_inline ipsList_reset wrap'>
						".$this->__f__157eed064558f89a07ace74b2d30ef5f($categories,$featuredImages,$recentImages,$recentAlbums,$recentComments,$tagCloud,$stats)."					</ul>
				</div>
			</div>
			<br />
		") : ("")) . "
		" . ((count($recentImages)) ? ("
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_global'), 'listingLightbox' ) ? $this->registry->getClass('output')->getTemplate('gallery_global')->listingLightbox() : '' ) . "
			<h2 class='maintitle'>{$this->lang->words['recent_images_heading']}</h2>
			<div class='ipsBox gallery_box'>
				".$this->__f__65537b722b3dedd4f36fa115c7dd5293($categories,$featuredImages,$recentImages,$recentAlbums,$recentComments,$tagCloud,$stats)."			</div>
		") : ("")) . "
	</div>
	" . ((count($recentComments) OR $tagCloud or count($categories)) ? ("<div class='ipsLayout_right'>
			<div class='general_box'>
				<h3>{$this->lang->words['categories_sidebarblock']}</h3>
				
				<ul class='ipsPad_half'>
					".$this->__f__34f21b15d44f116b0f274ab6382e8454($categories,$featuredImages,$recentImages,$recentAlbums,$recentComments,$tagCloud,$stats)."				</ul>
			</div>
			<br />
			" . ((count($recentComments)) ? ("
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_albums'), 'miniLatestCommentBlock' ) ? $this->registry->getClass('output')->getTemplate('gallery_albums')->miniLatestCommentBlock($recentComments, $this->lang->words['home_recent_comments']) : '' ) . "
				<br />
			") : ("")) . "
			" . (($tagCloud) ? ("
				{$tagCloud}
				<br />
			") : ("")) . "
                        <!--__SIDEBAR_AD_CODE__-->
		</div>") : ("")) . "
</div>
" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_home'), 'homeBottom' ) ? $this->registry->getClass('output')->getTemplate('gallery_home')->homeBottom($stats) : '' ) . "";
return $IPBHTML;
}


function __f__54a06143108c96fa5668837f33ed22f1($categories, $featuredImages, $recentImages, $recentAlbums, $recentComments, $tagCloud, $stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $featuredImages as $idx => $featuredImage )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							{
								\"image_id\": {$featuredImage['image_id']},
								\"image_url\": \"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;image={$featuredImage['image_id']}", "public",'' ), "{$featuredImage['image_caption_seo']}", "viewimage" ) . "\",
								\"med_img\": \"{$featuredImage['mediumUrl']}\",
								\"thumb_size\": {
								\"w\": " . (($featuredImage['_data']['sizes']['medium'][0]) ? ("{$featuredImage['_data']['sizes']['medium'][0]}") : ("{$featuredImage['_data']['sizes']['max'][0]}")) . ",
								\"h\": " . (($featuredImage['_data']['sizes']['medium'][1]) ? ("{$featuredImage['_data']['sizes']['medium'][1]}") : ("{$featuredImage['_data']['sizes']['max'][1]}")) . ",
								}
							},
						
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__f6ba71980803dda237fb2313430d4814($categories, $featuredImages, $recentImages, $recentAlbums, $recentComments, $tagCloud, $stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $featuredImages as $featuredImage )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
								<div class='carousel_img' style='background-image: url({$featuredImage['tag']});'>
									<a class='carousel_img_link' href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;image={$featuredImage['image_id']}", "public",'' ), "{$featuredImage['image_caption_seo']}", "viewimage" ) . "' title='{$featuredImage['image_caption']}'>&nbsp;</a>
									<div class='imageDescription'>
										<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;image={$featuredImage['image_id']}", "public",'' ), "{$featuredImage['image_caption_seo']}", "viewimage" ) . "' title='{$featuredImage['image_caption']}'>{$featuredImage['image_caption']}</a></strong><br />
										{$featuredImage['image_description']}<br />
										" . (($featuredImage['image_album_id']) ? ("
											{$this->lang->words['slider_from_album']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$featuredImage['image_album_id']}", "public",'' ), "{$featuredImage['album_name_seo']}", "viewalbum" ) . "' title='{$featuredImage['album_name']}'>{$featuredImage['album_name']}</a>
										") : ("
											{$this->lang->words['slider_from_category']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;category={$featuredImage['image_category_id']}", "public",'' ), "{$featuredImage['category_name_seo']}", "viewcategory" ) . "' title='{$featuredImage['category_name']}'>{$featuredImage['category_name']}</a>
										")) . "
									</div>
								</div>
							
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__157eed064558f89a07ace74b2d30ef5f($categories, $featuredImages, $recentImages, $recentAlbums, $recentComments, $tagCloud, $stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $recentAlbums as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							<li>
								" . $this->registry->getClass('gallery')->inlineResize( $data['thumb'],'thumb_medium','','' ) . "
								<div class='desc ipsType_smaller album_meta'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$data['album_id']}", "public",'' ), "{$data['album_name_seo']}", "viewalbum" ) . "'><strong>{$data['album_name']}</strong></a>
								<br />{$this->lang->words['by_lower']} " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($data) : '' ) . "</div>
							</li>
						
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__65537b722b3dedd4f36fa115c7dd5293($categories, $featuredImages, $recentImages, $recentAlbums, $recentComments, $tagCloud, $stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $recentImages as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					<div class='gallery_image" . (($data['image_approved'] != 1) ? (" moderated") : ("")) . "'>
						{$data['thumb']}
						<ul class='gallery_item_info ipsList_inline'>
							" . ((!$data['_isRead']) ? ("
								<li class='left'><img src='{$this->settings['img_url']}/t_unread.png' alt='' data-tooltip='{$this->lang->words['gallery_image_unread']}' /></li>
							") : ("")) . "
							" . (($data['image_approved'] != 1) ? ("<li class='left'><img src='{$this->settings['img_url']}/gallery/icon_moderated.png' alt='' data-tooltip='" . (($data['image_approved'] === -1) ? ("{$this->lang->words['moderated_img_hidden']}") : ("{$this->lang->words['moderated_img_unapproved']}")) . "' /></li>") : ("")) . "
							" . (($data['image_pinned']) ? ("
								<li class='left'><img src='{$this->settings['img_url']}/gallery/icon_pinned.png' alt='' /></li>
							") : ("")) . "
							<li " . ((!$data['image_views']) ? ("class='faded'") : ("")) . "><img src='{$this->settings['img_url']}/gallery/icon_view.png' alt='' /> {$data['image_views']}</li>
							<li " . ((!$data['image_comments']) ? ("class='faded'") : ("")) . "><img src='{$this->settings['img_url']}/gallery/icon_comments.png' alt='' /> {$data['image_comments']}</li>
						</ul>
					</div>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__58e1a6e49ba867fcb28f05245379b5b4($categories, $featuredImages, $recentImages, $recentAlbums, $recentComments, $tagCloud, $stats,$category='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $categories[$category['category_id']] as $child )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
											" . (($this->registry->gallery->helper('categories')->isViewable( $child['category_id'] )) ? ("
												<li class='clear ipsPad_half ipsType_small'>
													<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;category={$child['category_id']}", "public",'' ), "{$child['category_name_seo']}", "viewcategory" ) . "' title='{$child['category_name']}'>{$child['category_name']}</a>
												</li>
											") : ("")) . "
										
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__34f21b15d44f116b0f274ab6382e8454($categories, $featuredImages, $recentImages, $recentAlbums, $recentComments, $tagCloud, $stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $categories[0] as $category )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						" . (($this->registry->gallery->helper('categories')->isViewable( $category['category_id'] )) ? ("<li class='clear ipsPad_half'>
								<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;category={$category['category_id']}", "public",'' ), "{$category['category_name_seo']}", "viewcategory" ) . "' title='{$category['category_name']}'>{$category['category_name']}</a>
								" . ((count($categories[$category['category_id']])) ? ("
									<ul class='ipsGallery_subcategory'>
										".$this->__f__58e1a6e49ba867fcb28f05245379b5b4($categories,$featuredImages,$recentImages,$recentAlbums,$recentComments,$tagCloud,$stats,$category)."									</ul>
								") : ("")) . "
							</li>") : ("")) . "
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- homeTraditional --*/
function homeTraditional($categories, $featuredImages, $recentImages, $recentComments, $tagCloud, $stats) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_home', $this->_funcHooks['homeTraditional'] ) )
{
$count_78d0397d1ffcebb2abe5b882d87ef3dc = is_array($this->functionData['homeTraditional']) ? count($this->functionData['homeTraditional']) : 0;
$this->functionData['homeTraditional'][$count_78d0397d1ffcebb2abe5b882d87ef3dc]['categories'] = $categories;
$this->functionData['homeTraditional'][$count_78d0397d1ffcebb2abe5b882d87ef3dc]['featuredImages'] = $featuredImages;
$this->functionData['homeTraditional'][$count_78d0397d1ffcebb2abe5b882d87ef3dc]['recentImages'] = $recentImages;
$this->functionData['homeTraditional'][$count_78d0397d1ffcebb2abe5b882d87ef3dc]['recentComments'] = $recentComments;
$this->functionData['homeTraditional'][$count_78d0397d1ffcebb2abe5b882d87ef3dc]['tagCloud'] = $tagCloud;
$this->functionData['homeTraditional'][$count_78d0397d1ffcebb2abe5b882d87ef3dc]['stats'] = $stats;
}
$IPBHTML .= "" . (($this->registry->gallery->getCanUpload()) ? ("
	<ul class='topic_buttons'>
		<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=post&amp;section=image", "public",'' ), "", "" ) . "'>{$this->lang->words['upload']}</a></li>
	</ul>
") : ("")) . "
<h1 class='ipsType_pagetitle'>" . IPSLib::getAppTitle('gallery') . "</h1>
<br />
<div class='ipsLayout" . ((count($recentComments) OR $tagCloud) ? (" ipsLayout_withright ipsLayout_bigright") : ("")) . "'>
	" . ((count($recentComments) OR $tagCloud) ? ("<div class='ipsLayout_right'>
			" . ((count($recentComments)) ? ("
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_albums'), 'miniLatestCommentBlock' ) ? $this->registry->getClass('output')->getTemplate('gallery_albums')->miniLatestCommentBlock($recentComments, $this->lang->words['home_recent_comments']) : '' ) . "
				<br />
			") : ("")) . "
			" . (($tagCloud) ? ("
				{$tagCloud}
				<br />
			") : ("")) . "
		</div>") : ("")) . "
	<div class='ipsLayout_content'>
" . ((count($featuredImages)) ? ("" . (($this->settings['gallery_featuredimage'] == 'patchwork') ? ("
		" . $this->registry->getClass('output')->addJSModule("gallery_patchwork", "0" ) . "
		<script type='text/javascript'>
			ipb.galleryPatchwork = [
				".$this->__f__037325e522a373b96e879ba473006255($categories,$featuredImages,$recentImages,$recentComments,$tagCloud,$stats)."			];
		</script>
		<h2 class='maintitle'>{$this->lang->words['featured_images_heading']}</h2>
		<div class='ipsBox gallery_box'>
			<div id='featured_images'></div>
		</div>
		<br />
		<script type='text/javascript'>
			$('featured_images').patchwork({ imageData: ipb.galleryPatchwork });
		</script>
	") : ("
		<h2 class='maintitle'>{$this->lang->words['featured_images_heading']}</h2>
		<div class='ipsBox'>
			<div class='ipsBox_container ipsPad'>
				<div class='galleryCarousel' id='featuredImages'>
					<a href='#' id='feature_left' class='carousel_nav carousel_left' style='display: none'>&lsaquo;</a>
					<a href='#' id='feature_right' class='carousel_nav carousel_right' style='display: none'>&rsaquo;</a>
					".$this->__f__f007bc2ea8f110612242ce3bf1cb9fe3($categories,$featuredImages,$recentImages,$recentComments,$tagCloud,$stats)."				</div>
			</div>
		</div>
		<br />
	")) . "") : ("")) . "
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_home'), 'category_listing' ) ? $this->registry->getClass('output')->getTemplate('gallery_home')->category_listing($categories) : '' ) . "
		" . ((count($recentImages)) ? ("
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_global'), 'listingLightbox' ) ? $this->registry->getClass('output')->getTemplate('gallery_global')->listingLightbox() : '' ) . "
			<h2 class='maintitle'>{$this->lang->words['recent_images_heading']}</h2>
			<div class='ipsBox gallery_box'>
				".$this->__f__16f3cec4f256a8b39d708f33e0a5ef0a($categories,$featuredImages,$recentImages,$recentComments,$tagCloud,$stats)."			</div>
		") : ("")) . "
	</div>
</div>
" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_home'), 'homeBottom' ) ? $this->registry->getClass('output')->getTemplate('gallery_home')->homeBottom($stats) : '' ) . "";
return $IPBHTML;
}


function __f__037325e522a373b96e879ba473006255($categories, $featuredImages, $recentImages, $recentComments, $tagCloud, $stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $featuredImages as $idx => $featuredImage )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					{
						\"image_id\": {$featuredImage['image_id']},
						\"image_url\": \"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;image={$featuredImage['image_id']}", "public",'' ), "{$featuredImage['image_caption_seo']}", "viewimage" ) . "\",
						\"med_img\": \"{$featuredImage['mediumUrl']}\",
						\"thumb_size\": {
							\"w\": " . (($featuredImage['_data']['sizes']['medium'][0]) ? ("{$featuredImage['_data']['sizes']['medium'][0]}") : ("{$featuredImage['_data']['sizes']['max'][0]}")) . ",
							\"h\": " . (($featuredImage['_data']['sizes']['medium'][1]) ? ("{$featuredImage['_data']['sizes']['medium'][1]}") : ("{$featuredImage['_data']['sizes']['max'][1]}")) . ",
						}
					},
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__f007bc2ea8f110612242ce3bf1cb9fe3($categories, $featuredImages, $recentImages, $recentComments, $tagCloud, $stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $featuredImages as $featuredImage )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<div class='carousel_img' style='background-image: url({$featuredImage['tag']});'>
							<a class='carousel_img_link' href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;image={$featuredImage['image_id']}", "public",'' ), "{$featuredImage['image_caption_seo']}", "viewimage" ) . "' title='{$featuredImage['image_caption']}'>&nbsp;</a>
							<div class='imageDescription'>
								<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;image={$featuredImage['image_id']}", "public",'' ), "{$featuredImage['image_caption_seo']}", "viewimage" ) . "' title='{$featuredImage['image_caption']}'>{$featuredImage['image_caption']}</a></strong><br />
								{$featuredImage['image_description']}<br />
								" . (($featuredImage['image_album_id']) ? ("
									{$this->lang->words['slider_from_album']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$featuredImage['image_album_id']}", "public",'' ), "{$featuredImage['album_name_seo']}", "viewalbum" ) . "' title='{$featuredImage['album_name']}'>{$featuredImage['album_name']}</a>
								") : ("
									{$this->lang->words['slider_from_category']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;category={$featuredImage['image_category_id']}", "public",'' ), "{$featuredImage['category_name_seo']}", "viewcategory" ) . "' title='{$featuredImage['category_name']}'>{$featuredImage['category_name']}</a>
								")) . "
							</div>
						</div>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__16f3cec4f256a8b39d708f33e0a5ef0a($categories, $featuredImages, $recentImages, $recentComments, $tagCloud, $stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $recentImages as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					<div class='gallery_image" . (($data['image_approved'] != 1) ? (" moderated") : ("")) . "'>
						{$data['thumb']}
						<ul class='gallery_item_info ipsList_inline'>
							" . ((!$data['_isRead']) ? ("
								<li class='left'><img src='{$this->settings['img_url']}/t_unread.png' alt='' data-tooltip='{$this->lang->words['gallery_image_unread']}' /></li>
							") : ("")) . "
							" . (($data['image_approved'] != 1) ? ("<li class='left'><img src='{$this->settings['img_url']}/gallery/icon_moderated.png' alt='' data-tooltip='" . (($data['image_approved'] === -1) ? ("{$this->lang->words['moderated_img_hidden']}") : ("{$this->lang->words['moderated_img_unapproved']}")) . "' /></li>") : ("")) . "
							" . (($data['image_pinned']) ? ("
								<li class='left'><img src='{$this->settings['img_url']}/gallery/icon_pinned.png' alt='' /></li>
							") : ("")) . "
							<li " . ((!$data['image_views']) ? ("class='faded'") : ("")) . "><img src='{$this->settings['img_url']}/gallery/icon_view.png' alt='' /> {$data['image_views']}</li>
							<li " . ((!$data['image_comments']) ? ("class='faded'") : ("")) . "><img src='{$this->settings['img_url']}/gallery/icon_comments.png' alt='' /> {$data['image_comments']}</li>
						</ul>
					</div>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- image_listing --*/
function image_listing($images, $album, $category, $sortData=array(), $canChangeStyle = false, $viewStyle = false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_home', $this->_funcHooks['image_listing'] ) )
{
$count_3db48c41ef4cfc78d5655d490ae69b3b = is_array($this->functionData['image_listing']) ? count($this->functionData['image_listing']) : 0;
$this->functionData['image_listing'][$count_3db48c41ef4cfc78d5655d490ae69b3b]['images'] = $images;
$this->functionData['image_listing'][$count_3db48c41ef4cfc78d5655d490ae69b3b]['album'] = $album;
$this->functionData['image_listing'][$count_3db48c41ef4cfc78d5655d490ae69b3b]['category'] = $category;
$this->functionData['image_listing'][$count_3db48c41ef4cfc78d5655d490ae69b3b]['sortData'] = $sortData;
$this->functionData['image_listing'][$count_3db48c41ef4cfc78d5655d490ae69b3b]['canChangeStyle'] = $canChangeStyle;
$this->functionData['image_listing'][$count_3db48c41ef4cfc78d5655d490ae69b3b]['viewStyle'] = $viewStyle;
}
$IPBHTML .= "<div class='maintitle ipsFilterbar'>
	" . (($canChangeStyle) ? ("<ul class='ipsList_inline right'>
			<!--<li>{$this->lang->words['show_as']}</li>-->
			<li " . (($viewStyle == 'thumbs' || !$viewStyle) ? ("class='active'") : ("")) . ">
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;sort_key={$this->request['sort_key']}&amp;sort_order={$this->request['sort_order']}&amp;view_style=thumbs", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'><img src='{$this->settings['img_url']}/gallery/icon_thumbs.png' alt='' /> &nbsp;&nbsp;{$this->lang->words['show_as_thumbs']}</a>
			</li>
			<li " . (($viewStyle == 'large') ? ("class='active'") : ("")) . ">
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;sort_key={$this->request['sort_key']}&amp;sort_order={$this->request['sort_order']}&amp;view_style=large", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'><img src='{$this->settings['img_url']}/gallery/icon_large.png' alt='' /> &nbsp;&nbsp;{$this->lang->words['show_as_large']}</a>
			</li>
		</ul>") : ("")) . "
	<div class='filterBarPrefix'>{$this->lang->words['sortby_prefix']}</div>
	<ul class='ipsList_inline left'>
		<li " . (($this->request['sort_key'] == 'idate' || $this->request['sort_key'] == 'image_date' || (!$this->request['sort_key'] AND $sortData['sort_key'] == 'image_date')) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;sort_key=idate&amp;sort_order=" . (($this->request['sort_order']) ? ("{$this->request['sort_order']}") : ("" . (($sortData['sort_dir']) ? ("{$sortData['sort_dir']}") : ("asc")) . "")) . "", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['filter_most_recent']}</a>
		</li>
		<li " . (($this->request['sort_key'] == 'views' || $this->request['sort_key'] == 'image_views' || (!$this->request['sort_key'] AND $sortData['sort_key'] == 'image_views')) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;sort_key=views&amp;sort_order=" . (($this->request['sort_order']) ? ("{$this->request['sort_order']}") : ("" . (($sortData['sort_dir']) ? ("{$sortData['sort_dir']}") : ("asc")) . "")) . "", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['filter_most_views']}</a>
		</li>
		<li " . (($this->request['sort_key'] == 'rating' || $this->request['sort_key'] == 'image_rating' || (!$this->request['sort_key'] AND $sortData['sort_key'] == 'image_rating')) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;sort_key=rating&amp;sort_order=" . (($this->request['sort_order']) ? ("{$this->request['sort_order']}") : ("" . (($sortData['sort_dir']) ? ("{$sortData['sort_dir']}") : ("asc")) . "")) . "", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['filter_highest_rated']}</a>
		</li>
		" . (($album['album_id'] AND $album['album_allow_comments']) ? ("<li " . (($this->request['sort_key'] == 'comments' || $this->request['sort_key'] == 'image_comments' || (!$this->request['sort_key'] AND $sortData['sort_key'] == 'image_comments')) ? ("class='active'") : ("")) . ">
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;sort_key=comments&amp;sort_order=" . (($this->request['sort_order']) ? ("{$this->request['sort_order']}") : ("" . (($sortData['sort_dir']) ? ("{$sortData['sort_dir']}") : ("asc")) . "")) . "", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['filter_most_comments']}</a>
			</li>") : ("" . ((!$album['album_id'] AND $category['category_allow_comments']) ? ("<li " . (($this->request['sort_key'] == 'comments' || $this->request['sort_key'] == 'image_comments' || (!$this->request['sort_key'] AND $sortData['sort_key'] == 'image_comments')) ? ("class='active'") : ("")) . ">
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;sort_key=comments&amp;sort_order=" . (($this->request['sort_order']) ? ("{$this->request['sort_order']}") : ("" . (($sortData['sort_dir']) ? ("{$sortData['sort_dir']}") : ("asc")) . "")) . "", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['filter_most_comments']}</a>
				</li>") : ("")) . "")) . "
		<li " . (($this->request['sort_key'] == 'caption' || $this->request['sort_key'] == 'image_caption' || (!$this->request['sort_key'] AND $sortData['sort_key'] == 'image_caption')) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;sort_key=caption&amp;sort_order=" . (($this->request['sort_order']) ? ("{$this->request['sort_order']}") : ("" . (($sortData['sort_dir']) ? ("{$sortData['sort_dir']}") : ("asc")) . "")) . "", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['filter_by_caption']}</a>
		</li>
	</ul>
	<div class='filterBarPrefix second'>{$this->lang->words['sortorder_prefix']}</div>
	<ul class='ipsList_inline'>
		<li " . ((strtolower($this->request['sort_order']) == 'asc' || (!$this->request['sort_order'] AND ( strtolower($sortData['sort_dir']) == 'asc' OR !$sortData['sort_dir'] ) )) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;sort_key=" . (($this->request['sort_key']) ? ("{$this->request['sort_key']}") : ("{$sortData['sort_key']}")) . "&amp;sort_order=asc", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['dir_sort_az']}</a>
		</li>
		<li " . ((strtolower($this->request['sort_order']) == 'desc' || (!$this->request['sort_order'] AND strtolower($sortData['sort_dir']) == 'desc')) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sortData['url']}&amp;sort_key=" . (($this->request['sort_key']) ? ("{$this->request['sort_key']}") : ("{$sortData['sort_key']}")) . "&amp;sort_order=desc", "public",'' ), "{$sortData['title']}", "{$sortData['template']}" ) . "'>{$this->lang->words['dir_sort_za']}</a>
		</li>
	</ul>
</div>
<div class='ipsBox gallery_box'>
	" . ((is_array($images) && count($images)) ? ("" . ((!$canChangeStyle || ($canChangeStyle && $viewStyle != 'large')) ? ("
			<ul class='ipsList_inline ipsList_reset'>
				".$this->__f__a73e6a4d71e537e4c8b45abb5bb00c89($images,$album,$category,$sortData,$canChangeStyle,$viewStyle)."			</ul>
		") : ("
			".$this->__f__22be49eeecd9535405c2e31f182f7836($images,$album,$category,$sortData,$canChangeStyle,$viewStyle)."		")) . "") : ("
		<div class='no_messages'>
			{$this->lang->words['category_no_images']}
		</div>
	")) . "
</div>
<br />
" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_global'), 'listingLightbox' ) ? $this->registry->getClass('output')->getTemplate('gallery_global')->listingLightbox() : '' ) . "
" . ((($album['album_id'] AND $album['_canModerate']) OR (!$album['album_id'] AND $this->registry->gallery->helper('categories')->checkIsModerator( $category['category_id'] ))) ? ("
	" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_home'), 'inlineAlbumModeration' ) ? $this->registry->getClass('output')->getTemplate('gallery_home')->inlineAlbumModeration() : '' ) . "
") : ("")) . "";
return $IPBHTML;
}


function __f__a73e6a4d71e537e4c8b45abb5bb00c89($images, $album, $category, $sortData=array(), $canChangeStyle = false, $viewStyle = false)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $images as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					<li class='gallery_image " . (($data['image_approved'] != 1) ? ("moderated") : ("")) . "'> 
						" . (($album['_canModerate'] OR $category['_canModerate']) ? ("<input type=\"checkbox\" name=\"modBox_{$data['image_id']}\" id=\"modBox_{$data['image_id']}\" value=\"1\" class=\"albumModBox\" />") : ("")) . "
						{$data['thumb']}
						<ul class='ipsList_inline gallery_item_info'>
							" . ((!$data['_isRead']) ? ("
								<li class='left'><img src='{$this->settings['img_url']}/t_unread.png' alt='' data-tooltip='{$this->lang->words['gallery_image_unread']}' /></li>
							") : ("")) . "
							" . (($data['image_approved'] != 1) ? ("<li class='left'><img src='{$this->settings['img_url']}/gallery/icon_moderated.png' alt='' data-tooltip='" . (($data['image_approved'] === -1) ? ("{$this->lang->words['moderated_img_hidden']}") : ("{$this->lang->words['moderated_img_unapproved']}")) . "' /></li>") : ("")) . "
							" . (($data['image_pinned']) ? ("
								<li class='left'><img src='{$this->settings['img_url']}/gallery/icon_pinned.png' alt='' /></li>
							") : ("")) . "
							<li " . ((!$data['image_views']) ? ("class='faded'") : ("")) . "><img src='{$this->settings['img_url']}/gallery/icon_view.png' alt='' /> {$data['image_views']}</li>
							<li " . ((!$data['image_comments']) ? ("class='faded'") : ("")) . "><img src='{$this->settings['img_url']}/gallery/icon_comments.png' alt='' /> {$data['image_comments']}</li>
						</ul>
					</li>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__22be49eeecd9535405c2e31f182f7836($images, $album, $category, $sortData=array(), $canChangeStyle = false, $viewStyle = false)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $images as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<div class='gallery_image large_image " . (($data['image_approved'] != 1) ? ("moderated") : ("")) . "'>
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;image={$data['image_id']}", "public",'' ), "{$data['image_caption_seo']}", "viewimage" ) . "' title='{$data['image_title']}'>{$data['mediumThumb']}</a>
					<div class='gallery_image_info'>
						<ul class='gallery_item_info right'>
							" . ((!$data['_isRead']) ? ("
								<li class='left'><img src='{$this->settings['img_url']}/t_unread.png' alt='' data-tooltip='{$this->lang->words['gallery_image_unread']}' /></li>
							") : ("")) . "
							" . (($data['image_approved'] != 1) ? ("<li class='left'><img src='{$this->settings['img_url']}/gallery/icon_moderated.png' alt='' data-tooltip='" . (($data['image_approved'] === -1) ? ("{$this->lang->words['moderated_img_hidden']}") : ("{$this->lang->words['moderated_img_unapproved']}")) . "' />") : ("")) . "
							" . (($data['image_pinned']) ? ("
								<li class='left'><img src='{$this->settings['img_url']}/gallery/icon_pinned.png' alt='' /></li>
							") : ("")) . "
							<li " . ((!$data['image_views']) ? ("class='faded'") : ("")) . "><img src='{$this->settings['img_url']}/gallery/icon_view.png' alt='' /> {$data['image_views']}</li>
							<li " . ((!$data['image_comments']) ? ("class='faded'") : ("")) . "><img src='{$this->settings['img_url']}/gallery/icon_comments.png' alt='' /> {$data['image_comments']}</li>
						</ul>
						<h2 class='ipsType_subtitle'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;image={$data['image_id']}", "public",'' ), "{$data['image_caption_seo']}", "viewimage" ) . "' title='{$data['image_title']}'>{$data['image_caption']}</a></h2>
						<div class='desc'>" . IPSText::truncate( strip_tags( IPSText::getTextClass('bbcode')->stripAllTags( $data['image_description'] ) ), 70 ) . "</div>
					</div>
				</div>
				<br />
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- inlineAlbumModeration --*/
function inlineAlbumModeration() {
$IPBHTML = "";

// Have to do it this way so we don't have whitespace when injecting into the js template, which will cause a js error
	$options	= '';
	$_images	= $this->registry->gallery->helper('categories')->fetchImageCategories();
	foreach( $this->registry->gallery->helper('categories')->catJumpList( false, 'post', array(), $this->lang->words['or_select_category'] ) as $cat )
	{
		$disabled	= '';
		if( $cat[0] AND !in_array( $cat[0], $_images ) )
		{
			$disabled	= " disabled='disabled'";
		}
		$options .= "<option value='{$cat[0]}'" . $disabled . ">{$cat[1]}</option>";
	}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("gallery_albumchooser", "0" ) . "
<script type='text/javascript'>
	albumSelectorUpdate = '{\"field\": \"albumModBox_moveTo\",\"div\": \"asDiv\"}';
	ipb.templates['album_moderation'] = new Template(\"<div id='album_moderate_box' class='ipsFloatingAction' style='display: none'><form id='theForm' name='theForm'><span class='desc'>{$this->lang->words['album_modaction_count']} </span><select name='modOptions' id='albumModAction' class='input_select'><option value='approve'>{$this->lang->words['mod_img_approve']}</option><option value='hide'>{$this->lang->words['mod_img_unapprove']}</option><option value='delete'>{$this->lang->words['mod_img_delete']}</option><option value='move'>{$this->lang->words['mod_img_move']}</option></select>&nbsp;&nbsp;<input type='button' class='input_submit' id='submitModAction' value='{$this->lang->words['jmp_go']}' /><div id='albumModBox_move' class='desc ipsPad_half short' style='display:none'></div><div class='desc ipsPad_half short'><input type='checkbox' name='albumModSelectAll' id='albumModSelectAll' value='1' #{checked} /> <label for='albumModSelectAll'>{$this->lang->words['mod_select_all']}</label></div></form></div>\");
	ipb.templates['album_img_moveto'] = new Template(\"<input type='radio' name='movetoAlbum' id='movetoAlbum' checked='checked' value='1' /> {$this->lang->words['album_modaction_moveto']}: <input type='hidden' id='albumModBox_moveTo' value=0 /><div style='display:none' class='albumSelected' id='asDiv'></div><a href='#' class='ipsButton_secondary' data-album-selector-auto-update='\" + albumSelectorUpdate + \"' data-album-selector='type=moveImages&moderate=1&album_id=#{album_id}'>{$this->lang->words['as_select_album']}</a><br /><br /><input type='radio' name='movetoAlbum' id='movetoAlbum' value='2' /> {$this->lang->words['album_modaction_moveto']}: <select name='movetoCategory_id' id='movetoCategory_id'>{$options}</select>\");
</script>";
return $IPBHTML;
}

/* -- member_listing --*/
function member_listing($albums, $category, $sortData=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_home', $this->_funcHooks['member_listing'] ) )
{
$count_c64f2092deddcab96bce951b1e1822a0 = is_array($this->functionData['member_listing']) ? count($this->functionData['member_listing']) : 0;
$this->functionData['member_listing'][$count_c64f2092deddcab96bce951b1e1822a0]['albums'] = $albums;
$this->functionData['member_listing'][$count_c64f2092deddcab96bce951b1e1822a0]['category'] = $category;
$this->functionData['member_listing'][$count_c64f2092deddcab96bce951b1e1822a0]['sortData'] = $sortData;
}

if ( ! isset( $this->registry->templateStriping['browseRow'] ) ) {
$this->registry->templateStriping['browseRow'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "<div class='maintitle ipsFilterbar'>
	{$this->lang->words['gallery_members_heading']}
</div>
<div class='ipsBox'>
	<div class='ipsBox_container ipsPad'>
		" . ((!count($albums)) ? ("
			<div class='no_messages'>
				{$this->lang->words['members_none_to_see']}
			</div>
		") : ("
			<table class='ipb_table gallery_members'>
								".$this->__f__efb4e2f1528dd3b16fd3518cd576d1dd($albums,$category,$sortData)."			</table>
		")) . "
	</div>
</div>
<br />";
return $IPBHTML;
}


function __f__5f129cdb4d625235bfb010b04d40845d($albums, $category, $sortData=array(),$data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $data['_images'] as $_image )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
									<li>" . $this->registry->getClass('gallery')->inlineResize( $_image['thumb'],'thumb_small','','' ) . "</li>
								
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__efb4e2f1528dd3b16fd3518cd576d1dd($albums, $category, $sortData=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $albums as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					<tr class='" .  IPSLib::next( $this->registry->templateStriping["browseRow"] ) . "'>
						<td class='col_c_icon'>
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;user={$data['member_id']}", "public",'' ), "{$data['members_seo_name']}", "useralbum" ) . "' title='{$this->lang->words['view_all_albums']}' class='ipsUserPhotoLink'><div class='galattach cover_img_75'><div class='galmemberwrapper'><img src='{$data['pp_main_photo']}' alt=\"" . sprintf($this->lang->words['users_photo'],$data['members_display_name']) . "\" style='max-width: 75px; max-height: 75px;' /></div></div></a>
						</td>
						<td class='col_c_forum'>
							<strong>
								<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;user={$data['member_id']}", "public",'' ), "{$data['members_seo_name']}", "useralbum" ) . "'>{$data['members_display_name']}</a>
							</strong>
							" . ((count($data['_images'])) ? ("
								<br /><br />
								<ul class='ipsList_inline'>
								".$this->__f__5f129cdb4d625235bfb010b04d40845d($albums,$category,$sortData,$data)."								</ul>
							") : ("")) . "
						</td>
						<td class='col_c_post desc'>
							<strong>{$data['_totalImages']}</strong> {$this->lang->words['images']}<br />
							" . (($data['_latestImage']) ? ("
								<br />
								{$this->lang->words['last_upload']}: " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($data['_latestImage'],"DATE", 0)) . "
							") : ("")) . "
						</td>
					</tr>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>