<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 7               */
/* CACHE FILE: Generated: Fri, 23 Sep 2016 17:24:01 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_reviews_extra_7 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();


}

/* -- all_questions_page --*/
function all_questions_page($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['linkbar']}
" . (( $data['rows'] != "") ? ("<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr class='header'><th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['review_tip']}</th><th scope='col' style=\"width:35%\">{$this->lang->words['faqs_question_tip']}</th><th scope='col' style=\"width:20%;text-align:center\">{$this->lang->words['faqs_title']}</th><th scope='col' style=\"width:25%;text-align:center\">{$this->lang->words['faqs_time']}</th><th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['faqs_answers']}</th></tr>
{$data['rows']}
</table>
</div>
</div>
<br />
" . (($data['links'] != "") ? ("
<div class='topic_controls'>
{$data['links']}
</div>
") : ("")) . "") : ("
<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row1' align='center'>{$this->lang->words['no_faqs_3']}</td></tr>
</table>
</div>
</div>
<br />
")) . "";
return $IPBHTML;
}

/* -- all_questions_page_row --*/
function all_questions_page_row($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<tr class='{$data['rowclass']}'>
<td align='center'>{$data['type']}</td>
<td class='altrow'>
<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=faq&amp;do=questions&amp;id={$data['id']}", "public",'' ), "{$data['qname']}", "showrevanswers" ) . "'>{$data['question']}</a></td>
<td align='center'>
<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=products&amp;do=products&amp;id={$data['cid']}", "public",'' ), "{$data['fname']}", "showrevproduct" ) . "'>{$data['cname']}</a></td>
<td class='altrow' align='center'>{$data['date']}</td>
<td align='center'>{$data['answers']}</td>
</tr>";
return $IPBHTML;
}

/* -- answer_report_page --*/
function answer_report_page($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['links']}
<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=report&amp;do=do_report_answer&amp;id={$data['id']}'>
<h3 class='maintitle'>{$this->lang->words['reporting_answer']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container ipsPad'>
<ul class='ipsForm ipsForm_horizontal'>
<li class='ipsField'>
<p class='ipsField_content'>
<span class='ipsForm_required ipsType_smaller'>{$this->lang->words['reviews_required']}</span>
</p>
</li>
<li class='ipsField'>
<label class='ipsField_title'>{$this->lang->words['reporting_answer_text']}<span class='ipsForm required'>{$this->lang->words['reviews_asterisk']}</span></label>
<div class='ipsField_content'><textarea name='message_from_reporter' rows='10'></textarea><br /><span class='desc'>{$this->lang->words['bbcode_enabled']}</span>
</div>
</li>
</ul>
</div>
</div>
<fieldset class='submit'>
<input type='submit' value='{$this->lang->words['reporting_answer']}' tabindex=\"0\" class=\"input_submit\" />
</fieldset>
</form>
<br />";
return $IPBHTML;
}

/* -- faq_add_question --*/
function faq_add_question($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['links']}
" . (( $data['type'] == '2') ? ("
<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=products&amp;section=faq&amp;do=do_add_question&amp;id={$data['id']}'>
<input type='hidden' name='question' value='{$data['question']}' />
<h3 class='maintitle'>{$this->lang->words['faqs_ask_4']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container ipsPad'>
<ul class='ipsForm ipsForm_horizontal'>
<li class='ipsField'>
<label class='ipsField_title'>{$this->lang->words['add_msg_header_2']}</label>
<div class='ipsField_content'>{$data['category']}<span class='desc'></span>
</div>
</li>
<li class='ipsField'>
<label class='ipsField_title'>{$this->lang->words['faqs_question_4']}</label>
<div class='ipsField_content'>{$data['question']}<span class='desc'></span>
</div>
</li>
<li class='ipsField'>
<label class='ipsField_title'>{$this->lang->words['faqs_question_5']}</label>
<div class='ipsField_content'><textarea name='answer' rows='5'></textarea><span class='desc'></span>
</div>
</li>
</ul>
</div>
</div>
<fieldset class='submit'>
<strong>{$this->lang->words['faqs_warning_msg_2']}</strong><br />
<input type='submit' value='{$this->lang->words['submit']}' tabindex=\"0\" class=\"input_submit\" />
</fieldset>
</form>
<br />
") : ("
<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=products&amp;section=faq&amp;do=do_add_question&amp;id={$data['id']}'>
<input type='hidden' name='question' value='{$data['question']}' />
<h3 class='maintitle'>{$this->lang->words['faqs_ask_3']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container ipsPad'>
<ul class='ipsForm ipsForm_horizontal'>
<li class='ipsField'>
<label class='ipsField_title'>{$this->lang->words['add_msg_header_2']}</label>
<div class='ipsField_content'>{$data['category']}<span class='desc'></span>
</div>
</li>
<li class='ipsField'>
<label class='ipsField_title'>{$this->lang->words['faqs_question_2']}</label>
<div class='ipsField_content'>{$data['question']}<span class='desc'></span>
</div>
</li>
</ul>
</div>
</div>
<fieldset class='submit'>
<strong>{$this->lang->words['faqs_warning_msg']}</strong><br /><br />
<input type='submit' value='{$this->lang->words['submit']}' tabindex=\"0\" class=\"input_submit\" />
</fieldset>
</form>
<br />
")) . "";
return $IPBHTML;
}

/* -- faq_page --*/
function faq_page($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['linkbar']}
" . (( $data['extra'] == '1') ? ("" . (( $data['rows'] != "") ? ("<form action='{$this->settings['base_url']}app=reviews&amp;module=products&amp;section=faq&amp;do=add_question&amp;id={$data['id']}' method='post'>
<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr class='header'><th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['review_tip']}</th><th scope='col' style=\"width:35%\">{$this->lang->words['faqs_question_tip']}</th><th scope='col' style=\"width:20%;text-align:center\">{$this->lang->words['faqs_title']}</th><th scope='col' style=\"width:25%;text-align:center\">{$this->lang->words['faqs_time']}</th><th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['faqs_answers']}</th></tr>
{$data['rows']}
<tr class='unread'><td class='altrow' colspan='5' align='right'>
<select name='type' class='codebuttons'>
<option value='1'>{$this->lang->words['faqs_ask_2']}</option>
" . (( $data['extraa'] == '1') ? ("
<option value='2'>{$this->lang->words['faqs_ask_4']}</option>
") : ("")) . "
</select>&nbsp;
<input type='text' name='question' size='30' maxlength='150' onfocus=\"this.value=''\" value=\"{$this->lang->words['enter_search_faq']}\" />
<input type='submit' value='{$this->lang->words['faqs_ask']}' class='input_submit' />
</td></tr>
</table>
</div>
</div>
</form>
<br />
" . (($data['links'] != "") ? ("
<div class='topic_controls'>
{$data['links']}
</div>
") : ("")) . "") : ("<form action='{$this->settings['base_url']}app=reviews&amp;module=products&amp;section=faq&amp;do=add_question&amp;id={$data['id']}' method='post'>
<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row1' align='center'>{$this->lang->words['no_faqs']}</td></tr>
<tr class='unread'><td class='altrow' align='right'>
<select name='type' class='codebuttons'>
<option value='1'>{$this->lang->words['faqs_ask_2']}</option>
" . (( $data['extraa'] == '1') ? ("
<option value='2'>{$this->lang->words['faqs_ask_4']}</option>
") : ("")) . "
</select>&nbsp;
<input type='text' name='question' size='30' maxlength='150' onfocus=\"this.value=''\" value=\"{$this->lang->words['enter_search_faq']}\" />
<input type='submit' value='{$this->lang->words['faqs_ask']}' class='input_submit' />
</td></tr>
</table>
</div>
</div>
</form>
<br />")) . "") : ("" . (( $data['rows'] != "") ? ("<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr class='header'><th scope='col' style=\"width:30%\">{$this->lang->words['faqs_time']}</th><th scope='col' style=\"width:60%\">{$this->lang->words['faqs_question']}</th><th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['faqs_answers']}</th></tr>
{$data['rows']}
</table>
</div>
</div>
<br />
" . (($data['links'] != "") ? ("
<div class='topic_controls'>
{$data['links']}
</div>
") : ("")) . "") : ("
<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row1' align='center'>{$this->lang->words['no_faqs']}</td></tr>
</table>
</div>
</div>
<br />
")) . "")) . "";
return $IPBHTML;
}

/* -- faq_page_row --*/
function faq_page_row($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<tr class='{$data['rowclass']}'>
<td align='center'>{$data['type']}</td>
<td class='altrow'>
<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=faq&amp;do=questions&amp;id={$data['id']}", "public",'' ), "{$data['qname']}", "showrevanswers" ) . "'>{$data['question']}</a></td>
<td align='center'>
<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=products&amp;do=products&amp;id={$data['cid']}", "public",'' ), "{$data['fname']}", "showrevproduct" ) . "'>{$data['cname']}</a></td>
<td class='altrow' align='center'>{$data['date']}</td>
<td align='center'>{$data['answers']}</td>
</tr>";
return $IPBHTML;
}

/* -- faq_questions_page --*/
function faq_questions_page($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['linkbar']}
" . (( $data['extra'] == '1') ? ("<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=products&amp;section=faq&amp;do=do_add_answer&amp;id={$data['id']}'>
<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row2' colspan='3'><strong>" . (( $data['members_display_name'] == "") ? ("
{$data['mem_name']}
") : ("
<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=authors&amp;section=profile&amp;do=profile&amp;id={$data['mid']}", "public",'' ), "{$data['members_seo_name']}", "showrevuser" ) . "'>{$data['author']}</a>")) . "
({$data['time']}): {$data['question']}</strong>
" . (( $data['extra2'] == '1') ? ("
<div style=\"float: right;\">(<a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=report&amp;do=report_question&amp;id={$data['id']}'>{$this->lang->words['faqs_report_question']}</a>
 / <a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=delete_question&amp;id={$data['id']}'>{$this->lang->words['faqs_delete']}</a>)
") : ("
<div style=\"float: right;\">(<a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=report&amp;do=report_question&amp;id={$data['id']}'>{$this->lang->words['faqs_report_question']}</a>)
")) . "
</div>
</td></tr>
" . (( $data['rows'] != "") ? ("
<tr class='header'><th scope='col' style=\"width:1%;text-align:center\">{$this->lang->words['answers_rank']}</th><th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['answers_author']}</th><th scope='col' style=\"width:89%\">{$this->lang->words['answers_answer']}</th></tr>
{$data['rows']}
") : ("
<tr class='row1'><td class='altrow' colspan='3' align='center'>{$this->lang->words['no_faqs_2']}</td></tr>
")) . "
<tr class='unread'><td class='altrow' colspan='3' align='right'>{$this->lang->words['faqs_answer']}<textarea name='answer' rows='1'></textarea>
&nbsp;<input type='submit' value='{$this->lang->words['faqs_answer_2']}' class='input_submit' />
</td></tr>
</table>
</div>
</div>
</form>
<br />
" . (($data['links'] != "") ? ("
<div class='topic_controls'>
{$data['links']}
</div>
") : ("")) . "") : ("<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row2' colspan='3'><strong>" . (( $data['members_display_name'] == "") ? ("
{$data['mem_name']}
") : ("
<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=authors&amp;section=profile&amp;do=profile&amp;id={$data['mid']}", "public",'' ), "{$data['members_seo_name']}", "showrevuser" ) . "'>{$data['author']}</a>")) . "
({$data['time']}): {$data['question']}</strong>
" . (( $data['extra2'] == '1') ? ("
<div style=\"float: right;\">(<a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=report&amp;do=report_question&amp;id={$data['id']}'>{$this->lang->words['faqs_report_question']}</a>
 / <a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=delete_question&amp;id={$data['id']}'>{$this->lang->words['faqs_delete']}</a>)
</div>
") : ("" . (( $data['extraR'] == '1') ? ("
<div style=\"float: right;\">(<a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=report&amp;do=report_question&amp;id={$data['id']}'>{$this->lang->words['faqs_report_question']}</a>)
</div>
") : ("")) . "")) . "
</td></tr>
" . (( $data['rows'] != "") ? ("
<tr class='header'><th scope='col' style=\"width:1%;text-align:center\">{$this->lang->words['answers_rank']}</th><th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['answers_author']}</th><th scope='col' style=\"width:89%\">{$this->lang->words['answers_answer']}</th></tr>
{$data['rows']}
") : ("
<tr class='row1'><td class='altrow' colspan='3' align='center'>{$this->lang->words['no_faqs']}</td></tr>
")) . "
</table>
</div>
</div>
<br />
" . (($data['links'] != "") ? ("
<div class='topic_controls'>
{$data['links']}
</div>
") : ("")) . "")) . "";
return $IPBHTML;
}

/* -- faq_questions_page_row --*/
function faq_questions_page_row($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<tr class='{$data['rowclass']}'>
<td align='center'>{$data['rank']}</td>
<td class='altrow' align='center'>
" . (( $data['members_display_name'] == "") ? ("
{$data['mem_name']}
") : ("
<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=authors&amp;section=profile&amp;do=profile&amp;id={$data['mid']}", "public",'' ), "{$data['members_seo_name']}", "showrevuser" ) . "'>{$data['author']}</a>
")) . "</td>
<td>{$data['answer']}
" . (( $data['extra'] == '1' && $data['extra2'] == '1') ? ("
<div style=\"float: right;\">
(<a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=report&amp;do=report_answer&amp;id={$data['id']}'>{$this->lang->words['faqs_report_answer']}</a> / <a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=delete_answer&amp;id={$data['id']}'>{$this->lang->words['faqs_delete']}</a>)
</div>
") : ("" . (( $data['extra'] == '1') ? ("
<div style=\"float: right;\">
(<a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=report&amp;do=report_answer&amp;id={$data['id']}'>{$this->lang->words['faqs_report_answer']}</a>)
</div>
") : ("" . (( $data['extra2'] == '1') ? ("
<div style=\"float: right;\">
(<a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=delete_answer&amp;id={$data['id']}'>{$this->lang->words['faqs_delete']}</a>)
</div>
") : ("")) . "")) . "")) . "
</td>
</tr>";
return $IPBHTML;
}

/* -- faq_remove_answer --*/
function faq_remove_answer($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['links']}
<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=do_delete_answer&amp;id={$data['id']}'>
<h3 class='maintitle'>{$this->lang->words['del_answer']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row2'><strong>{$this->lang->words['faqs_question_3']}{$data['answer']}</td></tr>
<tr><td class='row2'><strong>{$this->lang->words['del_answer_msg']}</strong></td></tr>
<tr class='row2'><td class='altrow' align='center'><input type='submit' value='{$this->lang->words['del_answer']}' tabindex=\"0\" class=\"input_submit\" /></td></tr>
</table>
</div>
</div>
</form><br />";
return $IPBHTML;
}

/* -- faq_remove_question --*/
function faq_remove_question($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['links']}
<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=do_delete_question&amp;id={$data['id']}'>
<h3 class='maintitle'>{$this->lang->words['del_question']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row2'><strong>{$this->lang->words['faqs_question_2']}{$data['question']}</td></tr>
<tr><td class='row2'><strong>{$this->lang->words['del_question_msg']}</strong></td></tr>
<tr class='row2'><td class='altrow' align='center'><input type='submit' value='{$this->lang->words['del_question']}' tabindex=\"0\" class=\"input_submit\" /></td></tr>
</table>
</div>
</div>
</form><br />";
return $IPBHTML;
}

/* -- question_report_page --*/
function question_report_page($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['links']}
<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=report&amp;do=do_report_question&amp;id={$data['id']}'>
<h3 class='maintitle'>{$this->lang->words['reporting_question']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container ipsPad'>
<ul class='ipsForm ipsForm_horizontal'>
<li class='ipsField'>
<p class='ipsField_content'>
<span class='ipsForm_required ipsType_smaller'>{$this->lang->words['reviews_required']}</span>
</p>
</li>
<li class='ipsField'>
<label class='ipsField_title'>{$this->lang->words['reporting_question_text']}<span class='ipsForm required'>{$this->lang->words['reviews_asterisk']}</span></label>
<div class='ipsField_content'><textarea name='message_from_reporter' rows='10'></textarea><br /><span class='desc'>{$this->lang->words['bbcode_enabled']}</span>
</div>
</li>
</ul>
</div>
</div>
<fieldset class='submit'>
<input type='submit' value='{$this->lang->words['reporting_question']}' tabindex=\"0\" class=\"input_submit\" />
</fieldset>
</form>
<br />";
return $IPBHTML;
}

/* -- ratings_category_image --*/
function ratings_category_image($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<a href=\"{$data['cimg']}\"><img src=\"{$data['cimg']}\" border=\"0\" alt=\"{$data['imgdesc']}\" title=\"{$data['imgdesc']}\" width=\"120\" /></a>";
return $IPBHTML;
}

/* -- ratings_page --*/
function ratings_page($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['linkbar']}
" . (( $data['rows'] != "") ? ("<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=extra&amp;section=ratings&amp;do=ratings&amp;id={$data['root']}", "public",'' ), "{$data['fname']}", "showrevratingstwo" ) . "' method='post'>
<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr class='header'><th scope='col' colspan='2'>{$this->lang->words['sort_name']}</th><th scope='col' style='text-align:center'>{$this->lang->words['header_reviews']}</th><th scope='col' style='text-align:center'>{$this->lang->words['sort_rating']}</th><th scope='col' style='text-align:center'>{$this->lang->words['show_special']}</th><th scope='col' style='text-align:center'>{$this->lang->words['add_review_to_list']}</th></tr>
{$data['rows']}
<tr class='unread'><td class='altrow' colspan='6'>
<div style=\"float: left;\">&nbsp;{$data['pagelink']}</div><div style=\"text-align:right;\">
{$this->lang->words['sort_titles_by']}&nbsp;<select name='sort'>{$data['sortrow']}</select>&nbsp;&nbsp;
<select name='order'><option value='ASC'{$data['select_asc']}>{$this->lang->words['asc']}</option><option value='DESC'{$data['select_desc']}>{$this->lang->words['desc']}</option></select>&nbsp;
<input type='submit' value='{$this->lang->words['sort']}' />
</div></td></tr>
</table>
</div>
</div>
</form>
<br />
" . (($data['links'] != "") ? ("
<div class='topic_controls'>
{$data['links']}
</div>
") : ("")) . "") : ("
<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row1' colspan='2' align='center'>{$this->lang->words['no_cat_ratings']}</td></tr>
</table>
</div>
</div>
<br />
")) . "";
return $IPBHTML;
}

/* -- ratings_page_row --*/
function ratings_page_row($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<tr class='{$data['rowclass']}'>
" . (( $data['image'] != "") ? ("
<td class='altrow' style='width:1%'>{$data['image']}</td>
<td class='altrow' style='width:29%'>
") : ("
<td class='altrow' colspan='2' style='width:30%'>
")) . "
<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=products&amp;do=products&amp;id={$data['cid']}", "public",'' ), "{$data['fname']}", "showrevproduct" ) . "'>{$data['cname']}</a></strong><br />{$this->lang->words['sort_time']}: {$data['latest']}</td>
<td align='center'><strong>{$data['count']}</strong></td>
<td class='altrow' align='center'><strong>{$data['average']}</strong></td>
<td align='center'><strong>{$data['special']}</strong></td>
<td class='altrow' align='center'><strong>
{$data['favorite']}
" . (( $data['wishes'] != "") ? ("
{$data['wishes']}
") : ("")) . "
" . (( $data['owned'] != "") ? ("
{$data['owned']}
") : ("")) . "
" . (( $data['tracky'] != "") ? ("
{$data['tracky']}
") : ("")) . "
</strong></td>
</tr>";
return $IPBHTML;
}

/* -- request_bar --*/
function request_bar($extra="") {
$IPBHTML = "";
$IPBHTML .= "<li>
" . (( $extra == "1") ? ("
<a href='{$this->settings['base_url']}app=reviews&amp;module=products&amp;section=requests&amp;do=add_request'>{$this->lang->words['add_request']}</a>
") : ("
<li class='disabled'><span>{$this->lang->words['no_request_addy']}</span></li>
")) . "
</li>";
return $IPBHTML;
}

/* -- request_cancel_page --*/
function request_cancel_page($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['links']}
<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=products&amp;section=requests&amp;do=do_cancel_request&amp;id={$data['id']}'>
<h3 class='maintitle'>{$this->lang->words['cancel_request']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row2'><strong>{$this->lang->words['cancel_request_msg']}</strong></td></tr>
<tr class='row2'><td class='altrow' align='center'><input type='submit' value='{$this->lang->words['cancel_request']}' tabindex=\"0\" class=\"input_submit\" /></td></tr>
</table>
</div>
</div>
</form><br />";
return $IPBHTML;
}

/* -- request_choose_cat --*/
function request_choose_cat($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['links']}
" . (( $data['header'] == '1') ? ("
<div class=\"ipsSteps clearfix\">
<ul>
<li class=\"ipsSteps_active\">
<strong class=\"ipsSteps_title\">{$this->lang->words['step_uno']}</strong>
<span class=\"ipsSteps_desc\">{$this->lang->words['step_uno_desc']}</span>
<span class=\"ipsSteps_arrow\">&nbsp;</span>
</li>
<li class=\"\">
<strong class=\"ipsSteps_title\">{$this->lang->words['step_dos']}</strong>
<span class=\"ipsSteps_desc\">{$this->lang->words['step_dos_desc']}</span>
<span class=\"ipsSteps_arrow\">&nbsp;</span>
</li>
<li class=\"\">
<strong class=\"ipsSteps_title\">{$this->lang->words['step_tres']}</strong>
<span class=\"ipsSteps_desc\">{$this->lang->words['step_tres_desc']}</span>
<span class=\"ipsSteps_arrow\">&nbsp;</span>
</li>
</ul>
</div>
") : ("
<div class=\"ipsSteps clearfix\">
<ul>
<li class=\"ipsSteps_done\">
<strong class=\"ipsSteps_title\">{$this->lang->words['step_uno']}</strong>
<span class=\"ipsSteps_desc\">{$this->lang->words['step_uno_desc']}</span>
<span class=\"ipsSteps_arrow\">&nbsp;</span>
</li>
<li class=\"ipsSteps_active\">
<strong class=\"ipsSteps_title\">{$this->lang->words['step_dos']}</strong>
<span class=\"ipsSteps_desc\">{$this->lang->words['step_dos_desc']}</span>
<span class=\"ipsSteps_arrow\">&nbsp;</span>
</li>
<li class=\"\">
<strong class=\"ipsSteps_title\">{$this->lang->words['step_tres']}</strong>
<span class=\"ipsSteps_desc\">{$this->lang->words['step_tres_desc']}</span>
<span class=\"ipsSteps_arrow\">&nbsp;</span>
</li>
</ul>
</div>
")) . "
<br />
<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=products&amp;section=requests&amp;do=add_request'>
<h3 class='maintitle'>{$this->lang->words['choose_cat']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container ipsPad'>
<ul class='ipsForm ipsForm_horizontal'>
<li class='ipsField ipsField_select'>
<label class='ipsField_title'>{$data['lang1']}</label>
<div class='ipsField_content'>{$data['input']}
" . (( $data['lang2'] != '') ? ("
<br /><span class='desc'>{$data['lang2']}</span>
") : ("")) . "
</div>
</li>
</ul>
</div>
</div>
<fieldset class='submit'>
<input type='submit' value='{$this->lang->words['continue']}' tabindex=\"0\" class=\"input_submit\" />
</fieldset>
</form>
<br />";
return $IPBHTML;
}

/* -- request_delete_page --*/
function request_delete_page($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['links']}
<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=do_delete_request&amp;id={$data['id']}'>
<h3 class='maintitle'>{$this->lang->words['del_request']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row2'><strong>{$this->lang->words['del_request_msg']}</strong></td></tr>
<tr class='row2'><td class='altrow' align='center'><input type='submit' value='{$this->lang->words['del_request']}' tabindex=\"0\" class=\"input_submit\" /></td></tr>
</table>
</div>
</div>
</form><br />";
return $IPBHTML;
}

/* -- request_form --*/
function request_form($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['links']}
<div class=\"ipsSteps clearfix\">
<ul>
<li class=\"ipsSteps_done\">
<strong class=\"ipsSteps_title\">{$this->lang->words['step_uno']}</strong>
<span class=\"ipsSteps_desc\">{$this->lang->words['step_uno_desc']}</span>
<span class=\"ipsSteps_arrow\">&nbsp;</span>
</li>
<li class=\"ipsSteps_done\">
<strong class=\"ipsSteps_title\">{$this->lang->words['step_dos']}</strong>
<span class=\"ipsSteps_desc\">{$this->lang->words['step_dos_desc']}</span>
<span class=\"ipsSteps_arrow\">&nbsp;</span>
</li>
<li class=\"ipsSteps_active\">
<strong class=\"ipsSteps_title\">{$this->lang->words['step_tres']}</strong>
<span class=\"ipsSteps_desc\">{$this->lang->words['step_tres_desc']}</span>
<span class=\"ipsSteps_arrow\">&nbsp;</span>
</li>
</ul>
</div>
<br />
<form id='postingform' onsubmit='return ValidateForm()' action=\"{$this->settings['base_url']}app=reviews&amp;module=products&amp;section=requests&amp;do=do_add_request\" method=\"post\">
<input type='hidden' name='cid' value='{$data['cid']}' />
<input type='hidden' name='newcat' value='{$data['newcat']}' />
<input type='hidden' name='cparent' value='{$data['cparent']}' />
<input type='hidden' name='specialcat' value='{$data['specialcat']}' />
<h3 class='maintitle'>{$data['maintitle']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container ipsPad'>
<ul class='ipsForm ipsForm_horizontal'>
<li class='ipsField'>
<p class='ipsField_content'>
<span class='ipsForm_required ipsType_smaller'>{$this->lang->words['reviews_required']}</span>
</p>
</li>
<li class='ipsField'>
<label class='ipsField_title'>{$this->lang->words['request_category']}</label>
<div class='ipsField_content'>{$data['category']}<span class='desc'></span>
</div>
</li>
" . (( $this->settings['mr_use_points'] == '1') ? ("<li class='ipsField'>
<label class='ipsField_title'>{$this->lang->words['request_offer']}</label>
" . (( $data['point_add'] == '1') ? ("
<div class='ipsField_content'><input type='text' name='offer' size='20' maxlength='20' value='{$data['offer']}' /><br /><span class='desc'>{$this->lang->words['request_offer_desc']}</span>
</div>
") : ("
<div class='ipsField_content'>{$data['offer']}<span class='desc'></span>
</div>
")) . "
</li>") : ("")) . "
</li>
<li class='ipsField'>
<label class='ipsField_title'>{$this->lang->words['request_review_minimum']}</label>
<div class='ipsField_content'><input type='text' name='revmin' size='20' maxlength='20' value='{$data['revmin']}' /><br /><span class='desc'>{$this->lang->words['request_revmin_desc']}</span>
</div>
</li>
<li class='ipsField ipsField_select'>
<label class='ipsField_title'>{$this->lang->words['request_minimum']}<span class='ipsForm required'>{$this->lang->words['reviews_asterisk']}</span></label>
<div class='ipsField_content'><select name='minimum' class='codebuttons'>
<option value='0'>{$this->lang->words['request_minimum_0']}</option>
<option value='1'>{$this->lang->words['request_minimum_1']}</option>
<option value='2'>{$this->lang->words['request_minimum_2']}</option>
<option value='3'>{$this->lang->words['request_minimum_3']}</option>
<option value='4'>{$this->lang->words['request_minimum_4']}</option>
</select><br /><span class='desc'>{$this->lang->words['request_minimum_desc']}</span>
</div>
</li>
</ul>
</div>
</div>
<fieldset class='submit'>
<input type=\"submit\" value=\"Submit\" tabindex=\"0\" class=\"input_submit\" />
</fieldset>
</form>
<br />";
return $IPBHTML;
}

/* -- request_page --*/
function request_page($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['linkbar']}
<h3 class='maintitle'>{$data['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
" . (( $data['rows'] != "") ? ("
<tr class='header'><th scope='col' style=\"width:18%\">{$this->lang->words['request_title_date']}</th><th scope='col' style=\"width:15%;text-align:center\">{$this->lang->words['request_title_author']}</th><th scope='col' style=\"width:35%\">{$this->lang->words['request_title_category']}</th><th scope='col' style=\"width:10%;text-align:center\">{$this->lang->words['request_title_minimum']}</th><th scope='col' style=\"width:1%;text-align:center\">{$this->lang->words['request_title_revmin']}</th><th scope='col' style=\"width:1%;text-align:center\">{$this->lang->words['request_title_offer']}</th><th scope='col' style=\"width:20%\">{$this->lang->words['request_title_options']}</th></tr>
{$data['rows']}
") : ("
<tr><td class='row1' align='center'>{$this->lang->words['no_requests']}</td></tr>
")) . "
</table>
</div>
</div>
<br />
" . (($data['links'] != "") ? ("
<div class='topic_controls'>
{$data['links']}
</div>
") : ("")) . "";
return $IPBHTML;
}

/* -- request_page_row --*/
function request_page_row($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<tr class='{$data['rowclass']}'>
<td>{$data['date']}</td>
<td class='altrow' align='center'>
" . (( $data['members_display_name'] == "") ? ("
{$data['mem_name']}
") : ("
<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=authors&amp;section=profile&amp;do=profile&amp;id={$data['mid']}", "public",'' ), "{$data['members_seo_name']}", "showrevuser" ) . "'>{$data['author']}</a>")) . "</td>
<td>{$data['product']} ({$data['catty']})
" . (( $data['extra'] == '1') ? ("<br />
" . (( $data['extra3'] == '1' && $data['extra2'] == '1') ? ("
<a href='{$this->settings['base_url']}app=reviews&amp;module=products&amp;section=requests&amp;do=cancel_request&amp;id={$data['id']}'>{$this->lang->words['request_cancel']}</a> /
<a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=report&amp;do=report_request&amp;id={$data['id']}'>{$this->lang->words['report_request']}</a>
 / <a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=moderate&amp;do=delete_request&amp;id={$data['id']}'>{$this->lang->words['request_delete']}</a>
") : ("" . (( $data['extra3'] == '1') ? ("
<a href='{$this->settings['base_url']}app=reviews&amp;module=products&amp;section=requests&amp;do=cancel_request&amp;id={$data['id']}'>{$this->lang->words['request_cancel']}</a> /
<a href='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=report&amp;do=report_request&amp;id={$data['id']}'>{$this->lang->words['report_request']}</a>
") : ("")) . "")) . "") : ("")) . "
</td>
<td class='altrow' align='center'>{$data['minimum']}</td>
<td align='center'>{$data['revmin']}</td>
<td class='altrow' align='center'>{$data['offer']}</td>
<td>{$data['option']}</td>
</tr>";
return $IPBHTML;
}

/* -- request_report_page --*/
function request_report_page($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['links']}
<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=moderate&amp;section=report&amp;do=do_report_request&amp;id={$data['id']}'>
<h3 class='maintitle'>{$this->lang->words['reporting_request']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container ipsPad'>
<ul class='ipsForm ipsForm_horizontal'>
<li class='ipsField'>
<p class='ipsField_content'>
<span class='ipsForm_required ipsType_smaller'>{$this->lang->words['reviews_required']}</span>
</p>
</li>
<li class='ipsField'>
<label class='ipsField_title'>{$this->lang->words['reporting_request_text']}<span class='ipsForm required'>{$this->lang->words['reviews_asterisk']}</span></label>
<div class='ipsField_content'><textarea name='message_from_reporter' rows='10'></textarea><br /><span class='desc'>{$this->lang->words['bbcode_enabled']}</span>
</div>
</li>
</ul>
</div>
</div>
<fieldset class='submit'>
<input type='submit' value='{$this->lang->words['reporting_request']}' tabindex=\"0\" class=\"input_submit\" />
</fieldset>
</form>
<br />";
return $IPBHTML;
}

/* -- search_page --*/
function search_page($stuff=array(),$selected=array()) {
$IPBHTML = "";
$IPBHTML .= "{$stuff['linkbar']}
" . (($stuff['rows'] != '') ? ("<form method='post' action='{$this->settings['base_url']}app=reviews&amp;module=extra&amp;section=search&amp;do=search&amp;words={$stuff['words']}'>
<input type='hidden' name='SearchType' value='{$stuff['searchtype']}' />
<input type='hidden' name='SearchId' value='{$stuff['searchid']}' />
<h3 class='maintitle'>{$stuff['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr class='header'><th scope='col' style='text-align:center'>{$this->lang->words['review_category']}</th><th scope='col' style='text-align:center'>{$this->lang->words['review_parent']}</th><th scope='col' style='text-align:center'>{$this->lang->words['overallaveraged']}</th><th scope='col' style='text-align:center'>{$this->lang->words['header_reviews']}</th><th scope='col' style='text-align:center'>{$this->lang->words['last_review_added']}</th></tr>
{$stuff['rows']}
<tr class='unread'><td class='altrow' colspan='6' align='right'>
<select name='key' class='codebuttons'>
<option value='name'{$selected['name']}>{$this->lang->words['sort_name']}</option>
<option value='catname'{$selected['catname']}>{$this->lang->words['sort_catname']}</option>
<option value='reviews'{$selected['reviews']}>{$this->lang->words['sort_reviews']}</option>
<option value='rating'{$selected['rating']}>{$this->lang->words['sort_rating']}</option>
<option value='time'{$selected['time']}>{$this->lang->words['sort_time']}</option>
</select>&nbsp;
<select name='order' class='codebuttons'>
<option value='ASC'{$selected['ASC']}>{$this->lang->words['asc']}</option>
<option value='DESC'{$selected['DESC']}>{$this->lang->words['desc']}</option>
</select>&nbsp;
<input type='submit' value='{$this->lang->words['sort']}' class='input_submit' />&nbsp;</td></tr>
</table>
</div>
</div>
</form>
<br />
" . (($stuff['links'] != "") ? ("
<div class='topic_controls'>
{$stuff['links']}
</div>
") : ("")) . "") : ("" . (( $stuff['key'] != "") ? ("
<form action='{$this->settings['base_url']}app=reviews&amp;module=extra&amp;section=search&amp;do=search&amp;words={$stuff['words']}' method='post'>
<input type='hidden' name='SearchType' value='{$stuff['searchtype']}' />
<input type='hidden' name='SearchId' value='{$stuff['searchid']}' />
<h3 class='maintitle'>{$stuff['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row1' align='center'>{$this->lang->words['no_products_sort']}</td></tr>
<tr class='unread'><td class='altrow' align='right'>
<select name='key' class='codebuttons'>
<option value='name'{$selected['name']}>{$this->lang->words['sort_name']}</option>
<option value='catname'{$selected['catname']}>{$this->lang->words['sort_catname']}</option>
<option value='reviews'{$selected['reviews']}>{$this->lang->words['sort_reviews']}</option>
<option value='rating'{$selected['rating']}>{$this->lang->words['sort_rating']}</option>
<option value='time'{$selected['time']}>{$this->lang->words['sort_time']}</option>
</select>&nbsp;
<select name='order' class='codebuttons'>
<option value='ASC'{$selected['ASC']}>{$this->lang->words['asc']}</option>
<option value='DESC'{$selected['DESC']}>{$this->lang->words['desc']}</option>
</select>&nbsp;
<input type='submit' value='{$this->lang->words['sort']}' class='input_submit' />&nbsp;</td></tr>
</table>
</div>
</div>
</form>
<br />
") : ("
<h3 class='maintitle'>{$stuff['title']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
<tr><td class='row1' align='center'>{$this->lang->words['no_search_results']}</td></tr>
")) . "
</table>
</div>
</div>
<br />")) . "
</div></div>";
return $IPBHTML;
}

/* -- search_row --*/
function search_row($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<tr class='{$data['rowclass']}'><td class='altrow' align='center'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=products&amp;do=products&amp;id={$data['cid']}", "public",'' ), "{$data['fname']}", "showrevproduct" ) . "'>{$data['cname']}</a></td><td align='center'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=categories&amp;do=viewcat&amp;cid={$data['pcid']}", "public",'' ), "{$data['fname2']}", "showrevcategorytwo" ) . "'>{$data['pcname']}</a></td><td class='altrow' align='center'>{$data['finaloverall']}</td><td align='center'>{$data['num']}</td><td class='altrow' align='center'>{$data['date']}</td></tr>";
return $IPBHTML;
}

/* -- stats_bar --*/
function stats_bar($selected=array(),$monthy="",$yeary="") {
$IPBHTML = "";
$IPBHTML .= "<li class='non_button'>
      <form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=extra&amp;section=stats&amp;do=stats", "public",'' ), "stats", "showrevstats" ) . "' method='post'>
<div style=\"text-align:right;\">
<select name='key' class='codebuttons'>
<option value='awards'{$selected['awards']}>{$this->lang->words['topawards']}</option>
" . (( $this->settings['mr_use_points'] == '1') ? ("
<option value='points'{$selected['points']}>{$this->lang->words['toppoints']}</option>
") : ("")) . "
<option value='catcomments'{$selected['catcomments']}>{$this->lang->words['topcommentedcat']}</option>
<option value='revcomments'{$selected['revcomments']}>{$this->lang->words['topcommentedrevs']}</option>
<option value='comments'{$selected['comments']}>{$this->lang->words['topcommentedauthor']}</option>
<option value='deals'{$selected['deals']}>{$this->lang->words['topdeals']}</option>
<option value='catfavs'{$selected['catfavs']}>{$this->lang->words['topcatfavs']}</option>
<option value='catowned'{$selected['catowned']}>{$this->lang->words['topcatowned']}</option>
<option value='answers'{$selected['answers']}>{$this->lang->words['topanswers']}</option>
<option value='questions'{$selected['questions']}>{$this->lang->words['topquestions']}</option>
<option value='rated'{$selected['rated']}>{$this->lang->words['toprated']}</option>
<option value='ratings'{$selected['ratings']}>{$this->lang->words['toprates']}</option>
<option value='fills'{$selected['fills']}>{$this->lang->words['topfills']}</option>
<option value='requests'{$selected['requests']}>{$this->lang->words['toprequestedauthor']}</option>
<option value='reviews'{$selected['reviews']}>{$this->lang->words['topreviews']}</option>
<option value='tracked'{$selected['tracked']}>{$this->lang->words['toptrackedauthor']}</option>
<option value='cattracked'{$selected['cattracked']}>{$this->lang->words['toptrackedcat']}</option>
<option value='revtracked'{$selected['revtracked']}>{$this->lang->words['toptrackedrevs']}</option>
<option value='catviews'{$selected['catviews']}>{$this->lang->words['topcatviews']}</option>
<option value='revviews'{$selected['revviews']}>{$this->lang->words['toprevviews']}</option>
<option value='catwishes'{$selected['catwishes']}>{$this->lang->words['topcatwishes']}</option>
<option value='revawards'{$selected['revawards']}>{$this->lang->words['toprevawards']}</option>
</select>&nbsp;
{$monthy}&nbsp;
{$yeary}
<input type='submit' value='{$this->lang->words['sortstats']}' class='input_submit' />
</div>
</form>
</li>";
return $IPBHTML;
}

/* -- stats_page --*/
function stats_page($data=array()) {
$IPBHTML = "";
$IPBHTML .= "{$data['links']}
<table style='width:100%;'>
<tr>
<td style=\"width:50%;padding-left: 0;\" valign=\"top\">
<h3 class='maintitle'>{$data['lang']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
" . (( $data['rows'] != "") ? ("
<tr class='header'><th scope='col' style='text-align:center'>{$this->lang->words['rank']}</th>
<th scope='col'>{$this->lang->words['name']}</th>
<th scope='col' style='text-align:center'>{$this->lang->words['totals']}</th></tr>
{$data['rows']}
") : ("
<tr><td class='row1' align='center'>{$this->lang->words['no_stats']}</td></tr>
")) . "
</table>
</div>
</div>
</td>
<td style=\"width:50%;padding-left: 0;\" valign=\"top\">
<h3 class='maintitle'>{$data['lang2']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>
<table class='ipb_table'>
" . (( $data['rows'] != "") ? ("
<tr class='header'><th scope='col' style='text-align:center'>{$this->lang->words['rank']}</th>
<th scope='col'>{$this->lang->words['name']}</th>
<th scope='col' style='text-align:center'>{$this->lang->words['totals']}</th></tr>
{$data['rows2']}
") : ("
<tr><td class='row1' align='center'>{$this->lang->words['no_stats']}</td></tr>
")) . "
</table>
</div>
</div>
</td>
</tr>
</table>
<br />";
return $IPBHTML;
}

/* -- stats_page_row --*/
function stats_page_row($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<tr class='{$data['rowclass']}'><td class=\"altrow\" style=\"width:1%\" align='center'><strong>{$data['rank']}</strong></td>
<td style=\"width:89%\"><strong>{$data['name']}</strong></td>
<td class=\"altrow\" style=\"width:10%\" align='center'><strong>{$data['totals']}</strong></td></tr>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>