<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 6               */
/* CACHE FILE: Generated: Wed, 18 May 2016 17:28:40 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_blog_hooks_6 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['topics_blogThis'] = array('entryHasMore','blogloop','hasEntries');
$this->_funcHooks['topics_blogThisLink'] = array('hasblog');


}

/* -- topics_blogThis --*/
function topics_blogThis($entries=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_hooks', $this->_funcHooks['topics_blogThis'] ) )
{
$count_e2a4ff2c02fa0cce85e54bee2b8a15bf = is_array($this->functionData['topics_blogThis']) ? count($this->functionData['topics_blogThis']) : 0;
$this->functionData['topics_blogThis'][$count_e2a4ff2c02fa0cce85e54bee2b8a15bf]['entries'] = $entries;
}

if ( ! isset( $this->registry->templateStriping['recententries'] ) ) {
$this->registry->templateStriping['recententries'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "" . ((is_array($entries) && count($entries)) ? ("
	<br class='clear' /><br />
	<h2 class='maintitle'>{$this->lang->words['topic_blog_entries']}</h2>
	<div class='ipsBox'>
				".$this->__f__760fd1181e3f41d30f8e8413a14d9534($entries)."	</div>
") : ("")) . "";
return $IPBHTML;
}


function __f__760fd1181e3f41d30f8e8413a14d9534($entries=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $entries as $eid => $entry )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<div class='ipsBox_container ipsPad'>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$entry['member_id']}", "public",'' ), "{$entry['members_seo_name']}", "showuser" ) . "' class='ipsUserPhotoLink left'>
					<img src='{$entry['pp_small_photo']}' alt='{$this->lang->words['photo']}' class='ipsUserPhoto ipsUserPhoto_medium' />
				</a>
				<div class='ipsBox_withphoto'>
					<h3 class='ipsType_subtitle'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\">{$entry['entry_name']}</a></h3>
					<span class='desc blend_links'>
						{$this->lang->words['by_author']} " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($entry) : '' ) . "
						{$this->lang->words['in']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}", "public",'' ), "{$entry['blog_seo_name']}", "showblog" ) . "'>{$entry['blog_name']}</a>, {$this->lang->words['on']} " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($entry['_entry_date'],"long", 0)) . "
					</span>
					<br /><br />
					<div class='ipsType_textblock'>
						{$entry['entry_short']}
					</div>
					" . (($entry['blog_last_entry']) ? ("
						<br />
						<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\">
							<span class='ipsButton_secondary'>{$this->lang->words['read_more_go_on']} {$this->lang->words['_rarr']}</span>
						</a>
						<br class='clear' />
					") : ("")) . "
				</div>
			</div>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- topics_blogThisLink --*/
function topics_blogThisLink($post=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_hooks', $this->_funcHooks['topics_blogThisLink'] ) )
{
$count_b14f9dacb574108c83b5b6dc32454fb7 = is_array($this->functionData['topics_blogThisLink']) ? count($this->functionData['topics_blogThisLink']) : 0;
$this->functionData['topics_blogThisLink'][$count_b14f9dacb574108c83b5b6dc32454fb7]['post'] = $post;
}
$IPBHTML .= "" . (($this->settings['blog_allow_bthis'] AND $this->memberData['has_blog'] AND IPSLib::appIsInstalled( 'blog' ) AND $post['post']['_canReply']) ? ("
	<li>
		<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;blog_this=forums&amp;id1={$this->request['t']}&amp;id2={$post['post']['pid']}", "public",'' ), "", "" ) . "'>{$this->lang->words['blog_this']}</a>
	</li>
") : ("")) . "";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>