<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 02 Dec 2014 19:44:18 +0000 by SteveW
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'menu__calendars' => "Calendar Management",
'menu__cal_settings' => "Calendar Settings",
'menu__icalendar' => "Import iCalendar Feeds",
'r__calendar_delete' => "Can delete calendars?",
'r__calendar_ical' => "Can import ical and webcal feeds?",
'r__calendar_import' => "Import iCalendar Feeds",
'r__calendar_manage' => "Can add/edit calendars?",
'r__calendar_mt' => "Calendar Management",
 ); 
