<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 02 Dec 2014 19:44:18 +0000 by SteveW
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'cmtp_js_added' => "Added Successfully",
'cmtp_js_bug_BugReportBlank' => "Bug Report Message Can Not Be Blank!",
'cmtp_js_bug_BugReportSent' => "Bug Report Sent",
'cmtp_js_bug_delete' => "Bug Report Deleted.",
'cmtp_js_bug_NotValidEmail' => "Not A Valid Contact Email Address!",
'cmtp_js_bug_startBug' => "Bug Report Started",
'cmtp_js_deleted' => "Deleted Successfully",
'cmtp_js_doesNotExist' => "This Group Already Exist To Be Shown!",
'cmtp_js_edited' => "Changes Saved",
'cmtp_js_error' => "Something Bad has happened! Try Again",
'cmtp_js_NotThere' => "For Whatever Reason, This Group Does Not Exist! Try Again!",
'cmtp_js_no_perms' => "You don't have permissions to use this feature.",
'cmtp_js_reorder' => "New Ordering Saved",
'cmtp_php_AddButton' => "Add",
'cmtp_php_addRemove' => "Add/Remove",
'cmtp_php_add_member' => "Add Member",
'cmtp_php_add_member_name' => "Members Name",
'cmtp_php_BugReport' => "Bug Report",
'cmtp_php_BugReportBody' => "Found A Problem? Tell us about it",
'cmtp_php_BugReportButton' => "File A Bug Report",
'cmtp_php_BugReportContact' => "Contact Email",
'cmtp_php_BugReportDate' => "Date Filed",
'cmtp_php_BugReportDelete' => "Remove Report",
'cmtp_php_BugReportDescription' => "Detailed description of the problem:",
'cmtp_php_BugReportDisplay' => "Bugs Reported: Last 5 (Max)",
'cmtp_php_BugReportDisplayLatest' => "Bug Report",
'cmtp_php_BugReportDisplayNone' => "No Current Bug Reports",
'cmtp_php_BugReportReturn' => "Thank You, {$this->memberData['name']} for Submitting a Bug Report, we will look into it and get back to you soon! ",
'cmtp_php_BugReportSend' => "Submit Bug Report",
'cmtp_php_BugReportUser' => "User",
'cmtp_php_Change_Group_Name' => "Change Group Name",
'cmtp_php_CurrentVersion' => "Current Version",
'cmtp_php_displayed' => "Displayed?",
'cmtp_php_DisplayedGroups' => "Displayed Groups (drag and drop to reorder)",
'cmtp_php_DisplayName' => "Displayed Name",
'cmtp_php_GeneralInfo' => "General Information",
'cmtp_php_groupTitle' => "Group Title",
'cmtp_php_Installed' => "Installed Version",
'cmtp_php_mainDescription' => "Add and Remove Groups From Moderator Team Page",
'cmtp_php_mainLink' => "Display Groups",
'cmtp_php_members' => "Members",
'cmtp_php_NameChangeDesc' => "Leave Blank if you do not desire to alter display name.<br>
(this does not change the groups actual name, just how <br>
it displays in Moderator Team Page.)",
'cmtp_php_NewName' => "New Name",
'cmtp_php_News' => "News",
'cmtp_php_NewsBad' => "Can not Make A connection or there is no News!",
'cmtp_php_NewUpdates' => "New Updates Available!",
'cmtp_php_Original_Name' => "Original Name",
'cmtp_php_OverView' => "Custom Moderator Team Page: Overview",
'cmtp_php_overviewDescription' => "News, Update Information, Bug Reports, General Information",
'cmtp_php_overviewlink' => "Overview",
'cmtp_php_SelectGroups' => "Select Groups To Display",
 ); 
