<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 02 Dec 2014 19:44:18 +0000 by SteveW
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'menu__gallery_add_album' => "Add New Album",
'menu__gallery_album_defautls' => "Album Defaults",
'menu__gallery_album_manager' => "Album Manager",
'menu__gallery_category_manager' => "Category Manager",
'menu__gallery_overview' => "Overview",
'menu__gallery_settings' => "Settings",
'menu__gallery_stats' => "Statistics",
'r__album_add' => "Can add albums for members?",
'r__album_delete' => "Can delete albums?",
'r__album_empty' => "Can empty albums?",
'r__album_manage' => "Can edit and resynchronize album information for members?",
'r__album_managet' => "Album Management",
'r__category_delete' => "Can delete categories?",
'r__category_empty' => "Can empty categories?",
'r__category_manage' => "Can add and edit categories?",
'r__category_managet' => "Category Management",
'r__galstats_filealter' => "Can change file ownership?",
'r__galstats_files' => "Can run file reports?",
'r__galstats_groups' => "Can run group reports?",
'r__galstats_memberalter' => "Can change member access privileges?",
'r__galstats_members' => "Can run member reports?",
'r__stats_reports' => "Stats Reports",
 ); 
