<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 02 Dec 2014 19:44:18 +0000 by SteveW
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'menu__logs' => "Logs",
'menu__manage_settings' => "Manage Settings",
'menu__ranking' => "Ranking",
'menu__tools' => "Tools",
 ); 
