<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 02 Dec 2014 19:44:18 +0000 by SteveW
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'add_block' => "Add Sidebar Block",
'add_sidebar' => "Add Sidebar",
'all_groups' => "All Groups",
'app' => "Application",
'app_desc' => "The value of Array['app']",
'block' => "Block",
'block_desc__block' => "A block configured in IP.Content",
'block_desc__blog' => "A block configured in IP.Blog",
'block_desc__div' => "The contents of any div tag on the page",
'block_desc__group' => "A block available in the Social Groups application.<br />Note: These blocks will only be displayed in the Social Groups application OR on the Group forum pages.",
'block_desc__hook' => "A template hook that is configured to display on the Board Index",
'block_desc__html' => "HTML and/or template code that will be included on the page",
'block_key' => "Block Key",
'block_type__block' => "IP.Content Block",
'block_type__blog' => "IP.Blog Block",
'block_type__div' => "DIV Block",
'block_type__group' => "Social Groups Block",
'block_type__hook' => "Board Index Hook",
'block_type__html' => "HTML Block",
'div_id' => "Div ID",
'div_id_desc' => "The ID attribute of the Div tag on the page.<br /><strong>Note: The Div must be present on the current screen in order to be displayed on the sidebar.</strong>",
'do' => "Do",
'do_desc' => "The value of Array['do']",
'edit_block' => "Edit Sidebar Block",
'edit_sidebar' => "Edit Sidebar",
'groups' => "Groups",
'groups_desc' => "The groups that can see the sidebar block",
'html_content' => "HTML Content",
'html_content_desc' => "The HTML content of the Sidebar Block.<br/>Used only when Block Type is set to \"HTML Block\".",
'manage_blocks' => "Manage Blocks",
'manage_sidebars' => "Manage Sidebars",
'manage_sidebar_blocks' => "Manage Sidebar Blocks",
'module' => "Module",
'module_desc' => "The value of Array['module']",
'name' => "Block Name",
'name_desc' => "A unique name for the Sidebar Block",
'no_blocks' => "No sidebar blocks have been configured yet.",
'no_sidebars' => "No sidebars have been configured yet.",
'options' => "Options",
'params' => "Parameters",
'params_desc' => "Additional parameters that will be used to further define the page.<br />You may use any parameter that is included in the Request URL.<br />All parameters should be entered as <em>key=value</em>, with each parameter on its own line.<br />To use multiple values, enter a comma-separated list. Example: <em>key=value1,value2</em>",
'section' => "Section",
'section_desc' => "The value of Array['section']",
'step_1' => "1. Type",
'step_1_desc' => "Select the block type",
'step_2' => "2. Properties",
'step_2_desc' => "Configure the block",
'type' => "Block Type",
'type_desc' => "The type of content that will be used in the Sidebar Block",
'use_default' => "Use Default",
'use_default_desc' => "Indicates whether this page should use the Default Sidebar",
 ); 
