<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Wed, 18 May 2016 17:28:29 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_albums_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['albumView'] = array('pages');
$this->_funcHooks['userGalleryView'] = array('hasAlbumPagesTop','hasAlbumPagesBottom','hasImagePagesTop','hasImagePagesTop');


}

/* -- albumSelector --*/
function albumSelector($albums, $albumData=array()) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- albumSelectorPanel --*/
function albumSelectorPanel($albums, $filters, $albumData) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- albumView --*/
function albumView($cover, $images, $album, $follow='', $recentAlbums=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_albums', $this->_funcHooks['albumView'] ) )
{
$count_27e1e6ee7dcbf6fa294294d85e7bba53 = is_array($this->functionData['albumView']) ? count($this->functionData['albumView']) : 0;
$this->functionData['albumView'][$count_27e1e6ee7dcbf6fa294294d85e7bba53]['cover'] = $cover;
$this->functionData['albumView'][$count_27e1e6ee7dcbf6fa294294d85e7bba53]['images'] = $images;
$this->functionData['albumView'][$count_27e1e6ee7dcbf6fa294294d85e7bba53]['album'] = $album;
$this->functionData['albumView'][$count_27e1e6ee7dcbf6fa294294d85e7bba53]['follow'] = $follow;
$this->functionData['albumView'][$count_27e1e6ee7dcbf6fa294294d85e7bba53]['recentAlbums'] = $recentAlbums;
}
$IPBHTML .= "<h2>{$album['album_name']} {$this->lang->words['by_ucfirst']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;user={$album['owner']['member_id']}", "public",'' ), "{$album['owner']['members_seo_name']}", "useralbum" ) . "\">{$album['owner']['members_display_name']}</a></h2>
" . ((is_array($images) and count($images)) ? ("<div class='master_list'>
	<div class='row' style=\"text-align: center;\">
		".$this->__f__2f001e2b791e260b8e4ede3c8a4a347d($cover,$images,$album,$follow,$recentAlbums)."		" . ((! empty( $album['_pages'] )) ? ("
			<br />{$album['_pages']}
		") : ("")) . "
	</div>
</div>") : ("")) . "";
return $IPBHTML;
}


function __f__2f001e2b791e260b8e4ede3c8a4a347d($cover, $images, $album, $follow='', $recentAlbums=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $images as $id => $image )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<div style=\"margin:2px 1px; display: inline-block; min-height: 50px; border:1px solid #777;\">
				" . $this->registry->getClass('gallery')->inlineResize( $image['thumb'],'thumb_medium','','' ) . "
			</div>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- deleteAlbumDialogue --*/
function deleteAlbumDialogue($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- miniLatestCommentBlock --*/
function miniLatestCommentBlock($images, $title='') {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- newAlbumDialogue --*/
function newAlbumDialogue($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- userGalleryView --*/
function userGalleryView($data, $images, $albums) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_albums', $this->_funcHooks['userGalleryView'] ) )
{
$count_b83cedd83bbc7e8e02f911e4ede46a93 = is_array($this->functionData['userGalleryView']) ? count($this->functionData['userGalleryView']) : 0;
$this->functionData['userGalleryView'][$count_b83cedd83bbc7e8e02f911e4ede46a93]['data'] = $data;
$this->functionData['userGalleryView'][$count_b83cedd83bbc7e8e02f911e4ede46a93]['images'] = $images;
$this->functionData['userGalleryView'][$count_b83cedd83bbc7e8e02f911e4ede46a93]['albums'] = $albums;
}
$IPBHTML .= "<h2>" . sprintf( $this->lang->words['member_x_albums'], $data['owner']['members_display_name'] ) . "</h2>
<br />
" . (($data['_albumPages']) ? ("
	{$data['_albumPages']}<br />
") : ("")) . "
" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_home'), 'album_listing' ) ? $this->registry->getClass('output')->getTemplate('gallery_home')->album_listing($albums, array(), array( 'url' => 'app=gallery&amp;user=' . $data['owner']['member_id'], 'title' => $data['owner']['members_seo_name'], 'template' => 'useralbum', 'sort_key' => 'album_name', 'sort_dir' => 'asc' )) : '' ) . "
" . (($data['_albumPages']) ? ("
	<br />{$data['_albumPages']}
") : ("")) . "
<br />
" . (($data['_imagePages']) ? ("
	{$data['_imagePages']}<br />
") : ("")) . "
" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_home'), 'image_listing' ) ? $this->registry->getClass('output')->getTemplate('gallery_home')->image_listing($images, array(), array(), array( 'url' => 'app=gallery&amp;user=' . $data['owner']['member_id'], 'title' => $data['owner']['members_seo_name'], 'template' => 'useralbum', 'sort_key' => 'image_date', 'sort_dir' => 'desc' )) : '' ) . "
" . (($data['_imagePages']) ? ("
	<br />{$data['_imagePages']}
") : ("")) . "
<br />";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>