<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Wed, 18 May 2016 17:28:29 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gaplus_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['includeVars'] = array('varLoop','openGAPlusTag','hasvars','closeGAPlusTag');


}

/* -- includeEvents --*/
function includeEvents($events=array()) {
$IPBHTML = "";
$IPBHTML .= "" . ((count($events) && is_array($events)) ? ("".$this->__f__5a8aa643c15ea6640b9a2cc3140a10c2($events)."") : ("")) . "";
return $IPBHTML;
}


function __f__5a8aa643c15ea6640b9a2cc3140a10c2($events=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $events as $e => $event )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
function trackEvent_{$event['ga_event_element']}(e)
{
new _gaq.push(['_trackEvent', '{$event['ga_event_category']}', '{$event['ga_event_event']}', '{$event['ga_event_title']}']);
}
if($('{$event['ga_event_element']}'))
{
$('{$event['ga_event_element']}').observe('click', trackEvent_{$event['ga_event_element']});
}

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- includeVars --*/
function includeVars($vars=array(), $events=array(), $fullScript=TRUE) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gaplus', $this->_funcHooks['includeVars'] ) )
{
$count_7e0517d1210d5f7d09c550ede8f5b063 = is_array($this->functionData['includeVars']) ? count($this->functionData['includeVars']) : 0;
$this->functionData['includeVars'][$count_7e0517d1210d5f7d09c550ede8f5b063]['vars'] = $vars;
$this->functionData['includeVars'][$count_7e0517d1210d5f7d09c550ede8f5b063]['events'] = $events;
$this->functionData['includeVars'][$count_7e0517d1210d5f7d09c550ede8f5b063]['fullScript'] = $fullScript;
}
$IPBHTML .= "" . (($fullScript) ? ("
<script type='text/javascript'>
") : ("")) . "
var _gaq = _gaq || [];
_gaq.push(
['_setAccount', '{$this->settings['gaplus_ua_code']}'],
" . ((is_array($vars) && count($vars)) ? ("".$this->__f__f75bedee43f3f333c1a2f67e7da72e4e($vars,$events,$fullScript)."") : ("")) . "['_trackPageview']
);
" . ((count($events) && is_array($events)) ? ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('gaplus'), 'includeEvents' ) ? $this->registry->getClass('output')->getTemplate('gaplus')->includeEvents($events) : '' ) . "") : ("")) . "
(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
" . (($fullScript) ? ("
</script>
") : ("")) . "";
return $IPBHTML;
}


function __f__f75bedee43f3f333c1a2f67e7da72e4e($vars=array(), $events=array(), $fullScript=TRUE)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $vars as $k => $v )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "['_setCustomVar', " . ($k+1) . ", '{$v['ga_app']}{$v['ga_module']}{$v['ga_section']}{$v['ga_var_title']}', '{$v['ga_var_value']}', {$v['ga_level']}],
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>