<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Wed, 18 May 2016 17:28:32 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_nexus_payments_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();


}

/* -- attachments --*/
function attachments($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- authNetDpm --*/
function authNetDpm($hiddenFields) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cart_sidebar --*/
function cart_sidebar($cart=array()) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cat_menu_item --*/
function cat_menu_item($curGroup, $hierarchy) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- comment --*/
function comment($r, $parent, $settings) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- commentsList --*/
function commentsList($comments, $settings, $pages, $parent, $preReply='') {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- confirmButton --*/
function confirmButton($invoice, $onclick='') {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- creditCardPayments --*/
function creditCardPayments($transid, $methodid, $recurring, $acceptedTypes=array(), $showTypeList=FALSE, $isUkCard=FALSE, $showLogos=TRUE, $cardOnFile=NULL, $recurr_message='cc_ac', $giveFieldElementsNameTags=TRUE, $showCodeFieldForRecurringPayments=TRUE) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- donationsSidebar --*/
function donationsSidebar($goals) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- enterDetails --*/
function enterDetails($errors, $fields, $states, $member, $taxable, $invoice, $maxStep) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- extraStep --*/
function extraStep($invoice, $button) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- giftVouchers --*/
function giftVouchers($options, $errors=array(), $messageContent='') {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- hostingForm --*/
function hostingForm($subDomainOptions, $serverToUse, $tldOptions) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- loginOrRegister --*/
function loginOrRegister($errors, $fields, $states, $member, $invoice, $customProfileFields, $time_select, $captchaHTML, $question, $maxStep) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- moderatorPanel --*/
function moderatorPanel($results) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- orderProgress --*/
function orderProgress($curStep, $maxStep, $steps, $invoiceId) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- payment_onhold --*/
function payment_onhold($invoice, $instructions, $showSteps=TRUE, $allowCancel=FALSE) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- redeem --*/
function redeem($error) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- regForm32 --*/
function regForm32($packages, $error='') {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- reviewForm --*/
function reviewForm($package, $editor, $errors) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- selectMethod --*/
function selectMethod($invoice, $items, $subtotal, $tax, $shipping, $discount, $difference, $methods, $error, $showCoupons, $maxStep, $transaction, $previousTransactions, $canUseCredit=TRUE) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- selectShipping --*/
function selectShipping($invoice, $shipAddress, $states, $countries, $data, $maxStep, $member, $errors) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- showStore --*/
function showStore($packages, $packageGroups, $hierarchy, $cart, $title, $featured, $pagination, $cat) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- storeGridView --*/
function storeGridView($package) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- storeListView --*/
function storeListView($package) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- storeSearch --*/
function storeSearch($r) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- thanks --*/
function thanks($invoice, $instructions) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- upsell --*/
function upsell($added, $packages, $cart) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- viewCart --*/
function viewCart($cart) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- viewItem --*/
function viewItem($package, $customfields, $associate, $extra, $cart, $shareLinks, $images, $reviews, $rating, $bought, $renewOptions) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>