<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Wed, 18 May 2016 17:28:26 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_reviews_pages_1 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();


}

/* -- index --*/
function index($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<div class='ipsBox'>
	<div class='ipsBox_container'>
		" . ((is_array($data) && is_array($data['categories']) && count($data['categories'])) ? ("
			<div class=\"categories\">
				".$this->__f__4d7125ae6c63b6e7b455802c9ecf4170($data)."			</div>
		") : ("
			<p>{$this->lang->words['no_categories']}</p>
		")) . "
	</div>
</div>";
return $IPBHTML;
}


function __f__d19b65f8b77d6b4a812009b5046194fc($data=array(),$position='',$category='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $category['children'] as $subcategory )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
									<li class=\"category__li\"><span>›</span><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=categories&amp;do=viewcat&amp;cid={$subcategory['cid']}", "public",'' ), "" . IPSText::makeSeoTitle($subcategory['cname']) . "", "showrevcategorytwo" ) . "\">{$subcategory['cname']}</a></li>
								
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__4d7125ae6c63b6e7b455802c9ecf4170($data=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $data['categories'] as $position => $category )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					<div class='category " . (($position % 2) ? ("omega") : ("alpha")) . "'>
						<h2><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=reviews&amp;module=products&amp;section=categories&amp;do=viewcat&amp;cid={$category['cid']}", "public",'' ), "" . IPSText::makeSeoTitle($category['cname']) . "", "showrevcategorytwo" ) . "\">{$category['cname']}</a></h2>
						" . ((is_array($category['children']) && count($category['children'])) ? ("
							<ul>
								".$this->__f__d19b65f8b77d6b4a812009b5046194fc($data,$position,$category)."							</ul>
						") : ("")) . "
					</div>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>