<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Wed, 18 May 2016 17:28:24 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_blog_list_1 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['blog_rating'] = array('ratingishigher','blogRating');
$this->_funcHooks['blogAjaxSidebar'] = array('newcommentBlog','blogsLoop','anyrecents');
$this->_funcHooks['blogAjaxSidebarREntries'] = array('newcommentRecent','recentLoop','anyrecents');
$this->_funcHooks['blogFeaturedEntry'] = array('featured');
$this->_funcHooks['blogIndexPage'] = array('isCurrentBlog','canPostInBlog','memberBlogs','newcommentPinned','hasLastEntry','pinnedLoop','filterLoop','sortKeyLoop','sortOrderLoop','maxResultsLoop','featuredloop','tablenormalblogloop','featuredloop','tablepinnedblogloop','tablenormalblogloop','canstartblog','blogowner','howmanyblogsmenu','viewerismember','anypinned','statsrating','showsidebar','topicsismod','isDashboard','listAllBlogs','listLocalBlogs','listExternalBlogs','indexmoderation','featured','normalblogs','ismod','featured','tablepinnedblogs','tablenormalblogs','blogviewmode','hasPagesBottom','noblogs','whynotcreateone','statHasBlogs','hasactiveusers','indexactiveusers','disablelightbox');
$this->_funcHooks['blogListRow'] = array('viewdraftcss','futureblog2','isdraft','isfeatured','isrssimport','viewhascats','futureblog','blogRatingEnabled','hasFullListEntryImage','hasEntryImage','showFullList','viewprivate','canbanish','selected','ismod','entryFooterMod','entryHasMoreText','hasQueuedComments','islocked');
$this->_funcHooks['blogTableRow'] = array('newdata','isPrivate','isDisabled','isDisabledAndPinned','blogViewLevelPrivate','blogViewLevelPrivateClub','ispinned','isfeatured','isDisabledBadge','previewHasEntry','feedburnerlink','blogrss','isGroupBlog','hasEntries','selected','ismod','blogIsDisabled','ispinned','isfeatured','isDisabledBadge','isGroupBlog','selected','ismod','blogIsLocal');
$this->_funcHooks['generateBlogIcon'] = array('gotoNewCommentsStart','isBlogOwnerUnread','isNotBlogOwnerUnread','isBlogOwner','isDisabled','gotoNewCommentsEnd');


}

/* -- blog_rating --*/
function blog_rating($number) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_list', $this->_funcHooks['blog_rating'] ) )
{
$count_691e2192ab6ffb27d925f057050f6bd3 = is_array($this->functionData['blog_rating']) ? count($this->functionData['blog_rating']) : 0;
$this->functionData['blog_rating'][$count_691e2192ab6ffb27d925f057050f6bd3]['number'] = $number;
}
$IPBHTML .= "".$this->__f__d920e7e7f8eb25da55e384c6bd60fd66($number)."";
return $IPBHTML;
}


function __f__d920e7e7f8eb25da55e384c6bd60fd66($number)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( array(1,2,3,4,5) as $int )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	" . (($number >= $int) ? ("
		" . $this->registry->getClass('output')->getReplacement("mini_rate_on") . "
	") : ("
		" . $this->registry->getClass('output')->getReplacement("mini_rate_off") . "
	")) . "

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- blogAjaxSidebar --*/
function blogAjaxSidebar($blogs) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_list', $this->_funcHooks['blogAjaxSidebar'] ) )
{
$count_142d1874a8cf2e7b51a1d15c27a4984f = is_array($this->functionData['blogAjaxSidebar']) ? count($this->functionData['blogAjaxSidebar']) : 0;
$this->functionData['blogAjaxSidebar'][$count_142d1874a8cf2e7b51a1d15c27a4984f]['blogs'] = $blogs;
}
$IPBHTML .= "" . ((is_array( $blogs ) && count( $blogs )) ? ("
	".$this->__f__9b5ff0ff69fbea35df4c6d3bcbb52083($blogs)."") : ("
	<li><div class='ipsPad'>{$this->lang->words['no_entry_matches']}</div></li>
")) . "";
return $IPBHTML;
}


function __f__9b5ff0ff69fbea35df4c6d3bcbb52083($blogs)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $blogs as $eid => $entry )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<li class='clearfix'>
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($entry) : '' ) . "
			<div class='list_content'>
				" . (($entry['newpost']) ? ("
					 <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}&amp;show=newcomment", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\">" . $this->registry->getClass('output')->getReplacement("f_newpost") . "</a>
				") : ("")) . "
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}", "public",'' ), "{$entry['blog_seo_name']}", "showblog" ) . "'><strong>{$entry['blog_name']}</strong></a>
				<div class='desc ipsType_smaller'>
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\">{$entry['entry_name']}</a>
					<br />{$this->lang->words['by_ucfirst']} " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($entry) : '' ) . "
				</div>
			</div>
		</li>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- blogAjaxSidebarREntries --*/
function blogAjaxSidebarREntries($entries) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_list', $this->_funcHooks['blogAjaxSidebarREntries'] ) )
{
$count_f62afd6cedeb29ce5473f6b3d47f5935 = is_array($this->functionData['blogAjaxSidebarREntries']) ? count($this->functionData['blogAjaxSidebarREntries']) : 0;
$this->functionData['blogAjaxSidebarREntries'][$count_f62afd6cedeb29ce5473f6b3d47f5935]['entries'] = $entries;
}
$IPBHTML .= "" . ((is_array( $entries ) && count( $entries )) ? ("
	".$this->__f__f1bbcaf2f547e4e420045370c113663f($entries)."") : ("
	<li class='row2'><div class='ipsPad'>{$this->lang->words['no_entry_matches']}</div></li>
")) . "";
return $IPBHTML;
}


function __f__f1bbcaf2f547e4e420045370c113663f($entries)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $entries as $eid => $entry )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<li class='clear'>
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($entry) : '' ) . "
			<div class='list_content clearfix'>
				" . (($entry['newpost']) ? ("
					 <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}&amp;show=newcomment", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\">" . $this->registry->getClass('output')->getReplacement("f_newpost") . "</a>
				") : ("")) . "
				<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\">{$entry['entry_name']}</a>
				<div class='desc ipsType_smaller'>
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}", "public",'' ), "{$entry['blog_seo_name']}", "showblog" ) . "'><strong>{$entry['blog_name']}</strong></a>
					<br />" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($entry['entry_date'],"short2", 0)) . "
				</div>
			</div>
		</li>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- blogFeaturedEntry --*/
function blogFeaturedEntry($featured=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_list', $this->_funcHooks['blogFeaturedEntry'] ) )
{
$count_052972eb25ab21d0afd6ae73564f1146 = is_array($this->functionData['blogFeaturedEntry']) ? count($this->functionData['blogFeaturedEntry']) : 0;
$this->functionData['blogFeaturedEntry'][$count_052972eb25ab21d0afd6ae73564f1146]['featured'] = $featured;
}
$IPBHTML .= "" . ((is_array($featured) AND count($featured)) ? ("
	<link rel=\"stylesheet\" type=\"text/css\" title='Main' media='screen' href='{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipblog.css' />
	<div class='ipsBox'>
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('blog_list'), 'blogListRow' ) ? $this->registry->getClass('output')->getTemplate('blog_list')->blogListRow($featured, TRUE) : '' ) . "
	</div>
	<br class='clear' />
") : ("")) . "";
return $IPBHTML;
}

/* -- blogIndexPage --*/
function blogIndexPage($pages, $featured=array(), $blogs=array(), $extra='', $type='dash', $sorting='', $pinned=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_list', $this->_funcHooks['blogIndexPage'] ) )
{
$count_f6fea1e2b25f151e74fc16527eba9934 = is_array($this->functionData['blogIndexPage']) ? count($this->functionData['blogIndexPage']) : 0;
$this->functionData['blogIndexPage'][$count_f6fea1e2b25f151e74fc16527eba9934]['pages'] = $pages;
$this->functionData['blogIndexPage'][$count_f6fea1e2b25f151e74fc16527eba9934]['featured'] = $featured;
$this->functionData['blogIndexPage'][$count_f6fea1e2b25f151e74fc16527eba9934]['blogs'] = $blogs;
$this->functionData['blogIndexPage'][$count_f6fea1e2b25f151e74fc16527eba9934]['extra'] = $extra;
$this->functionData['blogIndexPage'][$count_f6fea1e2b25f151e74fc16527eba9934]['type'] = $type;
$this->functionData['blogIndexPage'][$count_f6fea1e2b25f151e74fc16527eba9934]['sorting'] = $sorting;
$this->functionData['blogIndexPage'][$count_f6fea1e2b25f151e74fc16527eba9934]['pinned'] = $pinned;
}

$this->_canModerateBlogs = ($this->memberData['g_is_supmod'] or $this->memberData['_blogmod']['moderate_can_disable'] or $this->memberData['_blogmod']['moderate_can_pin']) ? true : false;

$_sortKey	= empty($this->request['sort_key']) ? '' : '&amp;sort_key='.$this->request['sort_key'];
				$_sortOrder	= empty($this->request['sort_order']) ? '' : '&amp;sort_order='.$this->request['sort_order'];
				$_maxResult	= empty($this->request['max_results']) ? '' : '&amp;max_results='.$this->request['max_results'];
				
				$_listAll	= $type == 'dash' ? "app=blog&amp;type=all" : "app=blog&amp;type=all&amp;filter=all{$_sortKey}{$_sortOrder}{$_maxResult}";
$IPBHTML .= "<script type='text/javascript'>
	ipb.lang['blog_pin'] = \"{$this->lang->words['blog_pin']}\";
	ipb.lang['blog_unpin'] = \"{$this->lang->words['blog_unpin']}\";
	ipb.lang['blog_enable'] = \"{$this->lang->words['blog_enable']}\";
	ipb.lang['blog_disable'] = \"{$this->lang->words['blog_disable']}\";
</script>
" . $this->registry->getClass('output')->addJSModule("blog", "0" ) . "
<script type='text/javascript'>
	
	ipb.blog.withBlocks = true;
	ipb.templates['blog_moderation'] = new Template(\"<div id='comment_moderate_box' class='ipsFloatingAction' style='display: none'><span class='desc'>{$this->lang->words['b_comment_action_count']} </span><select id='tactInPopup' class='input_select'></select>&nbsp;&nbsp;<input type='button' class='input_submit' id='submitModAction' value='{$this->lang->words['comments_act_go']}' /></div>\");
</script>
<div id='blog_header_menu'>
	" . (($this->memberData['member_id']) ? ("<ul class='topic_buttons'>
			" . ((is_array($this->memberData['has_blog']) AND count($this->memberData['has_blog'])) ? ("
				<li class=''><a id='addentrylink' class='ipbmenu' href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=post&amp;section=post&amp;do=showform", "public",'' ), "", "" ) . "'>{$this->lang->words['add_entry']} <img src='{$this->settings['img_url']}/opts_arrow.png' alt='' class='arrow' /></a></li>
				<li class='non_button'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=manage", "public",'' ), "false", "manageblog" ) . "'>{$this->lang->words['blog_manage']}</a></li>
			") : ("" . (((!is_array($this->memberData['has_blog']) OR !count($this->memberData['has_blog'])) && $this->memberData['member_id'] && ( $this->memberData['g_blog_allowcreate'] OR $this->memberData['g_blog_allowlocal'])) ? ("
					<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=manage&amp;section=dashboard&amp;act=create&amp;form_hash={$this->member->form_hash}", "public",'' ), "false", "createblog" ) . "'>{$this->lang->words['ucp_create_blog']}</a></li>
				") : ("")) . "")) . "
		</ul>
		" . ((is_array($this->memberData['has_blog']) && count($this->memberData['has_blog'])) ? ("
			<ul class=\"ipbmenu_content\" id='addentrylink_menucontent' style='display:none' >
				".$this->__f__a9d3c69b4427971789bc943d73c2347e($pages,$featured,$blogs,$extra,$type,$sorting,$pinned)."			</ul>
		") : ("")) . "") : ("")) . "
	<h1 class='ipsType_pagetitle left'>" . IPSLib::getAppTitle('blog') . "</h1>
</div>
<br class='clear' />
<br />
" . (($type == 'dash') ? ("<div class='ipsLayout ipsLayout_withright ipsLayout_largeright'>
	<div class='ipsLayout_right'>
		<!-- PINNED -->
		" . ((is_array( $pinned ) AND count( $pinned )) ? ("
			<div class='ipsSideBlock clearfix'>
				<h3>{$this->lang->words['bloglist_start_pinned']}</h3>
				<ul class='ipsList_withminiphoto'>
					".$this->__f__9764d044d8af2a02a19e1dcc14759558($pages,$featured,$blogs,$extra,$type,$sorting,$pinned)."				</ul>
			</div>
		") : ("")) . "
		
		<!-- RECENT ENTRIES -->
		<div id='cblock_recent' class='ipsSideBlock clearfix'>
			<h3><span class='ipbmenu clickable' id='recentajax'><span id='ratitle'>{$this->lang->words['blist_recent_entries']}</span> " . $this->registry->getClass('output')->getReplacement("dropdown") . "</span></h3>
			<ul class='ipsList_withminiphoto' id='recentajaxcontent'>
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('blog_list'), 'blogAjaxSidebarREntries' ) ? $this->registry->getClass('output')->getTemplate('blog_list')->blogAjaxSidebarREntries($extra['recentEntries']) : '' ) . "
			</ul>
			<ul class='ipbmenu_content' id='recentajax_menucontent'>
				<li><a href=\"#\" class='c_block_title __rmenu __xrecent'>{$this->lang->words['blist_recent_entries']}</a></li>
				" . (($this->settings['blog_enable_rating']) ? ("
					<li><a href=\"#\" class='c_block_title __rmenu __xrating'>{$this->lang->words['top10_rated']}</a></li>
				") : ("")) . "
				<li><a href=\"#\" class='c_block_title __rmenu __xviewed'>{$this->lang->words['top10_viewed']}</a></li>
				<li><a href=\"#\" class='c_block_title __rmenu __xcommented'>{$this->lang->words['top10_commented']}</a></li>
				<li><a href=\"#\" class='c_block_title __rmenu __xbloggers'>{$this->lang->words['top10_bloggers']}</a></li>
			</ul>
		</div>
		<script type='text/javascript'>
			ipb.blog.setUpRecentMenu();
		</script>
	</div>") : ("
<div class='ipsLayout'>
")) . "
	<div class='ipsLayout_content'>
		<div class='maintitle ipsFilterbar'>
						
			" . (($this->_canModerateBlogs == 1) ? ("
				<span class='right'>
					&nbsp;<input type='checkbox' id='bmod_all' class='input_check' title='{$this->lang->words['blog_select_all']}' value='1' />
					&nbsp;
				</span>
			") : ("")) . "
				
			<ul class='ipsList_inline'>
				<li" . (($type == 'dash') ? (" class='active'") : ("")) . ">
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;type=dash", "public",'' ), "false", "app=blog" ) . "'>{$this->lang->words['blog_hp_viewhome']}</a>
				</li>
				<li" . ((($type == 'all' && empty($this->request['filter']) ) || $this->request['filter'] == 'all') ? (" class='active'") : ("")) . ">
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "$_listAll", "public",'' ), "false", "app=blog" ) . "'>{$this->lang->words[ $sorting['the_filter']['all'] ]}</a>
				</li>
				<li" . (($this->request['filter'] == 'local') ? (" class='active'") : ("")) . ">
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;type=all&amp;filter=local{$_sortKey}{$_sortOrder}{$_maxResult}", "public",'' ), "false", "app=blog" ) . "'>{$this->lang->words[ $sorting['the_filter']['local'] ]}</a>
				</li>
				<li" . (($this->request['filter'] == 'external') ? (" class='active'") : ("")) . ">
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;type=all&amp;filter=external{$_sortKey}{$_sortOrder}{$_maxResult}", "public",'' ), "false", "app=blog" ) . "'>{$this->lang->words[ $sorting['the_filter']['external'] ]}</a>
				</li>
				<li>
					<a href='#blogs_filter_menucontent' id='blogs_filter'>{$this->lang->words['custom_filter']}</a>
				</li>
			</ul>
		</div>
		<div id='blogs_filter_menucontent' class='ipbmenu_content ipsPad' style='display: none'>
			<form id='filter_form' action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;type=all", "public",'' ), "false", "app=blog" ) . "\" method=\"post\">
				<strong>{$this->lang->words['blist_show']}</strong><br />
				<select name='filter' id='filter' class='input_select'>
					".$this->__f__428c269262d0437f80b5e1f6785d40d6($pages,$featured,$blogs,$extra,$type,$sorting,$pinned)."				</select>
				<br /><br />
				
				<strong>{$this->lang->words['blist_sort_on']}</strong><br />
				<select name='sort_key' id='sort_key' class='input_select'>
					".$this->__f__764db7dd4b709a0dfd90e2821da92f62($pages,$featured,$blogs,$extra,$type,$sorting,$pinned)."				</select>
				<br /><br />
				
				<strong>{$this->lang->words['by_sort']}</strong><br />
				<select name='sort_order' id='sort_order' class='input_select'>
					".$this->__f__85301278ca33210511067ab6419ed933($pages,$featured,$blogs,$extra,$type,$sorting,$pinned)."				</select>
				<br /><br />
				
				<strong>{$this->lang->words['blist_per_page']}</strong><br />
				<select name='max_results' id='max_results' class='input_select'>
					".$this->__f__94b732dd31015e691826c432fe22fa17($pages,$featured,$blogs,$extra,$type,$sorting,$pinned)."				</select>
				<br /><br />
				
				<input type='submit' value=\"{$this->lang->words['_rarr']}\" class='input_submit' />
			</form>
		</div>
		<script type='text/javascript'>
			new ipb.Menu( $('blogs_filter'), $('blogs_filter_menucontent'), { stopClose: true } );
		</script>
		
		<!-- Entries -->
		" . ((!count($blogs) && !count($featured)) ? ("
			<div class='no_messages'>{$this->lang->words['no_blogs_found']}</div>
		") : ("<div class='ipsBox clear'>
				" . (($this->_canModerateBlogs) ? ("
					<form id=\"modform\" method=\"post\" action=\"{$this->settings['base_url']}\">
					<input type=\"hidden\" name=\"app\" value=\"blog\" />
					<input type=\"hidden\" name=\"module\" value=\"post\" />
					<input type=\"hidden\" name=\"section\" value=\"mod\" />
					<input type=\"hidden\" name=\"auth_key\" value=\"{$this->member->form_hash}\" />
					<input type=\"hidden\" value=\"{$this->request['selectedbids']}\" name=\"selectedbids\" id='selectedbids' />
					<input type=\"hidden\" name=\"do\" value=\"dommod\" />
					<input type=\"hidden\" name=\"type\" value=\"{$this->request['type']}\" />
					<input type=\"hidden\" name=\"blogact\" id=\"blogact\" value=\"\" />
				") : ("")) . "
				" . (($type == 'dash') ? ("<!-- FEATURED -->
					" . ((is_array($featured) AND count($featured)) ? ("
						".$this->__f__00cdae01e042bee41a1b57462de25674($pages,$featured,$blogs,$extra,$type,$sorting,$pinned)."					") : ("")) . "
					<!--NORMALS-->
					" . ((is_array( $blogs['normal'] ) && count( $blogs['normal'] )) ? ("
						".$this->__f__f6f519dd0f90832b761382a1673723ef($pages,$featured,$blogs,$extra,$type,$sorting,$pinned)."					") : ("")) . "") : ("<script type='text/javascript'>
						ipb.lang['error_blog_preview'] = \"{$this->lang->words['error_lastentry_preview']}\";
						ipb.lang['open_blog_preview']  = \"{$this->lang->words['view_lastentry_preview']}\";
					</script>
					
					<div class='ipsBox_container'>
						<table class='ipb_table'>
							<tr class='header hide'>
								<th scope='col' class='col_f_icon'>&nbsp;</th>
								<th scope='col' class='col_f_topic'>{$this->lang->words['sort_by_blogname']}</th>
								<th scope='col' class='col_f_starter short'>{$this->lang->words['sort_by_name']}</th>
								<th scope='col' class='col_f_views stats'>{$this->lang->words['sort_by_numentries']} / {$this->lang->words['sort_by_numcomments']}</th>
								<th scope='col' class='col_f_post'>{$this->lang->words['last_update_on']}</th>
								" . (($this->_canModerateBlogs) ? ("
									<th scope='col' class='col_f_mod short'>&nbsp;</th>
								") : ("")) . "
							</tr>
							" . ((is_array($featured) AND count($featured)) ? ("
								".$this->__f__bb1bc7f648b486d5dec818e573bf4306($pages,$featured,$blogs,$extra,$type,$sorting,$pinned)."							") : ("")) . "
							" . ((is_array( $blogs['pinned'] ) && count( $blogs['pinned'] )) ? ("
								".$this->__f__423044badb7422c4cd1c0c6a1ea67ab3($pages,$featured,$blogs,$extra,$type,$sorting,$pinned)."							") : ("")) . "
							" . ((is_array( $blogs['normal'] ) && count( $blogs['normal'] )) ? ("
								".$this->__f__3f9ee53f46fd0650b0e2403c86eb27db($pages,$featured,$blogs,$extra,$type,$sorting,$pinned)."							") : ("")) . "
						</table>
					</div>
					<script type='text/javascript'>
						ipb.blog.setUpBlogsAsTable();
					</script>")) . "
			</div>
			" . (($pages) ? ("{$pages}") : ("")) . "")) . "
	</div>
</div>
<br class='clear' />
<br />
<!-- STATISTICS -->
<div id='board_stats'>
	<ul class='ipsType_small ipsList_inline'>
		<li class='clear'>
			<span class='value'>" . $this->registry->getClass('class_localization')->formatNumber( $this->caches['blog_stats']['stats_num_blogs'] ) . "</span>
			{$this->lang->words['bstat_total_blogs']}
		</li>
		<li class='clear'>
			<span class='value'>" . $this->registry->getClass('class_localization')->formatNumber( $this->caches['blog_stats']['stats_num_entries'] ) . "</span>
			{$this->lang->words['bstat_total_entries']}
		</li>
		<li class='clear'>
			<span class='value'>" . $this->registry->getClass('class_localization')->formatNumber( $this->caches['blog_stats']['stats_num_comments'] ) . "</span>
			{$this->lang->words['bstat_total_comments']}
		</li>
		" . (($this->caches['blog_stats']['stats_last_blog_id']) ? ("
			<li class='clear'>
				<a class='value' href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$this->caches['blog_stats']['stats_last_blog_id']}", "public",'' ), "{$this->caches['blog_stats']['seo_stats_last_blog_name']}", "showblog" ) . "' title='{$this->lang->words['view_blog']}'>{$this->caches['blog_stats']['stats_last_blog_name']}</a>
				{$this->lang->words['bstat_latest_blog']}
			</li>
			<li class='clear'>
				" . IPSMember::makeProfileLink( $this->caches['blog_stats']['stats_last_blog_mname'], $this->caches['blog_stats']['stats_last_blog_mid'], $this->caches['blog_stats']['stats_last_blog_seoname'], 'value' ) . "
				{$this->lang->words['bstat_latest_blogger']}
			</li>
		") : ("<li class='clear'>
				" . (($this->memberData['g_blog_allowcreate'] AND $this->registry->blogFunctions->checkMaxBlogs() AND !$this->memberData['has_blog']) ? ("
					<a class='value' data-tooltip=\"{$this->lang->words['blist_start_blog']}\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=manage", "public",'' ), "false", "manageblog" ) . "\">---</a>
				") : ("
					<span class='value'>---</span>
				")) . "
				{$this->lang->words['bstat_latest_blog']}
			</li>")) . "
	</ul>
</div>
" . (($this->settings['blog_showactive']) ? ("<div id='board_statistics' class='statistics clearfix'>
		<h4 class='statistics_head'>" . sprintf( $this->lang->words['blog_active_users'], $extra['activeUsers']['stats']['total'], $this->settings['au_cutoff'] ) . "</h4>
		<p class='statistics_brief'>" . sprintf( $this->lang->words['active_users_detail'], $extra['activeUsers']['stats']['members'], $extra['activeUsers']['stats']['guests'], $extra['activeUsers']['stats']['anon'] ) . "</p>
		
		" . ((is_array( $extra['activeUsers']['names'] ) AND count( $extra['activeUsers']['names'] )) ? ("
			<br />
			<p>
				<span class='name'>" . implode( ",</span> <span class='name'>", $extra['activeUsers']['names'] ) . "</span>
			</p>
		") : ("")) . "
	</div>") : ("")) . "
" . ((!$this->settings['disable_lightbox']) ? ("
	" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'include_lightbox' ) ? $this->registry->getClass('output')->getTemplate('global')->include_lightbox() : '' ) . "
") : ("")) . "";
return $IPBHTML;
}


function __f__a9d3c69b4427971789bc943d73c2347e($pages, $featured=array(), $blogs=array(), $extra='', $type='dash', $sorting='', $pinned=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $this->memberData['has_blog'] as $blogid => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					" . (($data['_canPostIn']) ? ("<li" . (($data['blog_id']==$blog['blog_id']) ? (" class='current_blog'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=post&amp;section=post&amp;do=showform&amp;blogid={$data['blog_id']}", "public",'' ), "", "" ) . "'>{$data['blog_name']}</a></li>") : ("")) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__9764d044d8af2a02a19e1dcc14759558($pages, $featured=array(), $blogs=array(), $extra='', $type='dash', $sorting='', $pinned=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $pinned as $eid => $entry )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<li class='clearfix'>				
							" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($entry) : '' ) . "
							<div class='list_content'>
								" . (($entry['newpost']) ? ("
									 <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}&amp;show=newcomment", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\">" . $this->registry->getClass('output')->getReplacement("f_newpost") . "</a>
								") : ("")) . "
								<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}", "public",'' ), "{$entry['blog_seo_name']}", "showblog" ) . "'>{$entry['blog_name']}</a></strong>
								<div class='desc clearfix ipsType_smaller'>
									" . (($entry['entry_id']) ? ("
										<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\">{$entry['entry_name']}</a>
										<br />" . IPSMember::makeProfileLink( $entry['entry_author_name'], $entry['entry_author_id'], $entry['members_seo_name'] ) . "
									") : ("
										{$this->lang->words['pinned_no_entries']}
									")) . "
									 - " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($entry['_entry_date'],"short2", 0)) . "
								</div>
							</div>
						</li>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__428c269262d0437f80b5e1f6785d40d6($pages, $featured=array(), $blogs=array(), $extra='', $type='dash', $sorting='', $pinned=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( array( 'all', 'local', 'external' ) as $item )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<option value='{$item}' " . (($this->request['filter']==$item) ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words[ $sorting['the_filter'][$item] ]}</option>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__764db7dd4b709a0dfd90e2821da92f62($pages, $featured=array(), $blogs=array(), $extra='', $type='dash', $sorting='', $pinned=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( array( 'members_display_name', 'blog_name', 'blog_last_edate', 'blog_num_entries', 'blog_num_views', 'blog_num_comments', 'blog_last_comment', 'blog_rating' ) as $item )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<option value='{$item}' " . (($this->request['sort_key']==$item) ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words[ $sorting['the_sort_key'][$item] ]}</option>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__85301278ca33210511067ab6419ed933($pages, $featured=array(), $blogs=array(), $extra='', $type='dash', $sorting='', $pinned=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( array( 'desc', 'asc' ) as $item )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<option value='{$item}' " . (($this->request['sort_order']==$item) ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words[ $sorting['the_sort_order'][$item] ]}</option>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__94b732dd31015e691826c432fe22fa17($pages, $featured=array(), $blogs=array(), $extra='', $type='dash', $sorting='', $pinned=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( array( 10, 20, 30, 40, 50 ) as $item )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<option value='$item' " . (($this->request['max_results']==$item) ? ("selected=\"selected\"") : ("")) . ">{$item}</option>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__00cdae01e042bee41a1b57462de25674($pages, $featured=array(), $blogs=array(), $extra='', $type='dash', $sorting='', $pinned=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $featured as $fid => $entry )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							" . ( method_exists( $this->registry->getClass('output')->getTemplate('blog_list'), 'blogListRow' ) ? $this->registry->getClass('output')->getTemplate('blog_list')->blogListRow($entry) : '' ) . "
							<br />
						
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__f6f519dd0f90832b761382a1673723ef($pages, $featured=array(), $blogs=array(), $extra='', $type='dash', $sorting='', $pinned=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $blogs['normal'] as $fid => $entry )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							" . ( method_exists( $this->registry->getClass('output')->getTemplate('blog_list'), 'blogListRow' ) ? $this->registry->getClass('output')->getTemplate('blog_list')->blogListRow($entry) : '' ) . "
							<br />
						
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__bb1bc7f648b486d5dec818e573bf4306($pages, $featured=array(), $blogs=array(), $extra='', $type='dash', $sorting='', $pinned=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $featured as $fid => $entry )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
									" . ( method_exists( $this->registry->getClass('output')->getTemplate('blog_list'), 'blogTableRow' ) ? $this->registry->getClass('output')->getTemplate('blog_list')->blogTableRow($entry) : '' ) . "
								
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__423044badb7422c4cd1c0c6a1ea67ab3($pages, $featured=array(), $blogs=array(), $extra='', $type='dash', $sorting='', $pinned=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $blogs['pinned'] as $pinned )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
									" . ( method_exists( $this->registry->getClass('output')->getTemplate('blog_list'), 'blogTableRow' ) ? $this->registry->getClass('output')->getTemplate('blog_list')->blogTableRow($pinned) : '' ) . "
								
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__3f9ee53f46fd0650b0e2403c86eb27db($pages, $featured=array(), $blogs=array(), $extra='', $type='dash', $sorting='', $pinned=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $blogs['normal'] as $normal )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
									" . ( method_exists( $this->registry->getClass('output')->getTemplate('blog_list'), 'blogTableRow' ) ? $this->registry->getClass('output')->getTemplate('blog_list')->blogTableRow($normal) : '' ) . "
								
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- blogListRow --*/
function blogListRow($entry, $outSideBlog=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_list', $this->_funcHooks['blogListRow'] ) )
{
$count_e8fec844a560737c9fe96669dba11efd = is_array($this->functionData['blogListRow']) ? count($this->functionData['blogListRow']) : 0;
$this->functionData['blogListRow'][$count_e8fec844a560737c9fe96669dba11efd]['entry'] = $entry;
$this->functionData['blogListRow'][$count_e8fec844a560737c9fe96669dba11efd]['outSideBlog'] = $outSideBlog;
}
$IPBHTML .= "<div class='ipsBox_container'>
	<div class='entry" . (($entry['blog_pinned'] || $entry['entry_featured']) ? (" featured") : ("")) . "" . (($entry['entry_status'] != 'published') ? (" moderated") : ("")) . "" . (($entry['hide_private']) ? (" private") : ("")) . "' id='entry_{$entry['entry_id']}'>
		<div class='entry_header row2 ipsPad_half'>
			<div class='ipsPad_half right' id='entry_header_right'>
				" . (($entry['entry_status'] != 'published') ? ("<span class='ipsBadge ipsBadge_red'>" . (($entry['entry_future_date']) ? ("{$this->lang->words['entry_is_future_date']}") : ("{$this->lang->words['entry_is_a_draft']}")) . "</span>") : ("")) . "
				" . (($entry['blog_pinned'] || $entry['entry_featured']) ? ("<span class='ipsBadge ipsBadge_green'>{$this->lang->words['entry_is_featured']}</span>") : ("")) . "
			</div>
			{$entry['tags']['formatted']['prefix']}
			<div class='ipsPad_half left'>
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $entry, array( '_customClass' => 'ipsUserPhoto_medium' ) )) : '' ) . "
			</div>
			<h2 class='ipsType_pagetitle'>
				<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\" title='{$this->lang->words['view_entry_alt']}'>{$entry['entry_name']}</a>
			</h2>
			<div class='desc'>
				" . (($entry['entry_rss_import']) ? ("" . $this->registry->getClass('output')->getReplacement("blog_rss_import") . "&nbsp;") : ("")) . "
				{$this->lang->words['posted_by']} <strong>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($entry) : '' ) . "</strong> {$this->lang->words['in']} <strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&module=display&section=blog&blogid={$entry['blog_id']}", "public",'' ), "{$entry['blog_seo_name']}", "showblog" ) . "'>{$entry['blog_name']}</a></strong>, 
				" . (($entry['_categories']) ? ("
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('blog_global'), 'catsAsList' ) ? $this->registry->getClass('output')->getTemplate('blog_global')->catsAsList($entry['blog_id'], $entry['_categories']) : '' ) . "
				") : ("")) . "
				" . (($entry['entry_future_date']) ? ("<img src=\"{$this->settings['img_url']}/blog/time_entry.png\" data-tooltip=\"{$entry['entry_date']}\" title=\"{$entry['entry_date']}\" />&nbsp;") : ("")) . "" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($entry['_entry_date'],"short2", 1)) . "" . (($this->settings['blog_enable_rating']) ? (" - <span title=\"{$this->lang->words['entryhas_votes']} " . $this->registry->getClass('class_localization')->formatNumber( $entry['_rate_int'] ) . " {$this->lang->words['rate_out_of']}; {$this->lang->words['rate_votes']} " . $this->registry->getClass('class_localization')->formatNumber( $entry['entry_rating_count'] ) . "\">" . ( method_exists( $this->registry->getClass('output')->getTemplate('blog_list'), 'blog_rating' ) ? $this->registry->getClass('output')->getTemplate('blog_list')->blog_rating($entry['_rate_int']) : '' ) . "</span>") : ("")) . "
				 &middot; 
				" . $this->registry->getClass('class_localization')->formatNumber( $entry['entry_views'] ) . " {$this->lang->words['blog_num_views']}
				" . ((!empty( $entry['tags']['tags'] )) ? ("
					<br /><span class='ipsType_small desc blend_links'><img src='{$this->settings['img_url']}/icon_tag.png' /> {$entry['tags']['formatted']['truncatedWithLinks']}</span>
				") : ("")) . "
			</div>
			
			<br class='clear' />
		</div>
		<div class='entry_content ipsType_textblock ipsPad'>
			" . (($entry['hide_private']) ? ("
				{$this->lang->words['blog_private_entry']}
				<div class='desc right'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}&amp;showprivate=1", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\">{$this->lang->words['blog_show_privateentry']} {$this->lang->words['_rarr']}</a></div>
			") : ("" . (($this->settings['blog_list_full']) ? ("" . (($entry['entry_image']) ? ("
						<a href='{$this->settings['upload_url']}/{$entry['entry_image']}' rel='lightbox' class='ipsPad left'>
							<img src='{$this->settings['upload_url']}/thumb_{$entry['entry_image']}' alt='{$entry['entry_name']}' />
						</a>
					") : ("")) . "
					{$entry['entry']}
					<!--IBF.ATTACHMENT_{$entry['entry_id']}-->") : ("" . (($entry['entry_image']) ? ("
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}", "public",'' ), "", "" ) . "' class='ipsPad left'>
							<img src='{$this->settings['upload_url']}/thumb_{$entry['entry_image']}' alt='{$entry['entry_name']}' " . IPSLib::getTemplateDimensions("{$this->settings['upload_url']}/{$entry['entry_image']}", '', '')  . " />
						</a>
					") : ("")) . "
					{$entry['entry_short']}")) . "")) . "
			<br class='clear'/>
		</div>
		<div class='ipsPad'>
			" . (($this->memberData['member_id'] && !$outSideBlog) ? ("<span class='right'>
					&nbsp;&nbsp;
					" . (($this->memberData['g_is_supmod']) ? ("
						<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}&amp;banish=1&amp;return=home", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\" title=\"{$this->lang->words['blist_banish']}\">" . $this->registry->getClass('output')->getReplacement("blog_banish") . "</a>
					") : ("")) . "
					" . (($this->_canModerateBlogs) ? ("&nbsp;&nbsp;<input type='checkbox' id='bmod_{$entry['blog_id']}' class='input_check blog_mod' data-pinned=\"{$entry['blog_pinned']}\" data-enabled=\"" . (($entry['blog_disabled'] == 0) ? ("1") : ("0")) . "\"" . (($entry['bidon']) ? (" checked='checked'") : ("")) . " /> <label for='bmod_{$entry['blog_id']}' class='hide'>{$this->lang->words['select_for_mod']}</label>") : ("")) . "
				</span>") : ("")) . "
			" . (($entry['_hasMore']) ? ("
				<a class='right' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\">
					<span class='ipsButton_secondary'>{$this->lang->words['read_more_go_on']} {$this->lang->words['_rarr']}</span>
				</a>
				<br />
			") : ("")) . "
			" . (($entry['entry_queued_comments'] && $entry['_can_approve']) ? ("<span class='ipsBadge ipsBadge_orange' data-tooltip=\"" . sprintf( $this->lang->words['entry_queued_comments'], $entry['entry_queued_comments'] ) . "\">{$this->lang->words['f_queued_badge']}</span>") : ("")) . "
			" . (($entry['entry_locked']) ? ("" . $this->registry->getClass('output')->getReplacement("blog_locked") . "") : ("" . (($entry['entry_num_comments'] AND $entry['entry_last_comment_date'] > $entry['_lastRead']) ? ("" . $this->registry->getClass('output')->getReplacement("blog_comments_new") . "") : ("" . $this->registry->getClass('output')->getReplacement("blog_comments") . "")) . "")) . "
			<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "#commentsStart\">{$entry['entry_num_comments']} {$this->lang->words['entry_comments']}</a>
		</div>
	</div>
</div>";
return $IPBHTML;
}

/* -- blogPreview --*/
function blogPreview($blog, $entry) {
$IPBHTML = "";
$IPBHTML .= "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $entry, array( '_customClass' => 'ipsUserPhoto_medium' ) )) : '' ) . "
<div style='margin-left: 80px'>
	<p class='preview_info'><strong>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($entry) : '' ) . "</strong></p>
	{$entry['entry']}
</div>
<br class='clear' />
<br />
<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "' class='ipsButton'>{$this->lang->words['preview_goto_entry']}</a>";
return $IPBHTML;
}

/* -- blogTableRow --*/
function blogTableRow($blog) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_list', $this->_funcHooks['blogTableRow'] ) )
{
$count_456bfa2ff06e236dbc6f1f84d1103cc7 = is_array($this->functionData['blogTableRow']) ? count($this->functionData['blogTableRow']) : 0;
$this->functionData['blogTableRow'][$count_456bfa2ff06e236dbc6f1f84d1103cc7]['blog'] = $blog;
}
$IPBHTML .= "" . (($blog['blog_type'] == 'local') ? ("<tr id='brow_{$blog['blog_last_entry']}' data-bid=\"{$blog['blog_last_entry']}\" class='__blog expandable" . (($blog['last_read'] < $blog['blog_last_update']) ? (" unread") : ("")) . "" . ((in_array( $blog['blog_view_level'], array('private','privateclub') )) ? (" private") : ("")) . "" . (($blog['blog_disabled']) ? (" moderated") : ("")) . "'>
		<td class='col_b_icon altrow short'>
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('blog_list'), 'generateBlogIcon' ) ? $this->registry->getClass('output')->getTemplate('blog_list')->generateBlogIcon($blog) : '' ) . "
		</td>
		<td class='col_f_content blog_title'>			
			<h4><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$blog['blog_id']}", "public",'' ), "{$blog['blog_seo_name']}", "showblog" ) . "\" title='{$this->lang->words['view_blog']}' class='topic_title'>{$blog['blog_name']}</a></h4>
			<br />
			<span class='desc lighter blend_links'>{$blog['blog_desc']}</span>
		</td>
		<td>
			" . (($blog['blog_disabled']) ? ("<span class='ipsBadge ipsBadge_red'>{$this->lang->words['blog_disabled_prefix']}</span>
				" . (($blog['blog_pinned']) ? ("
					<br /><span class='ipsBadge ipsBadge_purple'>{$this->lang->words['pre_pinned']}</span>
				") : ("")) . "") : ("" . (($blog['blog_view_level'] == 'private') ? ("
					<span class='ipsBadge ipsBadge_red'>{$this->lang->words['cat__private']}</span>
				") : ("")) . "
				" . (($blog['blog_view_level'] == 'privateclub') ? ("
					<span class='ipsBadge ipsBadge_red'>{$this->lang->words['cat__privateclub']}</span>
				") : ("")) . "
				" . (($blog['entry_featured']) ? ("
					<span class='ipsBadge ipsBadge_green'>{$this->lang->words['bview_featured']}</span>
				") : ("" . (($blog['blog_pinned']) ? ("
						<span class='ipsBadge ipsBadge_purple'>{$this->lang->words['pre_pinned']}</span>
					") : ("")) . "")) . "")) . "
		</td>
		" . (($blog['blog_last_entry']) ? ("
			<td class='col_f_preview __blog_preview'>			
				<a class='expander closed' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$blog['blog_id']}&amp;showentry={$blog['blog_last_entry']}", "public",'' ), "{$blog['entry_name_seo']}", "showentry" ) . "\" title='{$this->lang->words['view_lastentry_preview']}'>&nbsp;</a>				
			</td>
		") : ("
			<td>&nbsp;</td>
		")) . "
		<td>
			" . (($blog['blog_settings']['allowrss'] && $blog['blog_view_level'] == 'public' && !$blog['blog_disabled']) ? ("<div class='right'>
					" . (($blog['blog_settings']['rssfeedburner']) ? ("
						<a class='expander' href=\"http://feeds.feedburner.com/{$blog['blog_settings']['rssfeedburner']}\" title='{$this->lang->words['blog_syndicate']}'><img src='{$this->settings['img_url']}/blog/rss.png' alt='{$this->lang->words['rss_feed']}'/></a>
					") : ("
						<a class='expander' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=rss&amp;type=blog&amp;blogid={$blog['blog_id']}", "public",'' ), "{$blog['blog_seo_name']}", "blogrss" ) . "\" title='{$this->lang->words['blog_syndicate']}'><img src='{$this->settings['img_url']}/blog/rss.png' alt='{$this->lang->words['rss_feed']}'/></a>
					")) . "
				</div>") : ("")) . "
		</td>
		<td class='col_f_starter short'>
			" . (($blog['blog_groupblog']) ? ("
				<img src='{$this->settings['img_url']}/blog/blog_group.png' alt='' /> {$blog['blog_groupblog_name']}
			") : ("
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($blog) : '' ) . "
			")) . "
		</td>
		<td class='col_f_views desc blend_links'>
			<ul>
				<li class='views desc'>" . $this->registry->getClass('class_localization')->formatNumber( $blog['blog_num_entries'] ) . " {$this->lang->words['entries_fn']}</li>
				<li class='views desc'>" . $this->registry->getClass('class_localization')->formatNumber( $blog['blog_num_comments'] ) . " {$this->lang->words['comments_fn']}</li>
				<li class='views desc'>" . $this->registry->getClass('class_localization')->formatNumber( $blog['blog_num_views'] ) . " {$this->lang->words['blog_num_views']}</li>
			</ul>
		</td>
		<td class='col_f_post'>
			<ul class='ipsList_withmediumphoto'>
				<li class='clearfix'>
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $blog, array( '_customClass' => 'ipsUserPhoto_medium' ) )) : '' ) . "
					<div class='list_content'>
						" . (($blog['blog_last_entry']) ? ("
							<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$blog['blog_id']}&amp;showentry={$blog['blog_last_entry']}", "public",'' ), "{$blog['entry_name_seo']}", "showentry" ) . "\" title='{$this->lang->words['entry_view']}'>" . IPSText::truncate( $blog['blog_last_entryname'], 50 ) . "</a>
							<br />{$this->lang->words['by_ucfirst']} " . IPSMember::makeProfileLink( $blog['entry_author_name'], $blog['entry_author_id']) . "
							<br /><span class='ipsType_smaller'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($blog['blog_last_date'],"date", 0)) . "</span>
						") : ("
							<em>{$this->lang->words['profile_noblogentries']}</em>
						")) . "
					</div>
				</li>
			</ul>
		</td>
		" . (($this->_canModerateBlogs) ? ("<td class='col_f_mod short'>
				<input type='checkbox' id='bmod_{$blog['blog_id']}' class='input_check blog_mod' data-pinned=\"{$blog['blog_pinned']}\" data-enabled=\"" . (($blog['blog_disabled'] == 0) ? ("1") : ("0")) . "\" " . (($blog['bidon']) ? ("checked='checked'") : ("")) . " />
			</td>") : ("")) . "
	</tr>") : ("<tr class='" . (($entry['blog_disabled']) ? (" moderated") : ("")) . "'>
		<td class='short'>
			" . $this->registry->getClass('output')->getReplacement("t_moved") . "
		</td>
		<td class='col_f_content'>
			<h4><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$blog['blog_id']}", "public",'' ), "{$blog['blog_seo_name']}", "showblog" ) . "\"" . (($this->settings['links_external']) ? (" target='_blank'") : ("")) . " title='{$this->lang->words['view_blog']}' class='topic_title'>{$blog['blog_name']}</a></h4>
			<br />
			<span class='desc lighter blend_links'>{$blog['blog_desc']}</span>
		</td>
		<td>
			" . (($blog['blog_disabled']) ? ("
				<span class='ipsBadge ipsBadge_red'>{$this->lang->words['blog_disabled_prefix']}</span>
			") : ("" . (($blog['entry_featured']) ? ("
					<span class='ipsBadge ipsBadge_green'>{$this->lang->words['bview_featured']}</span>
				") : ("" . (($blog['blog_pinned']) ? ("
						<span class='ipsBadge ipsBadge_purple'>{$this->lang->words['pre_pinned']}</span>
					") : ("")) . "")) . "")) . "
		</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td class='col_f_starter short'>
			" . (($blog['blog_groupblog']) ? ("
				<img src='{$this->settings['img_url']}/blog/blog_group.png' alt='' /> {$blog['blog_groupblog_name']}
			") : ("
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($blog) : '' ) . "
			")) . "
		</td>
		<td class='col_f_views desc blend_links'>
			<ul>
				<li class='views desc'>" . $this->registry->getClass('class_localization')->formatNumber( $blog['blog_num_exthits'] ) . " {$this->lang->words['blist_redirect_hits']}</li>
			</ul>
		</td>
		<td class='col_f_post'>
			<ul class='ipsList_withmediumphoto'>
				<li class='clearfix'>
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $blog, array( '_customClass' => 'ipsUserPhoto_medium' ) )) : '' ) . "
					<div class='list_content'>
						<em>{$this->lang->words['blog_external']}</em>
					</div>
				</li>
			</ul>
		</td>
		" . (($this->_canModerateBlogs) ? ("<td class='col_f_mod short'>
				<input type='checkbox' id='bmod_{$blog['blog_id']}' class='input_check blog_mod' data-pinned=\"{$blog['blog_pinned']}\" data-enabled=\"" . (($blog['blog_disabled'] == 0) ? ("1") : ("0")) . "\" " . (($blog['bidon']) ? ("selected='selected'") : ("")) . " />
			</td>") : ("")) . "
	</tr>")) . "";
return $IPBHTML;
}

/* -- generateBlogIcon --*/
function generateBlogIcon($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_list', $this->_funcHooks['generateBlogIcon'] ) )
{
$count_98b3b2c764aeb07eea8598c5d1f8fa2e = is_array($this->functionData['generateBlogIcon']) ? count($this->functionData['generateBlogIcon']) : 0;
$this->functionData['generateBlogIcon'][$count_98b3b2c764aeb07eea8598c5d1f8fa2e]['data'] = $data;
}

$isUnread = ($data['last_read'] < $data['blog_last_update']) ? true : false;
$IPBHTML .= "" . (($isUnread) ? ("
	<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$data['blog_id']}&amp;showentry={$data['blog_last_entry']}&amp;show=newcomment", "public",'' ), "{$data['entry_name_seo']}", "showentry" ) . "' title='{$this->lang->words['view_newest_comment']}'>
") : ("")) . "
" . (($blog['blog_disabled']) ? ("
	<span title=\"{$this->lang->words['blog_global_disabled_title']}\">" . $this->registry->getClass('output')->getReplacement("t_closed") . "</span>
") : ("" . (($this->registry->blogFunctions->ownsBlog( $data )) ? ("" . (($isUnread) ? ("
			" . $this->registry->getClass('output')->getReplacement("t_unread_dot") . "
		") : ("")) . "") : ("" . (($isUnread) ? ("
			" . $this->registry->getClass('output')->getReplacement("t_unread") . "
		") : ("")) . "")) . "")) . "
" . (($isUnread) ? ("
	</a>
") : ("")) . "";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>